# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

from ..utils import MAX_GRID_SIZE_X

logger = logging.getLogger(__name__)


@triton.jit
def _absolute_kernel(
    x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr
):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        x = tl.load(x_ptr + offsets, mask=mask)
        zero = x * 0
        is_neg = x < zero
        y = tl.where(is_neg, -x, x)
        tl.store(out_ptr + offsets, y, mask=mask)
        pid += grid_0


@triton.jit
def _absolute_complex_kernel(
    ri_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr
):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        base = offsets * 2
        re = tl.load(ri_ptr + base, mask=mask)
        im = tl.load(ri_ptr + base + 1, mask=mask)
        y = tl.sqrt(re * re + im * im)
        tl.store(out_ptr + offsets, y, mask=mask)
        pid += grid_0


def absolute(input: torch.Tensor):
    logger.debug("GEMS_CAMBRICON ABSOLUTE")
    x = input.contiguous()
    n_elements = x.numel()
    M = triton.cdiv(n_elements, 1024)
    grid = min(M, MAX_GRID_SIZE_X // 4)

    with torch_device_fn.device(input.device):
        if x.is_complex():
            ri = torch.view_as_real(x).contiguous()
            out_dtype = x.real.dtype
            out = torch.empty(x.shape, dtype=out_dtype, device=x.device)
            _absolute_complex_kernel[(grid,)](ri, out, n_elements, BLOCK_SIZE=1024, M=M)
            return out
        else:
            out = torch.empty_like(x)
            _absolute_kernel[(grid,)](x, out, n_elements, BLOCK_SIZE=1024, M=M)
            return out
