# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

from ..utils import MAX_GRID_SIZE_X

logger = logging.getLogger(__name__)


@triton.jit
def _alias_copy_kernel(
    src_ptr, dst_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr
):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        vals = tl.load(src_ptr + offsets, mask=mask)
        tl.store(dst_ptr + offsets, vals, mask=mask)
        pid += grid_0


def alias_copy(x: torch.Tensor):
    logger.debug("GEMS_CAMBRICON ALIAS_COPY")
    """
    Wrapper for aten::alias_copy
    Creates and returns a copy of `x` with identical content.
    """
    out = torch.empty_like(x)
    n_elements = out.numel()
    if n_elements == 0:
        return out
    # Ensure contiguous memory for efficient linear copy
    src = x.contiguous() if not x.is_contiguous() else x
    if not out.is_contiguous():
        out = out.contiguous()
    if src.dtype != out.dtype:
        raise RuntimeError("alias_copy: dtype mismatch between input and output.")
    M = triton.cdiv(n_elements, 1024)
    grid = min(M, MAX_GRID_SIZE_X // 4)
    with torch_device_fn.device(x.device):
        _alias_copy_kernel[(grid,)](src, out, n_elements, BLOCK_SIZE=1024, M=M)
    return out


def alias_copy_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS_CAMBRICON ALIAS_COPY_OUT")
    """
    Wrapper for aten::alias_copy.out
    Copies `x` into `out` and returns `out`.
    """
    if x.dtype != out.dtype:
        raise RuntimeError("alias_copy_out: dtype of input and output must match.")
    if x.numel() != out.numel():
        raise RuntimeError(
            "alias_copy_out: input and output must have the same number of elements."
        )
    if x.device != out.device:
        raise RuntimeError(
            "alias_copy_out: input and output must be on the same device."
        )
    if not out.is_contiguous():
        raise RuntimeError("alias_copy_out: output tensor must be contiguous.")
    src = x.contiguous() if not x.is_contiguous() else x
    n_elements = out.numel()
    if n_elements == 0:
        return out
    M = triton.cdiv(n_elements, 1024)
    grid = min(M, MAX_GRID_SIZE_X // 4)
    with torch_device_fn.device(x.device):
        _alias_copy_kernel[(grid,)](src, out, n_elements, BLOCK_SIZE=1024, M=M)
    return out
