# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

from ..utils import MAX_GRID_SIZE_X

logger = logging.getLogger(__name__)


@triton.jit
def arcsinh_kernel_(x_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x = tl.load(x_ptr + offsets, mask=mask)
        x32 = x.to(tl.float32)
        x2 = x32 * x32
        tmp = tl.sqrt(x2 + 1.0)
        y32 = tl.log(x32 + tmp)
        y = y32.to(x.dtype)

        tl.store(x_ptr + offsets, y, mask=mask)
        pid += grid_0


def arcsinh_(*args, **kwargs):
    logger.debug("GEMS_CAMBRICON ARCSINH_")
    if len(args) == 0:
        raise TypeError("arcsinh_ expected at least 1 argument (a Tensor)")
    x = args[0]
    if not isinstance(x, torch.Tensor):
        raise TypeError("arcsinh_ expected a torch.Tensor as the first argument")

    if (not x.is_contiguous()) or (not x.dtype.is_floating_point):
        torch.ops.aten.arcsinh_(x)
        return x

    n_elements = x.numel()
    M = triton.cdiv(n_elements, 1024)
    grid = min(M, MAX_GRID_SIZE_X // 4)
    with torch_device_fn.device(x.device):
        arcsinh_kernel_[(grid,)](x, n_elements, BLOCK_SIZE=1024, M=M)
    return x
