# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import tl_extra_shim

from ..utils.pointwise_dynamic import pointwise_dynamic

_atan2 = tl_extra_shim.atan2

logger = logging.getLogger(__name__)


@pointwise_dynamic(is_tensor=[True, True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def arctan2_kernel(x, y, inplace):
    return _atan2(x.to(tl.float32), y.to(tl.float32))


def arctan2(input, other):
    logger.debug("GEMS_CAMBRICON ARCTAN2")
    return arctan2_kernel(input, other, False)


def arctan2_(input, other):
    logger.debug("GEMS_CAMBRICON ARCTAN2_")
    arctan2_kernel(input, other, True, out0=input)
    return input
