# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

from ..utils import TOTAL_CORE_NUM
from .topk import topk as gems_topk

logger = logging.getLogger(__name__)


@triton.jit
def _pick(vals, pos: tl.tensor, cols, BLOCK_N: tl.constexpr):
    return tl.max(tl.where(cols == pos, vals, -float("inf")), axis=0)


@triton.jit
def _pick_i64(vals, pos: tl.tensor, cols, BLOCK_N: tl.constexpr):
    return tl.max(tl.where(cols == pos, vals, -1), axis=0)


@triton.jit
def _swap(vals, idxs, a: tl.tensor, b: tl.tensor, cols, BLOCK_N: tl.constexpr):
    va = _pick(vals, a, cols, BLOCK_N)
    vb = _pick(vals, b, cols, BLOCK_N)
    ia = _pick_i64(idxs, a, cols, BLOCK_N)
    ib = _pick_i64(idxs, b, cols, BLOCK_N)
    vals = tl.where(cols == a, vb, vals)
    vals = tl.where(cols == b, va, vals)
    idxs = tl.where(cols == a, ib, idxs)
    idxs = tl.where(cols == b, ia, idxs)
    return vals, idxs


@libentry()
@triton.jit
def _kthvalue_quick_select_kernel(
    inp,
    out,
    out_idx,
    M: tl.constexpr,
    N: tl.constexpr,
    K: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    pid = tl.program_id(0)
    grid_n = tl.num_programs(0)
    cols = tl.arange(0, BLOCK_N)
    mask = cols < N

    for row in tl.range(pid, M, grid_n):
        vals = tl.load(inp + row * N + cols, mask=mask, other=float("inf")).to(
            tl.float32
        )
        idxs = tl.where(mask, cols, 0).to(tl.int64)

        left = tl.full((), 0, dtype=tl.int32)
        right = tl.full((), N - 1, dtype=tl.int32)
        kth = tl.full((), K - 1, dtype=tl.int32)
        active = True

        while active:
            if right <= left:
                active = False
            elif right == left + 1:
                if _pick(vals, left, cols, BLOCK_N) > _pick(vals, right, cols, BLOCK_N):
                    vals, idxs = _swap(vals, idxs, left, right, cols, BLOCK_N)
                active = False
            else:
                pivot_pos = left + ((right - left) // 2)
                vals, idxs = _swap(vals, idxs, pivot_pos, left + 1, cols, BLOCK_N)

                if _pick(vals, left + 1, cols, BLOCK_N) > _pick(
                    vals, right, cols, BLOCK_N
                ):
                    vals, idxs = _swap(vals, idxs, left + 1, right, cols, BLOCK_N)
                if _pick(vals, left, cols, BLOCK_N) > _pick(vals, right, cols, BLOCK_N):
                    vals, idxs = _swap(vals, idxs, left, right, cols, BLOCK_N)
                if _pick(vals, left + 1, cols, BLOCK_N) > _pick(
                    vals, left, cols, BLOCK_N
                ):
                    vals, idxs = _swap(vals, idxs, left + 1, left, cols, BLOCK_N)

                i = left + 1
                j = right
                pivot = _pick(vals, left, cols, BLOCK_N)
                partition_done = False
                while not partition_done:
                    i += 1
                    while pivot > _pick(vals, i, cols, BLOCK_N):
                        i += 1
                    j -= 1
                    while _pick(vals, j, cols, BLOCK_N) > pivot:
                        j -= 1
                    if j < i:
                        partition_done = True
                    else:
                        vals, idxs = _swap(vals, idxs, i, j, cols, BLOCK_N)

                vals, idxs = _swap(vals, idxs, left, j, cols, BLOCK_N)
                if j <= kth:
                    left = i
                if j >= kth:
                    right = j - 1

        kth_val = _pick(vals, kth, cols, BLOCK_N)
        kth_idx = _pick_i64(idxs, kth, cols, BLOCK_N)
        tl.store(out + row, kth_val)
        tl.store(out_idx + row, kth_idx)


def kthvalue(inp, k, dim=-1, keepdim=False):
    """
    Returns the kth smallest elements and their indices along the given dimension.

    This implementation uses topk with largest=False to get the k smallest elements,
    then extracts the kth element from the result.
    """
    logger.debug("GEMS_CAMBRICON KTHVALUE")

    original_dtype = inp.dtype
    if inp.dtype not in (torch.float32,):
        inp = inp.to(torch.float32)

    # Get dimensions
    ndim = inp.ndim

    # Validate dim before normalization (match PyTorch error semantics)
    if dim < -ndim or dim >= ndim:
        raise IndexError(
            f"Dimension out of range (expected to be in range of [{-ndim}, {ndim - 1}], but got {dim})"
        )

    # Handle negative dim
    if dim < 0:
        dim = dim + inp.ndim

    dim_size = inp.shape[dim]

    # Check empty reduction dim before k validation (match PyTorch)
    if dim_size == 0:
        raise IndexError(
            f"kthvalue(): Expected reduction dim {dim} to have non-zero size."
        )

    if k < 1 or k > dim_size:
        raise RuntimeError(
            f"kthvalue(): selected number k out of range for dimension {dim}"
        )

    # Handle empty tensor
    if inp.numel() == 0:
        out_shape = list(inp.shape)
        if keepdim:
            out_shape[dim] = 1
        else:
            del out_shape[dim]
        return (
            torch.empty(out_shape, dtype=inp.dtype, device=inp.device),
            torch.empty(out_shape, dtype=torch.int64, device=inp.device),
        )

    # Determine if we need to transpose
    need_transpose = dim != ndim - 1

    if need_transpose:
        # Transpose so that dim becomes the last dimension
        perm = list(range(ndim))
        perm[dim] = ndim - 1
        perm[-1] = dim
        inp = inp.permute(perm).contiguous()

    topk_batch = inp.numel() // dim_size
    if dim_size <= 256:
        values_flat = torch.empty((topk_batch,), device=inp.device, dtype=inp.dtype)
        indices_flat = torch.empty((topk_batch,), device=inp.device, dtype=torch.int64)
        inp_2d = inp.reshape(topk_batch, dim_size)
        block_n = triton.next_power_of_2(dim_size)
        grid = (min(topk_batch, TOTAL_CORE_NUM),)
        with torch_device_fn.device(inp.device):
            _kthvalue_quick_select_kernel[grid](
                inp_2d,
                values_flat,
                indices_flat,
                topk_batch,
                dim_size,
                K=k,
                BLOCK_N=block_n,
            )
        values_kth = values_flat.reshape(*inp.shape[:-1], 1)
        indices_kth = indices_flat.reshape(*inp.shape[:-1], 1)
    else:
        # Request a slightly wider sorted prefix for sort-path cases so kthvalue
        # tie ordering matches the CPU reference. Split large batches so
        # Cambricon's 16-bit grid dimension limit is not exceeded.
        use_wide_topk = k > math.log2(dim_size)
        topk_k = (
            min(dim_size, max(k, int(math.log2(dim_size)) + 2)) if use_wide_topk else k
        )
        if use_wide_topk and topk_batch > TOTAL_CORE_NUM:
            inp_2d = inp.reshape(topk_batch, dim_size)
            values_2d = torch.empty(
                (topk_batch, topk_k), device=inp.device, dtype=inp.dtype
            )
            indices_2d = torch.empty(
                (topk_batch, topk_k), device=inp.device, dtype=torch.int64
            )
            for row_start in range(0, topk_batch, TOTAL_CORE_NUM):
                row_end = min(row_start + TOTAL_CORE_NUM, topk_batch)
                values_part, indices_part = gems_topk(
                    inp_2d[row_start:row_end],
                    topk_k,
                    dim=-1,
                    largest=False,
                    sorted=True,
                )
                values_2d[row_start:row_end] = values_part
                indices_2d[row_start:row_end] = indices_part
            values = values_2d.reshape(*inp.shape[:-1], topk_k)
            indices = indices_2d.reshape(*inp.shape[:-1], topk_k)
        else:
            values, indices = gems_topk(inp, topk_k, dim=-1, largest=False, sorted=True)

        # Extract the kth element (index k-1 in 0-indexed).
        slice_idx = k - 1
        values_kth = values[..., slice_idx : slice_idx + 1]
        indices_kth = indices[..., slice_idx : slice_idx + 1]

    if need_transpose:
        # Transpose back
        # After topk with k=1 on transposed input, values_kth shape is (other_dims, 1)
        # We need to permute back
        # Original perm maps: dim -> last, last -> dim
        # Inverse perm should map: last -> dim, dim -> last
        inv_perm = list(range(ndim))
        inv_perm[dim] = ndim - 1
        inv_perm[-1] = dim

        values = values_kth.permute(inv_perm)
        indices = indices_kth.permute(inv_perm)

        if not keepdim:
            values = values.squeeze(dim)
            indices = indices.squeeze(dim)
    else:
        if not keepdim:
            values = values_kth.squeeze(-1)
            indices = indices_kth.squeeze(-1)
        else:
            values = values_kth
            indices = indices_kth

    return values.to(original_dtype), indices
