# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from triton.backends.mlu import driver

import flag_gems

logger = logging.getLogger(__name__)


@triton.jit
def _margin_ranking_loss_elementwise_kernel(
    x1_ptr,
    x2_ptr,
    target_ptr,
    out_ptr,
    n_elements,
    margin,
    INPUT_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
    total_blocks: tl.constexpr,
):
    pid = tl.program_id(0)
    num_jobs = tl.num_programs(0)

    for block_id in range(pid, total_blocks, num_jobs):
        block_start = block_id * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x1 = tl.load(x1_ptr + offsets, mask=mask, other=0.0)
        x2 = tl.load(x2_ptr + offsets, mask=mask, other=0.0)
        y = tl.load(target_ptr + offsets, mask=mask, other=0.0)

        # Match CPU behavior: compute in float32 then round to input dtype
        # at each intermediate step to replicate bfloat16 arithmetic
        x1f = x1.to(tl.float32)
        x2f = x2.to(tl.float32)
        yf = y.to(tl.float32)

        diff = (x1f - x2f).to(INPUT_DTYPE).to(tl.float32)
        val = (-yf * diff + margin).to(INPUT_DTYPE).to(tl.float32)
        loss = tl.maximum(val, 0.0)

        tl.store(out_ptr + offsets, loss.to(INPUT_DTYPE), mask=mask)


@triton.jit
def _margin_ranking_loss_sum_kernel(
    x1_ptr,
    x2_ptr,
    target_ptr,
    out_ptr,
    n_elements,
    margin,
    INPUT_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
    total_blocks: tl.constexpr,
):
    pid = tl.program_id(0)
    num_jobs = tl.num_programs(0)

    for block_id in range(pid, total_blocks, num_jobs):
        block_start = block_id * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x1 = tl.load(x1_ptr + offsets, mask=mask, other=0.0)
        x2 = tl.load(x2_ptr + offsets, mask=mask, other=0.0)
        y = tl.load(target_ptr + offsets, mask=mask, other=0.0)

        x1f = x1.to(tl.float32)
        x2f = x2.to(tl.float32)
        yf = y.to(tl.float32)

        diff = (x1f - x2f).to(INPUT_DTYPE).to(tl.float32)
        val = (-yf * diff + margin).to(INPUT_DTYPE).to(tl.float32)
        loss = tl.maximum(val, 0.0)
        loss = tl.where(mask, loss, 0.0)

        acc = tl.sum(loss, axis=0)
        tl.atomic_add(out_ptr, acc)


@triton.jit
def _margin_ranking_loss_backward_kernel(
    grad_output_ptr,
    x1_ptr,
    x2_ptr,
    y_ptr,
    grad_x1_ptr,
    grad_x2_ptr,
    margin,
    n_elements,
    INPUT_DTYPE: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
    total_blocks: tl.constexpr,
):
    pid = tl.program_id(0)
    num_jobs = tl.num_programs(0)

    for block_id in range(pid, total_blocks, num_jobs):
        block_start = block_id * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        grad_output = tl.load(grad_output_ptr + offsets, mask=mask, other=0.0)
        x1 = tl.load(x1_ptr + offsets, mask=mask, other=0.0)
        x2 = tl.load(x2_ptr + offsets, mask=mask, other=0.0)
        y = tl.load(y_ptr + offsets, mask=mask, other=0.0)

        x1f = x1.to(tl.float32)
        x2f = x2.to(tl.float32)
        yf = y.to(tl.float32)
        gradf = grad_output.to(tl.float32)

        diff = (x1f - x2f).to(INPUT_DTYPE).to(tl.float32)
        val = (-yf * diff + margin).to(INPUT_DTYPE).to(tl.float32)
        active_mask = val > 0

        grad_x1 = tl.where(active_mask, -yf * gradf, 0.0)
        grad_x2 = tl.where(active_mask, yf * gradf, 0.0)

        tl.store(grad_x1_ptr + offsets, grad_x1, mask=mask)
        tl.store(grad_x2_ptr + offsets, grad_x2, mask=mask)


def _get_triton_dtype(torch_dtype):
    if torch_dtype == torch.float32:
        return tl.float32
    elif torch_dtype == torch.float16:
        return tl.float16
    elif torch_dtype == torch.bfloat16:
        return tl.bfloat16
    else:
        return tl.float32


class MarginRankingLossOp(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x1, x2, target, margin=0.0, reduction="mean"):
        logger.debug("GEMS_CAMBRICON MARGIN_RANKING_LOSS")

        if not (
            x1.is_floating_point()
            and x2.is_floating_point()
            and target.is_floating_point()
        ):
            raise ValueError("All inputs must be floating point tensors")

        if isinstance(reduction, int):
            reduction = {0: "none", 1: "mean", 2: "sum"}.get(reduction, "mean")
        if reduction not in ("none", "mean", "sum"):
            raise ValueError("reduction must be one of 'none', 'mean', or 'sum'")

        device = x1.device
        if not (isinstance(device, torch.device) and device.type == flag_gems.device):
            return torch.ops.aten.margin_ranking_loss(
                x1,
                x2,
                target,
                float(margin),
                {"none": 0, "mean": 1, "sum": 2}[reduction],
            )

        x1_b, x2_b, tgt_b = torch.broadcast_tensors(x1, x2, target)

        common_dtype = x1_b.dtype if x1_b.is_floating_point() else torch.float32
        x1_b = x1_b.to(dtype=common_dtype)
        x2_b = x2_b.to(dtype=common_dtype)
        tgt_b = tgt_b.to(dtype=common_dtype)

        x1_c = x1_b.contiguous().view(-1)
        x2_c = x2_b.contiguous().view(-1)
        tgt_c = tgt_b.contiguous().view(-1)

        n_elements = x1_c.numel()
        triton_dtype = _get_triton_dtype(common_dtype)

        ctx.save_for_backward(x1_c, x2_c, tgt_c)
        ctx.reduction = reduction
        ctx.margin = margin
        ctx.n_elements = n_elements
        ctx.original_shape = x1_b.shape
        ctx.common_dtype = common_dtype
        ctx.triton_dtype = triton_dtype

        # Get hardware core count for grid optimization
        _devprob = driver.BangUtils().get_device_properties(torch.mlu.current_device())
        TOTAL_CORE_NUM = _devprob.get("cluster_num") * _devprob.get(
            "core_num_per_cluster"
        )
        num_warps = 1
        MAX_GRID_SIZE = TOTAL_CORE_NUM // num_warps

        BLOCK_SIZE = 1024
        total_blocks = (n_elements + BLOCK_SIZE - 1) // BLOCK_SIZE

        if reduction == "none":
            out = torch.empty_like(x1_c)
            if n_elements == 0:
                return out.view(x1_b.shape)
            grid = lambda meta: (min(total_blocks, MAX_GRID_SIZE),)
            _margin_ranking_loss_elementwise_kernel[grid](
                x1_c,
                x2_c,
                tgt_c,
                out,
                n_elements,
                margin,
                triton_dtype,
                BLOCK_SIZE=BLOCK_SIZE,
                total_blocks=total_blocks,
            )
            return out.view(x1_b.shape)
        else:
            if n_elements == 0:
                if reduction == "sum":
                    return torch.zeros((), device=x1_c.device, dtype=common_dtype)
                else:
                    return torch.full(
                        (), float("nan"), device=x1_c.device, dtype=common_dtype
                    )
            # Zero-initialize for atomic_add reduction
            tmp_sum = torch.zeros((), device=x1_c.device, dtype=torch.float32)
            grid = lambda meta: (min(total_blocks, MAX_GRID_SIZE),)
            _margin_ranking_loss_sum_kernel[grid](
                x1_c,
                x2_c,
                tgt_c,
                tmp_sum,
                n_elements,
                float(margin),
                triton_dtype,
                BLOCK_SIZE=BLOCK_SIZE,
                total_blocks=total_blocks,
            )
            if reduction == "sum":
                return tmp_sum.to(dtype=common_dtype)
            else:
                return (tmp_sum / float(n_elements)).to(dtype=common_dtype)

    @staticmethod
    def backward(ctx, grad_output):
        logger.debug("GEMS_CAMBRICON MARGIN_RANKING_LOSS_BACKWARD")

        x1, x2, y = ctx.saved_tensors
        margin = ctx.margin
        reduction = ctx.reduction
        n_elements = ctx.n_elements
        common_dtype = ctx.common_dtype
        triton_dtype = ctx.triton_dtype

        if n_elements == 0:
            grad_x1 = torch.zeros_like(x1, dtype=common_dtype)
            grad_x2 = torch.zeros_like(x2, dtype=common_dtype)
            grad_target = torch.zeros_like(y, dtype=common_dtype)
            return (
                grad_x1.view(ctx.original_shape),
                grad_x2.view(ctx.original_shape),
                grad_target.view(ctx.original_shape),
                None,
                None,
            )

        if reduction == "mean":
            grad_output = grad_output.expand(n_elements) / n_elements
        elif reduction == "sum":
            grad_output = grad_output.expand(n_elements)
        else:
            grad_output = grad_output.contiguous().view(-1)

        grad_output = grad_output.contiguous().to(torch.float32)

        grad_x1 = torch.empty_like(x1, dtype=torch.float32)
        grad_x2 = torch.empty_like(x2, dtype=torch.float32)

        # Get hardware core count for grid optimization
        _devprob = driver.BangUtils().get_device_properties(torch.mlu.current_device())
        TOTAL_CORE_NUM = _devprob.get("cluster_num") * _devprob.get(
            "core_num_per_cluster"
        )
        num_warps = 1
        MAX_GRID_SIZE = TOTAL_CORE_NUM // num_warps

        BLOCK_SIZE = 1024
        total_blocks = (n_elements + BLOCK_SIZE - 1) // BLOCK_SIZE

        grid = lambda meta: (min(total_blocks, MAX_GRID_SIZE),)
        _margin_ranking_loss_backward_kernel[grid](
            grad_output,
            x1,
            x2,
            y,
            grad_x1,
            grad_x2,
            float(margin),
            n_elements,
            triton_dtype,
            BLOCK_SIZE=BLOCK_SIZE,
            total_blocks=total_blocks,
        )

        original_shape = ctx.original_shape
        grad_x1 = grad_x1.to(common_dtype).view(original_shape)
        grad_x2 = grad_x2.to(common_dtype).view(original_shape)
        grad_target = torch.zeros_like(y, dtype=common_dtype).view(original_shape)
        return grad_x1, grad_x2, grad_target, None, None


def margin_ranking_loss(x1, x2, target, margin=0.0, reduction="mean"):
    return MarginRankingLossOp.apply(x1, x2, target, margin, reduction)
