# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2026, Yuanzhu Li
# Copyright 2026, BAAI (Beijing Academy of Artificial Intelligence)
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, libtuner

from ..utils import TOTAL_CORE_NUM

logger = logging.getLogger(__name__)


@libtuner(
    configs=[
        triton.Config(kwargs={"BLOCK_SIZE": 4096}, num_stages=1, num_warps=1),
        triton.Config(kwargs={"BLOCK_SIZE": 16384}, num_stages=1, num_warps=1),
        triton.Config(kwargs={"BLOCK_SIZE": 65536}, num_stages=1, num_warps=1),
        triton.Config(kwargs={"BLOCK_SIZE": 131072}, num_stages=1, num_warps=1),
    ],
    key=["n_elements"],
    restore_value=["out_ptr"],
)
@libentry()
@triton.jit
def negative_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    num_jobs = tl.num_programs(axis=0)
    block_start = pid * BLOCK_SIZE
    step = num_jobs * BLOCK_SIZE
    block_start = block_start.to(tl.int64)
    for off in range(block_start, n_elements, step):
        offsets = off + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        x = tl.load(x_ptr + offsets, mask=mask)
        tl.store(out_ptr + offsets, -x, mask=mask)


def _launch_negative(x: torch.Tensor, out: torch.Tensor):
    assert x.dtype == out.dtype, "Input and output must have the same dtype"
    assert (
        x.numel() == out.numel()
    ), "Input and output must have the same number of elements"
    assert x.is_contiguous(), "Input tensor must be contiguous"
    assert out.is_contiguous(), "Output tensor must be contiguous"

    n_elements = x.numel()
    if n_elements == 0:
        return out

    grid = lambda meta: (
        min(triton.cdiv(n_elements, meta["BLOCK_SIZE"]), TOTAL_CORE_NUM),
    )
    with torch_device_fn.device(x.device):
        negative_kernel[grid](x, out, n_elements)
    return out


def negative(x: torch.Tensor):
    logger.debug("GEMS_CAMBRICON NEGATIVE")
    x = x.contiguous()
    out = torch.empty_like(x)
    _launch_negative(x, out)
    return out


def negative_out(x: torch.Tensor, out: torch.Tensor):
    logger.debug("GEMS_CAMBRICON NEGATIVE_OUT")
    x = x.contiguous()
    out_contig = (
        out
        if out.is_contiguous()
        else torch.empty_like(out, memory_format=torch.contiguous_format)
    )
    _launch_negative(x, out_contig)
    if out_contig is not out:
        out.copy_(out_contig)
    return out
