# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from triton.language.extra.mlu.libdevice import philox as _philox

from flag_gems.runtime import device, torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils.random_utils import philox_backend_seed_offset

from ..utils import TOTAL_CORE_NUM

logger = logging.getLogger(__name__)
device_ = device

UNROLL = 4


@libentry()
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N"])
def randint_kernel(
    out_ptr,
    N,
    high,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
):
    UNROLL: tl.constexpr = 4
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)

    pid = tl.program_id(0)
    num_jobs = tl.num_programs(0)
    i4_start = pid * BLOCK
    block_start = pid * UNROLL * BLOCK
    step = num_jobs * BLOCK * UNROLL

    for block_offset in range(block_start, N, step):
        sl = (philox_seed & 0xFFFFFFFF).to(tl.uint32)
        sh = ((philox_seed >> 32) & 0xFFFFFFFF).to(tl.uint32)
        c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
        r = _philox(BLOCK, sl, sh, c0 + i4_start, c1, 0, 0, 10)
        high_val = high.to(tl.uint64)
        r_mod = (r % high_val).to(out_ptr.dtype.element_ty)

        off = block_offset + tl.arange(0, UNROLL * BLOCK)
        r_mod = tl.reshape(r_mod, [UNROLL * BLOCK], can_reorder=True)
        tl.store(out_ptr + off, r_mod, mask=off < N)
        i4_start += num_jobs * BLOCK


def randint(
    high,
    size,
    *,
    generator=None,
    out=None,
    dtype=torch.int64,
    layout=None,
    device=None,
    requires_grad=False,
    pin_memory=None,
):
    logger.debug("GEMS_CAMBRICON RANDINT")
    if dtype is None:
        dtype = torch.int64

    if device is None:
        device = torch.device(device_.name)

    if pin_memory is None:
        pin_memory = False

    if layout is None:
        layout = torch.strided

    if high <= 0:
        raise RuntimeError(
            f"random_ expects 'from' to be less than 'to', but got from=0 >= to={high}"
        )

    N = 1
    for s in size:
        N *= s

    BLOCK_SIZE = 128  # matches philox 4-wide output for efficient random generation
    grid = lambda meta: (min(triton.cdiv(N, meta["BLOCK"] * UNROLL), TOTAL_CORE_NUM),)
    increment = triton.cdiv(N, UNROLL)

    result = torch.empty(size, device=device, dtype=dtype, pin_memory=pin_memory)
    if N == 0:
        if out is not None:
            out.copy_(result)
            return out
        return result

    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )

    with torch_device_fn.device(device):
        randint_kernel[grid](
            result,
            N,
            high,
            philox_seed,
            philox_offset,
            BLOCK_SIZE,
            num_warps=1,
        )

    if out is not None:
        out.copy_(result)
        return out
    return result
