# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from ..utils import MAX_GRID_SIZE_X

logger = logging.getLogger(__name__)


@triton.jit
def relu6_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr, M: tl.constexpr):
    grid_0 = tl.num_programs(0)
    pid = tl.program_id(0)
    while pid < M:
        block_start = pid * BLOCK_SIZE
        offsets = block_start + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements

        x = tl.load(x_ptr + offsets, mask=mask)
        y = tl.maximum(x, 0)
        y = tl.minimum(y, 6)
        tl.store(out_ptr + offsets, y, mask=mask)
        pid += grid_0


def relu6(*args, **kwargs):
    logger.debug("GEMS_CAMBRICON RELU6")
    x = (
        args[0]
        if len(args) > 0
        else kwargs.get("input", kwargs.get("self", kwargs.get("x")))
    )
    if x is None:
        raise TypeError(
            "relu6 expects a tensor as the first positional argument or keyword 'input'/'self'/'x'."
        )

    x_contig = x.contiguous()

    out = torch.empty_like(x_contig)
    n_elements = out.numel()
    BLOCK_SIZE = 1024
    M = triton.cdiv(n_elements, BLOCK_SIZE)
    grid = min(M, MAX_GRID_SIZE_X // 4)

    relu6_kernel[(grid,)](x_contig, out, n_elements, BLOCK_SIZE=BLOCK_SIZE, M=M)
    return out
