# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

from flag_gems.utils import broadcastable_to

from .addmm import _launch_addmm

logger = logging.getLogger(__name__)


def addmm_(bias, mat1, mat2, *, beta=1, alpha=1):
    """In-place addmm: writes result directly to bias tensor.

    Zero-copy optimisation: eliminates the intermediate allocation and copy
    present in the generic addmm_ path (addmm() + copy_()). When bias is
    already a contiguous (M, N) tensor, it serves directly as the output.

    Reuses the tuned addmm kernel from .addmm rather than duplicating it.
    """
    logger.debug("GEMS_ILUVATAR ADDMM_")
    assert mat1.shape[1] == mat2.shape[0], "Incompatible dimensions"
    assert broadcastable_to(
        bias.shape, (mat1.shape[0], mat2.shape[1])
    ), "Incompatible input shape"
    M, K = mat1.shape
    _, N = mat2.shape

    if mat1.stride(0) > 1 and mat1.stride(1) > 1:
        mat1 = mat1.contiguous()
    if mat2.stride(0) > 1 and mat2.stride(1) > 1:
        mat2 = mat2.contiguous()

    # Fast path: bias is already a contiguous (M, N) matrix
    if bias.shape == (M, N) and bias.is_contiguous():
        return _launch_addmm(mat1, mat2, bias, bias, M, N, K, alpha, beta)

    # Fallback: compute into contiguous buffer, then copy back
    bias_contig = bias.broadcast_to((M, N)).contiguous()
    _launch_addmm(mat1, mat2, bias_contig, bias_contig, M, N, K, alpha, beta)
    bias.copy_(bias_contig)
    return bias
