# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Iluvatar-specific median overrides.

Fixes two issues with the generic median implementation on the Iluvatar
backend's Triton version (3.1.x):

1. ``_f16_order_key``: the right-shift ``signed >> 15`` promotes int16
   to int32.  The subsequent ``sign.to(tl.uint16, bitcast=True)`` then
   fails because a 32-bit to 16-bit bitcast is invalid.  Fixed by
   masking and using a regular cast instead of a bitcast.

2. ``tl.sort`` does not support sub-32-bit integer types (int8, uint8,
   int16, bool).  The ``median_small_flat_kernel`` and
   ``median_small_dim_kernel`` are replaced with versions that accept a
   ``SORT_UPCAST`` constexpr to cast data to int32 before sorting and
   back afterward.
"""

import logging
import math
import sys

import torch
import triton
import triton.language as tl

from flag_gems.ops.topk import _get_iinfo_val
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

_SUB32_INT_DTYPES = frozenset({torch.int8, torch.uint8, torch.int16, torch.bool})

# -------------------------------------------------------------------
# Fixed _f16_order_key
# -------------------------------------------------------------------


@triton.jit
def _f16_order_key(x):
    bits = x.to(tl.uint16, bitcast=True)
    signed = x.to(tl.int16, bitcast=True)
    sign = signed >> 15
    sign_mask = tl.full((), 0x8000, dtype=tl.uint16)
    # sign may be promoted to int32; use mask+cast instead of bitcast
    mask = sign_mask | (sign & 0xFFFF).to(tl.uint16)
    return bits ^ mask


# -------------------------------------------------------------------
# Fixed median_small_flat_kernel with SORT_UPCAST support
# -------------------------------------------------------------------


@libentry()
@triton.jit
def median_small_flat_kernel(
    inp,
    value,
    WIDTH: tl.constexpr,
    BLOCK: tl.constexpr,
    SORT_UPCAST: tl.constexpr = False,
):
    offsets = tl.arange(0, BLOCK)
    valid = offsets < WIDTH

    if inp.dtype.element_ty.is_floating():
        high = float("inf")
    elif inp.dtype.element_ty is tl.int1:
        high = True
    else:
        high = _get_iinfo_val(inp.dtype.element_ty, return_max=True)

    data = tl.load(inp + offsets, mask=valid, other=high)
    sortable = data

    if inp.dtype.element_ty.is_floating():
        nan_mask = valid & (data != data)
        sortable = tl.where(nan_mask, high, data)

    if SORT_UPCAST:
        sortable = sortable.to(tl.int32)
    ordered = tl.sort(sortable, descending=False)
    if SORT_UPCAST:
        ordered = ordered.to(inp.dtype.element_ty)
    rank = (WIDTH - 1) // 2
    median_value = tl.sum(
        tl.where(offsets == rank, ordered, tl.zeros_like(ordered)),
        axis=0,
    )

    if inp.dtype.element_ty.is_floating():
        nan_i32 = nan_mask.to(tl.int32)
        has_nan = tl.max(nan_i32, axis=0) != 0
        first_nan = tl.argmax(nan_i32, axis=0)
        nan_value = tl.load(inp + first_nan, mask=has_nan, other=0.0)
        median_value = tl.where(has_nan, nan_value, median_value)

    tl.store(value, median_value)


# -------------------------------------------------------------------
# Fixed median_small_dim_kernel with SORT_UPCAST support
# -------------------------------------------------------------------


@libentry()
@triton.jit
def median_small_dim_kernel(
    inp,
    values,
    indices,
    total_outputs,
    reduction_size,
    inner_size,
    BLOCK_N: tl.constexpr,
    BLOCK_OUT: tl.constexpr,
    SORT_UPCAST: tl.constexpr = False,
):
    out_offsets = tl.program_id(0) * BLOCK_OUT + tl.arange(0, BLOCK_OUT)
    out_mask = out_offsets < total_outputs
    inner_offsets = out_offsets % inner_size
    outer_offsets = out_offsets // inner_size

    reduction_offsets = tl.arange(0, BLOCK_N)
    sample_mask = (reduction_offsets[None, :] < reduction_size) & out_mask[:, None]
    sample_ptrs = (
        inp
        + outer_offsets[:, None] * reduction_size * inner_size
        + reduction_offsets[None, :] * inner_size
        + inner_offsets[:, None]
    )

    if inp.dtype.element_ty.is_floating():
        high = float("inf")
    else:
        high = _get_iinfo_val(inp.dtype.element_ty, return_max=True)

    samples = tl.load(sample_ptrs, mask=sample_mask, other=high)
    sortable = samples

    if inp.dtype.element_ty.is_floating():
        nan_mask = sample_mask & (samples != samples)
        sortable = tl.where(nan_mask, high, samples)

    if SORT_UPCAST:
        sortable = sortable.to(tl.int32)
    ordered = tl.sort(sortable, dim=1, descending=False)
    if SORT_UPCAST:
        ordered = ordered.to(inp.dtype.element_ty)
    rank = (reduction_size - 1) // 2
    rank_mask = reduction_offsets[None, :] == rank
    median_values = tl.sum(tl.where(rank_mask, ordered, tl.zeros_like(ordered)), axis=1)

    first_match = tl.argmax(
        (sample_mask & (samples == median_values[:, None])).to(tl.int32),
        axis=1,
    )

    if inp.dtype.element_ty.is_floating():
        nan_i32 = nan_mask.to(tl.int32)
        has_nan = tl.max(nan_i32, axis=1) != 0
        first_nan = tl.argmax(nan_i32, axis=1)
        nan_values = tl.load(
            inp
            + outer_offsets * reduction_size * inner_size
            + first_nan * inner_size
            + inner_offsets,
            mask=out_mask,
            other=0.0,
        )
        median_values = tl.where(has_nan, nan_values, median_values)
        first_match = tl.where(has_nan, first_nan, first_match)

    tl.store(values + out_offsets, median_values, mask=out_mask)
    tl.store(
        indices + out_offsets,
        first_match.to(tl.int64),
        mask=out_mask,
    )


# -------------------------------------------------------------------
# Fixed launcher: _median_small_flat
# -------------------------------------------------------------------


def _median_small_flat(inp):
    value = torch.empty((), dtype=inp.dtype, device=inp.device)
    block = triton.next_power_of_2(inp.numel())
    sort_upcast = inp.dtype in _SUB32_INT_DTYPES
    with torch_device_fn.device(inp.device):
        median_small_flat_kernel[(1,)](
            inp.reshape(-1),
            value,
            WIDTH=inp.numel(),
            BLOCK=block,
            SORT_UPCAST=sort_upcast,
            num_warps=min(8, max(4, block // 32)),
        )
    return value


# -------------------------------------------------------------------
# Fixed launcher: _median_direct_dim
# -------------------------------------------------------------------


def _median_direct_dim(inp, dim, output_shape):
    reduction_size = inp.shape[dim]
    inner_size = math.prod(inp.shape[dim + 1 :])
    total_outputs = math.prod(output_shape)
    values = torch.empty(output_shape, dtype=inp.dtype, device=inp.device)
    indices = torch.empty(output_shape, dtype=torch.int64, device=inp.device)
    block_n = triton.next_power_of_2(reduction_size)
    block_out = 2 if block_n >= 128 else 16
    if block_n >= 128:
        num_warps = 8 if inp.dtype in (torch.int32, torch.int64) else 4
    else:
        num_warps = 1
    sort_upcast = inp.dtype in _SUB32_INT_DTYPES
    with torch_device_fn.device(inp.device):
        median_small_dim_kernel[(triton.cdiv(total_outputs, block_out),)](
            inp,
            values.reshape(-1),
            indices.reshape(-1),
            total_outputs,
            reduction_size,
            inner_size,
            BLOCK_N=block_n,
            BLOCK_OUT=block_out,
            SORT_UPCAST=sort_upcast,
            num_warps=num_warps,
        )
    return values, indices


# -------------------------------------------------------------------
# Apply patches to the generic median module
# -------------------------------------------------------------------

_median_mod = sys.modules.get("flag_gems.ops.median")
if _median_mod is None:
    import flag_gems.ops.median  # noqa: F401

    _median_mod = sys.modules["flag_gems.ops.median"]

# Patch module-level globals so all JIT kernels in the module
# (which share the same globals dict) pick up the fixed version.
_median_mod._f16_order_key = _f16_order_key

# Replace the sort-based kernels and their launchers
_median_mod.median_small_flat_kernel = median_small_flat_kernel
_median_mod.median_small_dim_kernel = median_small_dim_kernel
_median_mod._median_small_flat = _median_small_flat
_median_mod._median_direct_dim = _median_direct_dim

# Patch fn.__globals__ dict used by all JIT functions in the module.
# This ensures kernels calling _f16_order_key via shared globals pick
# up the fixed version at Triton compile time.
_jit_globals = _median_mod.median_f16_key_select_kernel.jit_function.fn.__globals__
_jit_globals["_f16_order_key"] = _f16_order_key
_jit_globals["median_small_flat_kernel"] = median_small_flat_kernel
_jit_globals["median_small_dim_kernel"] = median_small_dim_kernel
_jit_globals["_median_small_flat"] = _median_small_flat
_jit_globals["_median_direct_dim"] = _median_direct_dim

# -------------------------------------------------------------------
# Export the public API functions (they now use patched internals)
# -------------------------------------------------------------------

median = _median_mod.median
median_out = _median_mod.median_out
median_dim = _median_mod.median_dim
median_dim_values = _median_mod.median_dim_values
