# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)

# Heuristic threshold: when per-slice reduction length N <= this value,
# a single tile covers the whole slice and the norm + rescale fuse into
# one load/store pass (INPUT_FITS=True).
_REDUCTION_FIT_CAP = 1024
# Target register tile size used to derive BLOCK_M from BLOCK_N.
_TILE_TARGET = 4096


@libentry()
@triton.jit(do_not_specialize=["maxnorm"])
def renorm_2d_kernel(
    X,
    M,
    N,
    p_val,
    maxnorm,
    sM,
    sN,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    INPUT_FITS: tl.constexpr,
):
    """In-place renorm over a 2-D (M, N) strided view of the tensor.

    ``M`` is the size of the non-reduced axis (``dim``) and ``N`` is the
    reduction length.  One program processes ``BLOCK_M`` consecutive slices;
    each slice p-norm is computed over its ``N`` elements and, where it
    exceeds ``maxnorm``, the slice is rescaled in place.

    ``sM``/``sN`` are the strides (in elements) so the kernel runs directly
    on a permuted view without materializing a contiguous copy — this removes
    the full-tensor copies the generic path performs.
    """
    pid = tl.program_id(0).to(tl.int64)
    m_idx = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    m_mask = m_idx < M
    m_idx = m_idx.to(tl.int64)

    if INPUT_FITS:
        # Single pass: whole reduction fits in one tile — load once,
        # compute norm, rescale and store.  No reload needed.
        n_idx = tl.arange(0, BLOCK_N)
        n_mask = n_idx < N
        offs = n_idx[:, None].to(tl.int64) * sN + m_idx[None, :] * sM
        mask = n_mask[:, None] & m_mask[None, :]
        x = tl.load(X + offs, mask=mask, other=0.0).to(tl.float32)
        if p_val == 2.0:
            norm = tl.sqrt(tl.sum(x * x, axis=0))
        elif p_val == 1.0:
            norm = tl.sum(tl.abs(x), axis=0)
        else:
            a = tl.abs(x)
            norm = tl_extra_shim.pow(
                tl.sum(tl_extra_shim.pow(a, p_val), axis=0), 1.0 / p_val
            )
        scale = tl.where(norm > maxnorm, maxnorm / norm, 1.0)
        scale = scale.to(X.dtype.element_ty).to(tl.float32)
        y = (x * scale[None, :]).to(X.dtype.element_ty)
        tl.store(X + offs, y, mask=mask)
    else:
        # Two passes within one launch: accumulate norm, then reload and
        # rescale.  ``scale`` stays in registers across both passes.
        acc = tl.zeros([BLOCK_M], dtype=tl.float32)
        for n0 in range(0, N, BLOCK_N):
            n_idx = n0 + tl.arange(0, BLOCK_N)
            n_mask = n_idx < N
            offs = n_idx[:, None].to(tl.int64) * sN + m_idx[None, :] * sM
            mask = n_mask[:, None] & m_mask[None, :]
            x = tl.load(X + offs, mask=mask, other=0.0).to(tl.float32)
            if p_val == 2.0:
                acc += tl.sum(x * x, axis=0)
            elif p_val == 1.0:
                acc += tl.sum(tl.abs(x), axis=0)
            else:
                a = tl.abs(x)
                acc += tl.sum(tl_extra_shim.pow(a, p_val), axis=0)
        if p_val == 2.0:
            norm = tl.sqrt(acc)
        else:
            norm = tl_extra_shim.pow(acc, 1.0 / p_val)
        scale = tl.where(norm > maxnorm, maxnorm / norm, 1.0)
        scale = scale.to(X.dtype.element_ty).to(tl.float32)
        for n0 in range(0, N, BLOCK_N):
            n_idx = n0 + tl.arange(0, BLOCK_N)
            n_mask = n_idx < N
            offs = n_idx[:, None].to(tl.int64) * sN + m_idx[None, :] * sM
            mask = n_mask[:, None] & m_mask[None, :]
            x = tl.load(X + offs, mask=mask, other=0.0)
            y = (x.to(tl.float32) * scale[None, :]).to(X.dtype.element_ty)
            tl.store(X + offs, y, mask=mask)


def _block_heuristics(N):
    """Pick (BLOCK_M, BLOCK_N, INPUT_FITS, num_warps) for a reduction
    length N.  Iluvatar-tuned for num_stages=1."""
    if N <= _REDUCTION_FIT_CAP:
        input_fits = True
        block_n = min(triton.next_power_of_2(N), _REDUCTION_FIT_CAP)
    else:
        input_fits = False
        block_n = 256
    block_m = max(4, min(128, _TILE_TARGET // block_n))
    tile = block_n * block_m
    if tile <= 1024:
        num_warps = 1
    elif tile <= 2048:
        num_warps = 2
    elif tile <= 8192:
        num_warps = 4
    else:
        num_warps = 8
    return block_m, block_n, input_fits, num_warps


def _launch_2d(buf, M, N, sM, sN, p, maxnorm):
    block_m, block_n, input_fits, num_warps = _block_heuristics(N)
    grid = (triton.cdiv(M, block_m),)
    with torch_device_fn.device(buf.device):
        renorm_2d_kernel[grid](
            buf,
            M,
            N,
            p,
            maxnorm,
            sM,
            sN,
            BLOCK_M=block_m,
            BLOCK_N=block_n,
            INPUT_FITS=input_fits,
            num_warps=num_warps,
            num_stages=1,
        )


def renorm_(x, p, dim, maxnorm):
    """In-place renorm — Iluvatar optimized 2-D tiled kernel.

    Compared to the generic one-block-per-row implementation this version:
      - tiles BLOCK_M rows per program to amortize launch overhead
      - uses a 2-D (BLOCK_M × BLOCK_N) decomposition for balanced occupancy
      - operates on strided views of 2-D tensors to avoid permute/copy
      - short-circuits p=2.0 → x*x and p=1.0 → abs, skipping tl_extra_shim.pow
    """
    logger.debug("GEMS_ILUVATAR RENORM_")
    p = float(p)
    maxnorm = float(maxnorm)
    dim = dim % x.ndim

    if x.ndim == 2:
        # Fast path: operate in place on the original strided view —
        # no permute-contiguous copy, no copy-back, one launch.
        other = 1 - dim
        M = x.shape[dim]
        N = x.shape[other]
        sM = x.stride(dim)
        sN = x.stride(other)
        _launch_2d(x, M, N, sM, sN, p, maxnorm)
        return x

    # General path for rank > 2: bring ``dim`` to the front, materialize
    # a contiguous (M, N) buffer, rescale in place, then copy back.
    perm = [dim] + [i for i in range(x.ndim) if i != dim]
    inv_perm = [perm.index(i) for i in range(x.ndim)]
    x_perm = x.permute(perm).contiguous()
    M = x_perm.shape[0]
    N = x_perm[0].numel()
    _launch_2d(x_perm, M, N, N, 1, p, maxnorm)
    x.copy_(x_perm.permute(inv_perm))
    return x
