# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.neg import neg_func
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as ext
from flag_gems.utils.libentry import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 4096}, num_warps=16, num_stages=1),
        triton.Config({"BLOCK_SIZE": 4096}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=16, num_stages=1),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=4, num_stages=1),
        triton.Config({"BLOCK_SIZE": 8192}, num_warps=16, num_stages=1),
        triton.Config({"BLOCK_SIZE": 8192}, num_warps=8, num_stages=1),
        triton.Config({"BLOCK_SIZE": 512}, num_warps=4, num_stages=1),
        triton.Config({"BLOCK_SIZE": 16384}, num_warps=16, num_stages=1),
        triton.Config({"BLOCK_SIZE": 32768}, num_warps=16, num_stages=1),
    ],
    key=["n_elements"],
)
@triton.jit
def _resolve_neg_kernel_stride2(
    inp_ptr,
    out_ptr,
    n_elements,
    inp_offset,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimised fast path for tensors with stride-2 innermost dimension.

    When every input stride is exactly twice the corresponding logical
    (contiguous) stride — as with ``complex.conj().imag`` — the physical
    address is simply ``storage_offset + 2 * flat_index``.
    """
    pid = ext.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    inp_offsets = inp_offset + offsets * 2
    data = tl.load(inp_ptr + inp_offsets, mask=mask)
    out_data = -data
    tl.store(out_ptr + offsets, out_data, mask=mask)


def _strides_are_2x_logical(shape, stride):
    """Return True if every stride is exactly 2× the logical stride."""
    rank = len(shape)
    if rank == 1:
        return stride[0] == 2
    if stride[-1] != 2:
        return False
    for i in range(rank - 1):
        if stride[i] // stride[i + 1] != shape[i + 1]:
            return False
    return True


def resolve_neg(A: torch.Tensor):
    """Materialise the conceptual negation flag on a tensor.

    For tensors from ``complex.conj().imag`` the input strides are
    exactly twice the logical strides, so physical addressing reduces
    to ``storage_offset + 2 * flat_index`` — a simple multiply, load,
    negate, and store without any division or modulo.
    """
    logger.debug("GEMS_ILUVATAR RESOLVE_NEG")
    if not A.is_neg():
        return A

    strides = A.stride()
    storage_offset = A.storage_offset()

    # Fast path: strides are exactly 2× logical (universal for .conj().imag)
    if _strides_are_2x_logical(A.shape, strides):
        n_elements = A.numel()
        out = torch.empty(A.shape, dtype=A.dtype, device=A.device)
        with torch_device_fn.device(A.device.index):
            grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
            _resolve_neg_kernel_stride2[grid](
                A,
                out,
                n_elements,
                storage_offset,
            )
        return out

    # General fallback for non-standard stride patterns
    return neg_func(A)
