# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)

# Element-count thresholds for kernel tier dispatch:
#   <= TINY:   bare single-block @triton.jit, no libentry, in-kernel n-clamp
#   <= MEDIUM: bare multi-block  @triton.jit, no libentry, in-kernel n-clamp
#   >  MEDIUM: libentry-decorated kernel with Iluvatar-tuned heuristics
_TINY = 4096
_MEDIUM = 1 << 20  # 1 048 576


# ---- Tier 1: tiny single-block kernels (<= 4K elements) ----
# Single-block, num_warps=1, no libentry or host sync overhead.


@triton.jit
def _tiny_tensor_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements: tl.constexpr,
):
    offsets = tl.arange(0, n_elements)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n = tl.load(n_ptr + offsets, mask=mask, other=0.0)
    n_i = n.to(tl.int32)
    n_i = tl.minimum(tl.maximum(n_i, 0), 9)

    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = 1.0 + 0.0 * xf
    h_k = two_x
    result = tl.where(n_i == 0, h_km1, h_k)

    for k in tl.static_range(1, 9):
        h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
        h_km1 = h_k
        h_k = h_kp1
        result = tl.where(n_i == (k + 1), h_k, result)

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


@triton.jit
def _tiny_scalar_kernel(
    x_ptr,
    out_ptr,
    n_elements: tl.constexpr,
    N: tl.constexpr,
):
    offsets = tl.arange(0, n_elements)
    mask = offsets < n_elements
    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = 1.0 + 0.0 * xf
    h_k = two_x

    if N == 0:
        result = h_km1
    elif N == 1:
        result = h_k
    else:
        for k in tl.static_range(1, N):
            h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
            h_km1 = h_k
            h_k = h_kp1
        result = h_k

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


# ---- Tier 2: medium bare multi-block kernels (4K – 1M elements) ----
# No libentry to avoid cache-lookup overhead; in-kernel n-clamp.


@triton.jit
def _med_tensor_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n_val = tl.load(n_ptr + offsets, mask=mask, other=0.0)
    n_i = n_val.to(tl.int32)
    n_i = tl.minimum(tl.maximum(n_i, 0), 9)

    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)
    h_k = two_x
    result = tl.where(n_i == 0, h_km1, h_k)

    for k in tl.static_range(1, 9):
        h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
        h_km1 = h_k
        h_k = h_kp1
        result = tl.where(n_i == (k + 1), h_k, result)

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


@triton.jit
def _med_scalar_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    N: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)
    h_k = two_x

    if N == 0:
        result = h_km1
    elif N == 1:
        result = h_k
    else:
        for k in tl.static_range(1, N):
            h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
            h_km1 = h_k
            h_k = h_kp1
        result = h_k

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


# ---- Tier 3: large libentry-decorated kernels (> 1M elements) ----
# libentry autotuning pays off at this scale; in-kernel n-clamp.


@libentry()
@triton.jit
def hermite_polynomial_h_tensor_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    n_val = tl.load(n_ptr + offsets, mask=mask, other=0.0)
    n_int = n_val.to(tl.int32)
    n_int = tl.minimum(tl.maximum(n_int, 0), 9)

    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)
    h_k = two_x
    result = tl.where(n_int == 0, h_km1, h_k)

    for k in tl.static_range(1, 9):
        h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
        h_km1 = h_k
        h_k = h_kp1
        result = tl.where(n_int == (k + 1), h_k, result)

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


@libentry()
@triton.jit
def hermite_polynomial_h_scalar_kernel(
    x_ptr,
    out_ptr,
    n_elements,
    N: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    xf = x.to(tl.float32)
    two_x = 2.0 * xf

    h_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)
    h_k = two_x

    if N == 0:
        result = h_km1
    elif N == 1:
        result = h_k
    else:
        for k in tl.static_range(1, N):
            h_kp1 = tl.fma(two_x, h_k, (-2.0 * k) * h_km1)
            h_km1 = h_k
            h_k = h_kp1
        result = h_k

    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


# ---- Heuristics ----
# All tiers clamp n to [0,9] in-kernel, so no torch.aminmax host sync is
# needed at any size.


def _large_heuristics(n_elements):
    """Iluvatar-tuned block/warp config for the libentry tier."""
    if n_elements <= 2**20:
        return 512, 4
    else:
        return 1024, 8


def _medium_heuristics(n_elements):
    """Block/warp config for the bare-kernel tier."""
    if n_elements <= 65536:
        return 256, 2
    elif n_elements <= 262144:
        return 512, 2
    else:
        return 1024, 4


# ---- Public API ----


def _tensor_tensor_inputs(x, n):
    """Prepare contiguous same-shape inputs, fast path when shapes match."""
    if x.shape == n.shape:
        x_c = x if x.is_contiguous() else x.contiguous()
        n_c = n if n.is_contiguous() else n.contiguous()
    else:
        x_b, n_b = torch.broadcast_tensors(x, n)
        x_c = x_b.contiguous()
        n_c = n_b.contiguous()
    return x_c, n_c


def special_hermite_polynomial_h_tensor_tensor(x, n):
    logger.debug("GEMS_ILUVATAR SPECIAL_HERMITE_POLYNOMIAL_H")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(f"Unsupported dtype {x.dtype}")

    x_c, n_c = _tensor_tensor_inputs(x, n)
    n_elements = volume(x_c.shape)
    if n_elements == 0:
        return torch.empty_like(x_c)

    out = torch.empty_like(x_c)

    if n_elements <= _TINY:
        with torch_device_fn.device(x_c.device):
            _tiny_tensor_kernel[(1,)](
                x_c,
                n_c,
                out,
                n_elements=n_elements,
                num_warps=1,
            )
        return out

    if n_elements <= _MEDIUM:
        block, warps = _medium_heuristics(n_elements)
        grid = (triton.cdiv(n_elements, block),)
        with torch_device_fn.device(x_c.device):
            _med_tensor_kernel[grid](
                x_c,
                n_c,
                out,
                n_elements,
                BLOCK_SIZE=block,
                num_warps=warps,
                num_stages=1,
            )
        return out

    block, warps = _large_heuristics(n_elements)
    grid = (triton.cdiv(n_elements, block),)
    with torch_device_fn.device(x_c.device):
        hermite_polynomial_h_tensor_kernel[grid](
            x_c,
            n_c,
            out,
            n_elements,
            BLOCK_SIZE=block,
            num_warps=warps,
            num_stages=1,
        )
    return out


def special_hermite_polynomial_h(x, n):
    """Physicist's Hermite polynomial H_n(x).

    Iluvatar-optimized with a three-tier dispatch:
    - Tiny    (<= 4K): bare single-block kernel, num_warps=1.
    - Medium  (4K-1M): bare multi-block kernel, heuristic block/warp.
    - Large    (> 1M): libentry kernel with Iluvatar-tuned block/warp.

    All tiers use recurrence evaluation (~6x fewer FLOPs than the generic
    layer's closed-form-per-degree path) and in-kernel n-clamping to avoid
    the host-synchronising torch.aminmax call.
    """
    logger.debug("GEMS_ILUVATAR SPECIAL_HERMITE_POLYNOMIAL_H")
    if not isinstance(x, torch.Tensor):
        raise ValueError("First argument must be a tensor")
    if x.dtype not in (torch.float32, torch.float64):
        raise ValueError(f"Unsupported dtype {x.dtype}")

    if isinstance(n, torch.Tensor):
        return special_hermite_polynomial_h_tensor_tensor(x, n)
    elif isinstance(n, (int, float)):
        if int(n) < 0 or int(n) > 9:
            raise ValueError(
                f"special_hermite_polynomial_h only supports n in [0, 9], " f"got n={n}"
            )
        n_int = int(n)

        x_c = x.contiguous()
        n_elements = volume(x_c.shape)
        if n_elements == 0:
            return torch.empty_like(x_c)

        out = torch.empty_like(x_c)

        if n_elements <= _TINY:
            with torch_device_fn.device(x_c.device):
                _tiny_scalar_kernel[(1,)](
                    x_c,
                    out,
                    n_elements=n_elements,
                    N=n_int,
                    num_warps=1,
                )
            return out

        if n_elements <= _MEDIUM:
            block, warps = _medium_heuristics(n_elements)
            grid = (triton.cdiv(n_elements, block),)
            with torch_device_fn.device(x_c.device):
                _med_scalar_kernel[grid](
                    x_c,
                    out,
                    n_elements,
                    N=n_int,
                    BLOCK_SIZE=block,
                    num_warps=warps,
                    num_stages=1,
                )
            return out

        block, warps = _large_heuristics(n_elements)
        grid = (triton.cdiv(n_elements, block),)
        with torch_device_fn.device(x_c.device):
            hermite_polynomial_h_scalar_kernel[grid](
                x_c,
                out,
                n_elements,
                N=n_int,
                BLOCK_SIZE=block,
                num_warps=warps,
                num_stages=1,
            )
        return out
    else:
        raise ValueError("n must be a Tensor, int, or float")
