# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import math

import pytest
import torch

import flag_gems
from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import set_philox_state

from . import accuracy_utils as utils
from .conftest import TO_CPU


def make_qkv(batch, num_head, q_seq_len, kv_seq_len, head_size, dtype, device):
    dev = torch_device_fn.current_device()
    set_philox_state(1234567890, 0, dev)
    Q = torch.empty(
        batch, q_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    K = torch.empty(
        batch, kv_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    V = torch.empty(
        batch, kv_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    return Q, K, V


QM_NS = [
    (2, 4, 512, 512),
    (1, 2, 512, 1024),
    (1, 1, 64, 64),
    (4, 8, 128, 128),
]


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_attention_forward
@pytest.mark.parametrize("batch, num_head, q_seq_len, kv_seq_len", QM_NS)
@pytest.mark.parametrize("head_size", [64, 128])
@pytest.mark.parametrize("is_causal", [False, True])
@pytest.mark.parametrize("has_attn_bias", [False, True])
@pytest.mark.parametrize("dtype", [torch.float16, torch.bfloat16])
def test_cudnn_attention_forward(
    batch,
    num_head,
    q_seq_len,
    kv_seq_len,
    head_size,
    is_causal,
    has_attn_bias,
    dtype,
):
    if TO_CPU:
        pytest.skip(
            "_cudnn_attention_forward is CUDA-only, " "cannot run in quick-cpu mode"
        )
    if is_causal and has_attn_bias:
        pytest.skip("causal + attn_bias combination: skip")

    scale = float(1.0 / math.sqrt(head_size))

    Q, K, V = make_qkv(
        batch,
        num_head,
        q_seq_len,
        kv_seq_len,
        head_size,
        dtype,
        flag_gems.device,
    )

    attn_bias = None
    if has_attn_bias:
        attn_bias = (
            torch.randn(
                batch,
                num_head,
                q_seq_len,
                kv_seq_len,
                dtype=dtype,
                device=flag_gems.device,
            )
            * 0.1
        )

    Q_bhsd = Q.permute(0, 2, 1, 3).contiguous()
    K_bhsd = K.permute(0, 2, 1, 3).contiguous()
    V_bhsd = V.permute(0, 2, 1, 3).contiguous()

    ref_Q_bhsd = utils.to_reference(Q_bhsd)
    ref_K_bhsd = utils.to_reference(K_bhsd)
    ref_V_bhsd = utils.to_reference(V_bhsd)

    ref_out = torch.ops.aten._cudnn_attention_forward(
        ref_Q_bhsd,
        ref_K_bhsd,
        ref_V_bhsd,
        attn_bias,
        None,
        None,
        q_seq_len,
        kv_seq_len,
        True,
        0.0,
        is_causal,
        False,
        scale=scale,
    )
    ref_output = ref_out[0]
    ref_lse = ref_out[1]

    gems_out = flag_gems.ops.cudnn_attention_forward(
        Q_bhsd,
        K_bhsd,
        V_bhsd,
        attn_bias,
        None,
        None,
        q_seq_len,
        kv_seq_len,
        True,
        0.0,
        is_causal,
        False,
        scale=scale,
    )
    gems_output = gems_out[0]
    gems_lse = gems_out[1]

    out_bshd = gems_output.permute(0, 2, 1, 3).contiguous()
    ref_out_bshd = ref_output.permute(0, 2, 1, 3).contiguous()
    utils.gems_assert_close(out_bshd, ref_out_bshd, dtype, equal_nan=True, atol=1e-3)

    # Compare LSE: tolerance relaxed because GEMS uses a different softmax
    # implementation (online rescaling) than cuDNN.
    gems_lse_f = gems_lse.float()
    ref_lse_f = ref_lse.float()
    lse_diff = (gems_lse_f - ref_lse_f).abs().max().item()
    assert lse_diff < 0.1, f"LSE max diff {lse_diff:.6f} exceeds tolerance 0.1"
