# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

_tanh = tl_extra_shim.tanh


@triton.jit
def _lstm_cell_backward_kernel(
    grad_hy_ptr,
    grad_cy_ptr,
    cx_ptr,
    cy_ptr,
    workspace_ptr,
    grad_gates_ptr,
    grad_cx_ptr,
    batch,
    hidden,
    N,  # batch * hidden
    BLOCK: tl.constexpr,
):
    """Fused LSTM-cell backward.

    One program block owns ``BLOCK`` (batch, hidden) elements. For each
    element it loads the four gate activations from ``workspace`` — laid out
    as ``[i, f, g, o]`` blocks of ``hidden`` columns per row — computes the
    identical chain-rule gradients as the generic layer, and writes
    ``grad_gates`` (same ``[batch, 4*hidden]`` layout) plus ``grad_cx``.
    """
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N

    # Decompose the flat elementwise index into (row, column-in-hidden).
    b = offs // hidden
    h = offs % hidden

    # Row base into the [batch, 4*hidden] gate tensors; the four gate slabs
    # sit at column offsets 0, hidden, 2*hidden, 3*hidden within the row.
    row4 = b * (4 * hidden)
    i_off = row4 + h
    f_off = i_off + hidden
    g_off = f_off + hidden
    o_off = g_off + hidden

    # Per-element tensors are plain [batch, hidden]; their flat index is offs.
    grad_hy = tl.load(grad_hy_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    grad_cy = tl.load(grad_cy_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    cx = tl.load(cx_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    cy = tl.load(cy_ptr + offs, mask=mask, other=0.0).to(tl.float32)

    i_gate = tl.load(workspace_ptr + i_off, mask=mask, other=0.0).to(tl.float32)
    f_gate = tl.load(workspace_ptr + f_off, mask=mask, other=0.0).to(tl.float32)
    g_gate = tl.load(workspace_ptr + g_off, mask=mask, other=0.0).to(tl.float32)
    o_gate = tl.load(workspace_ptr + o_off, mask=mask, other=0.0).to(tl.float32)

    # Identical numerics to the generic layer.
    tanh_cy = _tanh(cy)
    d_cy = grad_hy * o_gate * (1.0 - tanh_cy * tanh_cy) + grad_cy

    grad_i = d_cy * g_gate * i_gate * (1.0 - i_gate)
    grad_f = d_cy * cx * f_gate * (1.0 - f_gate)
    grad_g = d_cy * i_gate * (1.0 - g_gate * g_gate)
    grad_o = grad_hy * tanh_cy * o_gate * (1.0 - o_gate)
    grad_cx = d_cy * f_gate

    out_dtype = grad_gates_ptr.dtype.element_ty
    tl.store(grad_gates_ptr + i_off, grad_i.to(out_dtype), mask=mask)
    tl.store(grad_gates_ptr + f_off, grad_f.to(out_dtype), mask=mask)
    tl.store(grad_gates_ptr + g_off, grad_g.to(out_dtype), mask=mask)
    tl.store(grad_gates_ptr + o_off, grad_o.to(out_dtype), mask=mask)
    tl.store(grad_cx_ptr + offs, grad_cx.to(grad_cx_ptr.dtype.element_ty), mask=mask)


@triton.jit
def _lstm_bias_kernel(
    grad_gates_ptr,
    grad_bias_ptr,
    batch,
    M,  # 4 * hidden
    BLOCK: tl.constexpr,
):
    """Column reduction: grad_biases[c] = sum_b grad_gates[b, c]."""
    pid = tl.program_id(0)
    cols = pid * BLOCK + tl.arange(0, BLOCK)
    mask = cols < M

    acc = tl.zeros([BLOCK], tl.float32)
    for b in range(batch):
        v = tl.load(grad_gates_ptr + b * M + cols, mask=mask, other=0.0).to(tl.float32)
        acc += v
    tl.store(grad_bias_ptr + cols, acc.to(grad_bias_ptr.dtype.element_ty), mask=mask)


def _thnn_fused_lstm_cell_backward_impl(
    grad_hy: torch.Tensor,
    grad_cy: torch.Tensor,
    cx: torch.Tensor,
    cy: torch.Tensor,
    workspace: torch.Tensor,
    has_bias: bool,
):
    """thead specialization of the fused LSTM-cell backward.

    The generic layer expresses the backward as a chain of ~15 individual
    PyTorch tensor ops (tanh, several muls/subs, a ``cat`` and a ``sum``).
    Under ``use_gems`` every one of those dispatches to its own gems Triton
    launch, and on PPU each launch carries a fixed ~100 us dispatch/codegen
    tax that swamps the tiny per-shape compute — hence the uniform 0.008x
    speedup regardless of shape. This implementation collapses the whole
    gate-gradient computation into a single fused elementwise kernel and does
    the bias reduction in one more small kernel, keeping the numerics
    identical while cutting the launch count from ~15 to 2.
    """
    logger.debug("GEMS_THEAD _THNN_FUSED_LSTM_CELL_BACKWARD_IMPL")

    batch_size, hidden_size = cx.shape

    grad_hy = grad_hy.contiguous()
    grad_cy = grad_cy.contiguous()
    cx = cx.contiguous()
    cy = cy.contiguous()
    workspace = workspace.contiguous()

    grad_input_gates = torch.empty(
        batch_size, 4 * hidden_size, dtype=workspace.dtype, device=workspace.device
    )
    grad_cx = torch.empty_like(cx)

    N = batch_size * hidden_size
    if N > 0:
        BLOCK = min(triton.next_power_of_2(N), 1024)
        grid = (triton.cdiv(N, BLOCK),)
        # Small shapes are pure launch overhead (num_warps=1 keeps the launch
        # cheap); once a single block owns a full 1024-wide tile, spreading it
        # across more warps recovers the compute-bound tail.
        num_warps = 4 if N >= 512 else 1
        with torch_device_fn.device(cx.device):
            _lstm_cell_backward_kernel[grid](
                grad_hy,
                grad_cy,
                cx,
                cy,
                workspace,
                grad_input_gates,
                grad_cx,
                batch_size,
                hidden_size,
                N,
                BLOCK=BLOCK,
                num_warps=num_warps,
            )

    if has_bias:
        M = 4 * hidden_size
        grad_biases = torch.empty(
            M, dtype=grad_input_gates.dtype, device=grad_input_gates.device
        )
        if M > 0:
            BLOCK_B = min(triton.next_power_of_2(M), 1024)
            grid_b = (triton.cdiv(M, BLOCK_B),)
            with torch_device_fn.device(cx.device):
                _lstm_bias_kernel[grid_b](
                    grad_input_gates,
                    grad_biases,
                    batch_size,
                    M,
                    BLOCK=BLOCK_B,
                    num_warps=1,
                )
    else:
        grad_biases = torch.zeros(0, dtype=cx.dtype, device=cx.device)

    return grad_input_gates, grad_cx, grad_biases
