# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


def _conv_out_size(in_size, kernel_size, stride, padding, dilation):
    return (in_size + 2 * padding - dilation * (kernel_size - 1) - 1) // stride + 1


@triton.jit
def _depthwise2d_kernel(
    input_ptr,
    weight_ptr,
    bias_ptr,
    output_ptr,
    N,
    OC,
    IH,
    IW,
    OH,
    OW,
    MULT,
    in_n_stride,
    in_c_stride,
    in_h_stride,
    in_w_stride,
    w_c_stride,
    w_h_stride,
    w_w_stride,
    out_n_stride,
    out_c_stride,
    out_h_stride,
    out_w_stride,
    stride_h,
    stride_w,
    pad_h,
    pad_w,
    dil_h,
    dil_w,
    HAS_BIAS: tl.constexpr,
    KH: tl.constexpr,
    KW: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Flat program over every output element (N * OC * OH * OW). Depthwise conv
    # (groups == in_channels) means output channel oc reads only input channel
    # ic = oc // MULT and weight row oc; no channel reduction / im2col matmul.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    total = N * OC * OH * OW
    mask = offs < total

    ow = offs % OW
    tmp = offs // OW
    oh = tmp % OH
    tmp = tmp // OH
    oc = tmp % OC
    n = tmp // OC
    ic = oc // MULT

    # Base pointers into the per-element input channel and output element.
    in_base = n * in_n_stride + ic * in_c_stride
    w_base = oc * w_c_stride
    acc = tl.zeros((BLOCK,), dtype=tl.float32)

    # KH / KW are constexpr so the tap loop is fully unrolled.
    for kh in tl.static_range(KH):
        ih = oh * stride_h - pad_h + kh * dil_h
        h_valid = (ih >= 0) & (ih < IH)
        for kw in tl.static_range(KW):
            iw = ow * stride_w - pad_w + kw * dil_w
            w_valid = (iw >= 0) & (iw < IW)
            load_mask = mask & h_valid & w_valid
            in_ptr = in_base + ih * in_h_stride + iw * in_w_stride
            x = tl.load(input_ptr + in_ptr, mask=load_mask, other=0.0).to(tl.float32)
            wv = tl.load(
                weight_ptr + w_base + kh * w_h_stride + kw * w_w_stride,
                mask=mask,
                other=0.0,
            ).to(tl.float32)
            acc += x * wv

    if HAS_BIAS:
        acc += tl.load(bias_ptr + oc, mask=mask, other=0.0).to(tl.float32)

    out_ptr = (
        n * out_n_stride + oc * out_c_stride + oh * out_h_stride + ow * out_w_stride
    )
    tl.store(output_ptr + out_ptr, acc.to(output_ptr.dtype.element_ty), mask=mask)


def _conv_depthwise2d(input, weight, kernel_size, bias, stride, padding, dilation):
    """thead depthwise 2-D convolution specialization.

    The generic layer (``flag_gems.ops.conv_depthwise2d``) routes into the
    tiled im2col ``conv2d`` kernel, which is wrapped in ``triton.autotune``
    over ~14 configs. On thead PPU that autotune loop never converges — the
    accuracy suite and the ``--level core`` benchmark both hang past 600s.
    On top of that, depthwise conv has ``weight_c == 1`` so the generic path
    pads input/weight channels up to K>=16 just to satisfy ``tl.dot``, wasting
    most of the matmul.

    Depthwise conv needs no channel reduction at all: output channel ``c``
    convolves input channel ``c`` with ``weight[c, 0, :, :]``. This kernel is a
    direct per-output-element gather with a fully unrolled ``KH*KW`` tap loop,
    driven by a single fixed config (no autotune) so it launches immediately.
    Numerics are identical to ``torch.nn.functional.conv2d`` with
    ``groups == channels`` (fp32 accumulation, cast back on store).
    """
    logger.debug("GEMS_THEAD DEPTHWISE2D")
    assert input.ndim == 4, f"Invalid input tensor must be 4D, received {input.shape}"
    assert (
        weight.shape[1] == 1
    ), f"depthwise weight in-channels must be 1, got {weight.shape[1]}"

    if isinstance(stride, (list, tuple)):
        stride_h, stride_w = stride[0], stride[1]
    else:
        stride_h = stride_w = stride
    if isinstance(padding, (list, tuple)):
        pad_h, pad_w = padding[0], padding[1]
    else:
        pad_h = pad_w = padding
    if isinstance(dilation, (list, tuple)):
        dil_h, dil_w = dilation[0], dilation[1]
    else:
        dil_h = dil_w = dilation

    N, C, IH, IW = input.shape
    out_c, _, KH, KW = weight.shape
    assert (
        out_c % C == 0
    ), f"depthwise out-channels {out_c} must be a multiple of in-channels {C}"
    mult = out_c // C

    OH = _conv_out_size(IH, KH, stride_h, pad_h, dil_h)
    OW = _conv_out_size(IW, KW, stride_w, pad_w, dil_w)

    output = torch.empty((N, out_c, OH, OW), device=input.device, dtype=input.dtype)
    total = N * out_c * OH * OW
    if total == 0:
        return output

    has_bias = bias is not None
    if has_bias:
        bias_t = bias
    else:
        bias_t = input  # unused placeholder, HAS_BIAS gates all reads

    # BLOCK=1024: tuned for thead PPU — balances parallelism against
    # per-block register pressure.
    BLOCK = 1024
    num_warps = 16
    grid = (triton.cdiv(total, BLOCK),)

    with torch_device_fn.device(input.device):
        _depthwise2d_kernel[grid](
            input,
            weight,
            bias_t,
            output,
            N,
            out_c,
            IH,
            IW,
            OH,
            OW,
            mult,
            *input.stride(),
            weight.stride()[0],
            weight.stride()[2],
            weight.stride()[3],
            *output.stride(),
            stride_h,
            stride_w,
            pad_h,
            pad_w,
            dil_h,
            dil_w,
            HAS_BIAS=has_bias,
            KH=KH,
            KW=KW,
            BLOCK=BLOCK,
            num_warps=num_warps,
        )
    return output
