# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import tl_extra_shim

logger = logging.getLogger(__name__)

# Per-channel element count beyond which the multi-tile two-kernel
# approach is used.  Below this the generic layer's autotuned kernel
# is already well-tuned.
_MULTI_TILE_THRESHOLD = 500_000


def make_3d_for_bn(input: Tensor) -> Tensor:
    """
    Converts the input to a 3D view for batch normalization.

    Args:
        input: Input to render 3D.

    Returns:
        Input's 3D view.
    """
    if input.ndim == 2:
        input = input.unsqueeze(-1)

    elif input.ndim >= 4:
        input = input.flatten(2, -1)

    return input


# ---------------------------------------------------------------------------
# Multi-tile two-kernel path — used when per-channel element count exceeds
# _MULTI_TILE_THRESHOLD.  Splits the reduction across per-tile programs
# instead of serialising inside a single per-channel loop.
# ---------------------------------------------------------------------------


def _multi_tile_config(batch_dim, spatial_dim):
    """Tile shape for the per-tile kernels."""
    BLOCK_M = min(32, triton.next_power_of_2(batch_dim))
    BLOCK_N = min(64, triton.next_power_of_2(spatial_dim))
    m_tiles = triton.cdiv(batch_dim, BLOCK_M)
    n_tiles = triton.cdiv(spatial_dim, BLOCK_N)
    return BLOCK_M, BLOCK_N, m_tiles, n_tiles


@triton.jit
def partial_reduce_kernel(
    grad_output_pointer,
    input_pointer,
    mean_pointer,
    var_pointer,
    partial_term1_pointer,
    partial_term2_pointer,
    batch_dim,
    spatial_dim,
    grad_output_batch_stride,
    grad_output_feat_stride,
    grad_output_spatial_stride,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    eps,
    n_tiles: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Compute per-tile term1 and term2 partial sums.

    Grid: (feat_dim * m_tiles * n_tiles,).
    """
    pid = tl.program_id(axis=0)
    tiles_per_channel = n_tiles * tl.cdiv(batch_dim, BLOCK_M)
    feat_pid = pid // tiles_per_channel
    tile_off = pid % tiles_per_channel
    m_idx = tile_off // n_tiles
    n_idx = tile_off % n_tiles

    mean = tl.load(feat_pid + mean_pointer).to(tl.float32)
    var = tl.load(feat_pid + var_pointer).to(tl.float32)
    inv_std = tl_extra_shim.rsqrt(var + eps)

    batch_offset = m_idx * BLOCK_M + tl.arange(0, BLOCK_M)
    batch_mask = batch_offset < batch_dim

    spatial_offset = n_idx * BLOCK_N + tl.arange(0, BLOCK_N)
    spatial_mask = spatial_offset < spatial_dim

    curr_grad_output_pointer = (
        grad_output_pointer
        + grad_output_feat_stride * feat_pid
        + grad_output_batch_stride * batch_offset[:, None]
        + grad_output_spatial_stride * spatial_offset[None, :]
    )
    curr_input_pointer = (
        input_pointer
        + input_feat_stride * feat_pid
        + input_batch_stride * batch_offset[:, None]
        + input_spatial_stride * spatial_offset[None, :]
    )

    mask = batch_mask[:, None] & spatial_mask[None, :]
    curr_input = tl.load(curr_input_pointer, mask=mask, other=0.0).to(tl.float32)
    curr_norm = (curr_input - mean) * inv_std
    curr_grad_output = tl.load(curr_grad_output_pointer, mask=mask, other=0.0).to(
        tl.float32
    )

    term1_scalar = tl.sum(curr_norm * curr_grad_output)
    term2_scalar = tl.sum(curr_grad_output)

    store_idx = pid
    tl.store(store_idx + partial_term1_pointer, term1_scalar)
    tl.store(store_idx + partial_term2_pointer, term2_scalar)


@triton.jit
def input_grad_kernel(
    grad_output_pointer,
    input_pointer,
    weight_pointer,
    weight_grad_pointer,
    bias_grad_pointer,
    mean_pointer,
    var_pointer,
    input_grad_pointer,
    batch_dim,
    spatial_dim,
    grad_output_batch_stride,
    grad_output_feat_stride,
    grad_output_spatial_stride,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    input_grad_batch_stride,
    input_grad_feat_stride,
    input_grad_spatial_stride,
    eps,
    n_tiles: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Compute grad_input per tile (highly parallel second pass)."""
    pid = tl.program_id(axis=0)
    tiles_per_channel = n_tiles * tl.cdiv(batch_dim, BLOCK_M)
    feat_pid = pid // tiles_per_channel
    tile_off = pid % tiles_per_channel
    m_idx = tile_off // n_tiles
    n_idx = tile_off % n_tiles

    mean = tl.load(feat_pid + mean_pointer).to(tl.float32)
    var = tl.load(feat_pid + var_pointer).to(tl.float32)
    inv_std = tl_extra_shim.rsqrt(var + eps)

    term1 = tl.load(feat_pid + weight_grad_pointer).to(tl.float32)
    term2 = tl.load(feat_pid + bias_grad_pointer).to(tl.float32)

    if weight_pointer:
        weight = tl.load(feat_pid + weight_pointer).to(tl.float32)
    else:
        weight = 1.0

    count = batch_dim * spatial_dim

    batch_offset = m_idx * BLOCK_M + tl.arange(0, BLOCK_M)
    batch_mask = batch_offset < batch_dim

    spatial_offset = n_idx * BLOCK_N + tl.arange(0, BLOCK_N)
    spatial_mask = spatial_offset < spatial_dim

    curr_grad_output_pointer = (
        grad_output_pointer
        + grad_output_feat_stride * feat_pid
        + grad_output_batch_stride * batch_offset[:, None]
        + grad_output_spatial_stride * spatial_offset[None, :]
    )
    curr_input_pointer = (
        input_pointer
        + input_feat_stride * feat_pid
        + input_batch_stride * batch_offset[:, None]
        + input_spatial_stride * spatial_offset[None, :]
    )
    curr_input_grad_pointer = (
        input_grad_pointer
        + input_grad_feat_stride * feat_pid
        + input_grad_batch_stride * batch_offset[:, None]
        + input_grad_spatial_stride * spatial_offset[None, :]
    )

    mask = batch_mask[:, None] & spatial_mask[None, :]
    curr_input = tl.load(curr_input_pointer, mask=mask, other=0.0).to(tl.float32)
    curr_norm = (curr_input - mean) * inv_std
    curr_grad_output = tl.load(curr_grad_output_pointer, mask=mask, other=0.0).to(
        tl.float32
    )
    curr_input_grad = (
        inv_std * weight * (curr_grad_output - (term1 * curr_norm + term2) / count)
    )
    tl.store(
        curr_input_grad_pointer,
        curr_input_grad,
        mask=mask,
    )


def _run_multi_tile(
    input_3d,
    grad_output_3d,
    weight,
    save_mean,
    save_var,
    input_grad,
    batch_dim,
    feat_dim,
    spatial_dim,
    epsilon,
):
    BLOCK_M, BLOCK_N, m_tiles, n_tiles = _multi_tile_config(batch_dim, spatial_dim)
    tiles_per_channel = m_tiles * n_tiles
    total_tiles = feat_dim * tiles_per_channel

    weight_grad = torch.zeros((feat_dim,), dtype=torch.float32, device=input_3d.device)
    bias_grad = torch.zeros((feat_dim,), dtype=torch.float32, device=input_3d.device)

    partial_term1 = torch.empty(
        total_tiles, dtype=torch.float32, device=input_3d.device
    )
    partial_term2 = torch.empty(
        total_tiles, dtype=torch.float32, device=input_3d.device
    )

    with torch_device_fn.device(input_3d.device):
        partial_reduce_kernel[(total_tiles,)](
            grad_output_3d,
            input_3d,
            save_mean,
            save_var,
            partial_term1,
            partial_term2,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            epsilon,
            n_tiles=n_tiles,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            num_warps=1,
        )

    # On-device reduction — torch.sum on GPU, fast for small tensors.
    weight_grad.copy_(partial_term1.view(feat_dim, tiles_per_channel).sum(dim=1))
    bias_grad.copy_(partial_term2.view(feat_dim, tiles_per_channel).sum(dim=1))

    with torch_device_fn.device(input_3d.device):
        input_grad_kernel[(total_tiles,)](
            grad_output_3d,
            input_3d,
            weight,
            weight_grad,
            bias_grad,
            save_mean,
            save_var,
            input_grad,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            *input_grad.stride(),
            epsilon,
            n_tiles=n_tiles,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            num_warps=1,
        )

    return weight_grad.to(input_3d.dtype), bias_grad.to(input_3d.dtype)


def _run_single_kernel(
    input_3d,
    grad_output_3d,
    weight,
    save_mean,
    save_var,
    input_grad,
    weight_grad,
    bias_grad,
    batch_dim,
    spatial_dim,
    epsilon,
):
    """Use the generic layer's autotuned kernel for small shapes.

    The generic kernel is already well-tuned for modest per-channel
    element counts where the reduction inside a per-feature program
    is cheap.  We import at call time (not module level) so the
    override in flag_gems.__init__ does not affect the import.
    """
    from flag_gems.ops.cudnn_batch_norm_backward import (
        cudnn_batch_norm_backward_kernel as generic_kernel,
    )

    feat_dim = input_3d.shape[1]
    generic_kernel[(feat_dim,)](
        grad_output_3d,
        input_3d,
        weight,
        save_mean,
        save_var,
        input_grad,
        weight_grad,
        bias_grad,
        batch_dim,
        spatial_dim,
        *grad_output_3d.stride(),
        *input_3d.stride(),
        *input_grad.stride(),
        epsilon,
        True,
        True,
        True,
    )


# ---------------------------------------------------------------------------
# Public entry point — name must match the generic layer.
# ---------------------------------------------------------------------------


def cudnn_batch_norm_backward(
    input: Tensor,
    grad_output: Tensor,
    weight: Tensor,
    running_mean: Tensor = None,
    running_var: Tensor = None,
    save_mean: Tensor = None,
    save_var: Tensor = None,
    epsilon: float = 1e-5,
    reserveSpace: Tensor = None,
):
    """Backward pass for cudnn_batch_norm, specialised for thead PPU.

    For per-channel element counts below 500 000 the generic layer's
    autotuned kernel is used (one program per feature channel).
    Above the threshold the reduction is split across per-tile
    programs to increase parallelism, which is critical when feat_dim
    is small but batch_dim * spatial_dim is large.
    """
    logger.debug("GEMS_THEAD CUDNN_BATCH_NORM_BACKWARD")

    input_3d = make_3d_for_bn(input)
    grad_output_3d = make_3d_for_bn(grad_output)

    batch_dim, feat_dim, spatial_dim = input_3d.shape

    input_grad = torch.empty_like(input_3d)
    total_per_channel = batch_dim * spatial_dim

    if total_per_channel < _MULTI_TILE_THRESHOLD:
        weight_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
        bias_grad = torch.empty((feat_dim,), dtype=input.dtype, device=input.device)
        with torch_device_fn.device(input.device):
            _run_single_kernel(
                input_3d,
                grad_output_3d,
                weight,
                save_mean,
                save_var,
                input_grad,
                weight_grad,
                bias_grad,
                batch_dim,
                spatial_dim,
                epsilon,
            )
        return (
            input_grad.view_as(input),
            weight_grad,
            bias_grad,
        )
    else:
        weight_grad, bias_grad = _run_multi_tile(
            input_3d,
            grad_output_3d,
            weight,
            save_mean,
            save_var,
            input_grad,
            batch_dim,
            feat_dim,
            spatial_dim,
            epsilon,
        )
        return (
            input_grad.view_as(input),
            weight_grad,
            bias_grad,
        )
