# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _diag_scatter_fused_kernel(
    inp_ptr,
    src_ptr,
    out_ptr,
    N,
    dim2_size,
    inner_size,
    offset,
    diag_len,
    BLOCK: tl.constexpr,
):
    # Fused copy + diagonal scatter: every output element is either a plain
    # copy of the input or, when it sits on the requested diagonal
    # (col - row == offset), the corresponding src value. One kernel replaces
    # the generic clone-then-scatter pair, halving the launch count — the
    # dominant cost on thead PPU at the small shapes this op benchmarks with.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N

    batch = offs // inner_size
    rem = offs % inner_size
    row = rem // dim2_size
    col = rem % dim2_size

    on_diag = (col - row) == offset
    # Position along the diagonal: row index for upper/main diagonals,
    # col index for lower ones (matches torch.diagonal src ordering).
    pos = tl.where(offset >= 0, row, col)

    in_val = tl.load(inp_ptr + offs, mask=mask, other=0)
    src_val = tl.load(src_ptr + batch * diag_len + pos, mask=mask & on_diag, other=0)
    tl.store(out_ptr + offs, tl.where(on_diag, src_val, in_val), mask=mask)


def _launch_fused(inp, src, out, dim1_size, dim2_size, offset, diag_len):
    N = out.numel()
    inner_size = dim1_size * dim2_size
    # A per-tile grid beats a single fat program on thead PPU: one program
    # covering the whole tensor serializes its many blocks through a single
    # CU, while the extra dispatch cost of a few small tiles is lower.
    BLOCK = 1024
    grid = (triton.cdiv(N, BLOCK),)
    if grid[0] > 65535:
        # thead PPU grid-dim cap: widen the block for very large tensors.
        BLOCK = 4096
        grid = (triton.cdiv(N, BLOCK),)
    _diag_scatter_fused_kernel[grid](
        inp,
        src,
        out,
        N,
        dim2_size,
        inner_size,
        offset,
        diag_len,
        BLOCK=BLOCK,
        num_warps=4,
    )


def _diag_len(dim1_size, dim2_size, offset):
    if offset >= 0:
        return max(0, min(dim1_size, dim2_size - offset))
    return max(0, min(dim1_size + offset, dim2_size))


def diagonal_scatter(input, src, offset=0, dim1=0, dim2=1):
    """Scatter src values into the diagonal of a clone of input.

    thead specialization: a single fused kernel streams the input to the
    output once, overwriting only the diagonal lanes with src values gathered
    from the flat src buffer. The generic implementation launches a full
    clone kernel plus a scatter kernel (and pays extra Python permute
    scaffolding), which costs ~2x on the small shapes where this op is
    launch-overhead-bound.
    """
    logger.debug("GEMS_THEAD DIAGONAL_SCATTER")

    ndim = input.ndim
    if dim1 < 0:
        dim1 += ndim
    if dim2 < 0:
        dim2 += ndim

    if dim1 == ndim - 2 and dim2 == ndim - 1:
        # Fast path: the diagonal lives in the last two dims, so for a
        # contiguous input the flat output index maps directly onto
        # (batch, row, col) with no data movement or permutation.
        inp = input if input.is_contiguous() else input.contiguous()
        output = torch.empty_like(inp)
        dim1_size, dim2_size = inp.shape[-2], inp.shape[-1]
        diag_len = _diag_len(dim1_size, dim2_size, offset)
        if diag_len > 0 and src.numel() > 0:
            src_flat = src.contiguous().reshape(-1)
            _launch_fused(
                inp.reshape(-1),
                src_flat,
                output.reshape(-1),
                dim1_size,
                dim2_size,
                offset,
                diag_len,
            )
            return output
        return inp.clone()

    # General path: permute the diagonal dims to the end, run the same fused
    # kernel on the contiguous permuted view, then permute back.
    perm = [i for i in range(ndim) if i != dim1 and i != dim2] + [dim1, dim2]
    input_perm = input.permute(perm).contiguous()
    output_perm = torch.empty_like(input_perm)

    dim1_size = input_perm.shape[-2]
    dim2_size = input_perm.shape[-1]
    diag_len = _diag_len(dim1_size, dim2_size, offset)

    if diag_len > 0 and src.numel() > 0:
        src_flat = src.contiguous().reshape(-1)
        _launch_fused(
            input_perm.reshape(-1),
            src_flat,
            output_perm.reshape(-1),
            dim1_size,
            dim2_size,
            offset,
            diag_len,
        )
    else:
        output_perm = input_perm.clone()

    inv_perm = [0] * ndim
    for i, p in enumerate(perm):
        inv_perm[p] = i
    return output_perm.permute(inv_perm).contiguous()
