# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

import flag_gems

logger = logging.getLogger(__name__)


@triton.jit
def _embedding_dense_backward_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_weight_ptr,
    num_weights,
    padding_idx,
    N_ROWS,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
    EMBED_DIM: tl.constexpr,
):
    # Each program scatters BLOCK_N rows of grad_output (each EMBED_DIM wide)
    # into grad_weight via atomic_add. The generic layer launches one program
    # per (row, D-tile) with a flat 1-D D-tile, which under-utilises the PPU:
    # it fixes BLOCK_D=128 / num_warps=4, and the tiny per-program work plus
    # the default 4-warp launch dominate the small/medium bench shapes. Tiling
    # rows x cols in 2-D lets a single program cover many more output rows per
    # launch (fewer programs, more work each) and pairs a wide D-tile with
    # num_warps=1, which profiling shows is the sweet spot on this hardware
    # (more warps oversubscribe the scatter/atomic path and regress).
    pid_n = tl.program_id(0)
    pid_d = tl.program_id(1)

    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    mask_n = offs_n < N_ROWS
    offs_d = pid_d * BLOCK_D + tl.arange(0, BLOCK_D)
    mask_d = offs_d < EMBED_DIM

    idx = tl.load(indices_ptr + offs_n, mask=mask_n, other=-1).to(tl.int32)
    valid = (idx != padding_idx) & (idx >= 0) & (idx < num_weights)

    # 2-D gather of the grad_output block: (BLOCK_N, BLOCK_D).
    offs = offs_n[:, None] * EMBED_DIM + offs_d[None, :]
    m = mask_n[:, None] & mask_d[None, :]
    go = tl.load(grad_output_ptr + offs, mask=m, other=0).to(tl.float32)

    # Scatter-add into the corresponding weight rows. Different rows may map to
    # the same weight row (duplicate indices), so accumulation must be atomic.
    gw_ptrs = idx[:, None] * EMBED_DIM + offs_d[None, :]
    tl.atomic_add(grad_weight_ptr + gw_ptrs, go, mask=(m & valid[:, None]))


@triton.jit
def _embedding_dense_backward_count_kernel(
    indices_ptr,
    counts_ptr,
    N,
    num_weights,
    padding_idx,
    BLOCK_N: tl.constexpr,
):
    pid = tl.program_id(0)
    offs = pid * BLOCK_N + tl.arange(0, BLOCK_N)
    mask = offs < N
    idx = tl.load(indices_ptr + offs, mask=mask, other=0).to(tl.int32)
    valid = mask & (idx != padding_idx) & (idx >= 0) & (idx < num_weights)
    tl.atomic_add(counts_ptr + idx, 1, mask=valid)


@triton.jit
def _embedding_dense_backward_kernel_scale_by_freq(
    grad_output_ptr,
    indices_ptr,
    counts_ptr,
    grad_weight_ptr,
    num_weights,
    padding_idx,
    N_ROWS,
    BLOCK_N: tl.constexpr,
    BLOCK_D: tl.constexpr,
    EMBED_DIM: tl.constexpr,
):
    pid_n = tl.program_id(0)
    pid_d = tl.program_id(1)

    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    mask_n = offs_n < N_ROWS
    offs_d = pid_d * BLOCK_D + tl.arange(0, BLOCK_D)
    mask_d = offs_d < EMBED_DIM

    idx = tl.load(indices_ptr + offs_n, mask=mask_n, other=-1).to(tl.int32)
    valid = (idx != padding_idx) & (idx >= 0) & (idx < num_weights)

    offs = offs_n[:, None] * EMBED_DIM + offs_d[None, :]
    m = mask_n[:, None] & mask_d[None, :]
    go = tl.load(grad_output_ptr + offs, mask=m, other=0).to(tl.float32)

    # Scale by 1 / count(indices) in fp32 before accumulating. The count load
    # is guarded by `valid` so padded rows keep a unit scale and contribute 0
    # (their grad_output is masked out of the atomic_add anyway).
    cnt = tl.load(counts_ptr + idx, mask=valid, other=1).to(tl.float32)
    go = go / cnt[:, None]

    gw_ptrs = idx[:, None] * EMBED_DIM + offs_d[None, :]
    tl.atomic_add(grad_weight_ptr + gw_ptrs, go, mask=(m & valid[:, None]))


def _block_heuristics(D):
    # D-tile: cover the whole embedding dim in one program when it is small
    # (avoids splitting a short row across programs), otherwise cap at 1024 to
    # bound register pressure. N-tile: ~2048 elements per program keeps enough
    # programs in flight for occupancy while amortising launch overhead, capped
    # at 16 rows so a single program never owns too many competing atomics.
    BLOCK_D = min(triton.next_power_of_2(D), 1024)
    BLOCK_N = max(1, min(2048 // BLOCK_D, 16))
    return BLOCK_N, BLOCK_D


def embedding_dense_backward(
    grad_output: torch.Tensor,
    indices: torch.Tensor,
    num_weights: int,
    padding_idx: int,
    scale_grad_by_freq: bool,
):
    logger.debug("GEMS_THEAD EMBEDDING_DENSE_BACKWARD")
    assert indices.dtype in (
        torch.int32,
        torch.int64,
    ), "Indices must be int32 or int64."
    if (
        grad_output.device.type != flag_gems.device
        or indices.device.type != flag_gems.device
        or grad_output.device != indices.device
    ):
        raise ValueError(
            f"Inputs must be {flag_gems.device} tensors on the same device."
        )

    device = grad_output.device
    assert (
        grad_output.dim() >= 2
    ), "grad_output must have embedding dimension as the last dim."

    D = grad_output.shape[-1]
    go = grad_output.contiguous().view(-1, D)  # (N, D)
    idx = indices.contiguous().view(-1)
    N = idx.numel()

    assert go.shape[0] == N, "indices number must match grad_output rows."
    grad_weight_fp32 = torch.zeros((num_weights, D), device=device, dtype=torch.float32)

    BLOCK_N, BLOCK_D = _block_heuristics(D)
    grid = (triton.cdiv(N, BLOCK_N), triton.cdiv(D, BLOCK_D))
    pad = padding_idx if padding_idx is not None else -1

    if scale_grad_by_freq:
        counts = torch.zeros((num_weights,), device=device, dtype=torch.int32)
        BLOCK_N_CNT = 512
        _embedding_dense_backward_count_kernel[(triton.cdiv(N, BLOCK_N_CNT),)](
            idx,
            counts,
            N,
            num_weights,
            pad,
            BLOCK_N=BLOCK_N_CNT,
        )

        _embedding_dense_backward_kernel_scale_by_freq[grid](
            go,
            idx,
            counts,
            grad_weight_fp32,
            num_weights,
            pad,
            N,
            BLOCK_N=BLOCK_N,
            BLOCK_D=BLOCK_D,
            EMBED_DIM=D,
            num_warps=1,
        )
    else:
        _embedding_dense_backward_kernel[grid](
            go,
            idx,
            grad_weight_fp32,
            num_weights,
            pad,
            N,
            BLOCK_N=BLOCK_N,
            BLOCK_D=BLOCK_D,
            EMBED_DIM=D,
            num_warps=1,
        )

    if grad_output.dtype != torch.float32:
        return grad_weight_fp32.to(grad_output.dtype)
    return grad_weight_fp32
