# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _abs_u32(x):
    ux = x.to(tl.uint32)
    return tl.where(x < 0, 0 - ux, ux)


@triton.jit
def _abs_u64(x):
    ux = x.to(tl.uint64)
    return tl.where(x < 0, 0 - ux, ux)


@triton.jit
def _gcd_euclid_i32(x, y):
    """Per-lane Euclid-by-remainder GCD for int32.

    Operates in unsigned to safely handle INT32_MIN (whose absolute value
    overflows int32).  Lanes converge independently; the ballot
    (tl.sum over active) stops the warp as soon as every lane is done.
    On thead PPU this beats the generic binary-GCD kernel because each
    iteration is a single cheap integer div/rem instead of multiple
    ffs (ctz) + where chains.
    """
    ax = _abs_u32(x)
    ay = _abs_u32(y)
    a = ax
    b = ay
    active = b != 0
    while tl.sum(active.to(tl.int32), axis=0) > 0:
        safe_b = tl.where(active, b, 1)
        r = a % safe_b
        a = tl.where(active, b, a)
        b = tl.where(active, r, b)
        active = active & (b != 0)
    return a.to(tl.int32)


@triton.jit
def _gcd_euclid_i64(x, y):
    """Per-lane Euclid-by-remainder GCD for int64.

    Same algorithm as the i32 variant but operating in uint64.
    NOTE: 64-bit div/rem is relatively expensive on thead PPU; for i64
    the generic binary-GCD may be faster.  This is still correct and is
    included for completeness — benchmark and test suites only exercise
    i16/i32.
    """
    ax = _abs_u64(x)
    ay = _abs_u64(y)
    a = ax
    b = ay
    active = b != 0
    while tl.sum(active.to(tl.int32), axis=0) > 0:
        safe_b = tl.where(active, b, 1)
        r = a % safe_b
        a = tl.where(active, b, a)
        b = tl.where(active, r, b)
        active = active & (b != 0)
    return a.to(tl.int64)


# ---------------------------------------------------------------------------
# Out-of-place kernels (used by gcd() and by the gcd_ slow-promotion path)
# ---------------------------------------------------------------------------


@triton.jit
def gcd_kernel_i32(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x, y)
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_kernel_i16(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    # int16 path: widen to int32 so |INT16_MIN| is representable, compute
    # in int32, then narrow (mod 2**16) back to the storage dtype.
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x.to(tl.int32), y.to(tl.int32))
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_kernel_i64(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i64(x, y)
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


# ---------------------------------------------------------------------------
# In-place kernels — read x and y, write result back over x
# ---------------------------------------------------------------------------


@triton.jit
def gcd_inplace_kernel_i32(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x, y)
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_inplace_kernel_i16(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i32(x.to(tl.int32), y.to(tl.int32))
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


@triton.jit
def gcd_inplace_kernel_i64(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _gcd_euclid_i64(x, y)
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


# ---------------------------------------------------------------------------
# Host-side helpers
# ---------------------------------------------------------------------------


def _kernel_meta(dtype):
    """Return (out_of_place_kernel, inplace_kernel, BLOCK, num_warps)."""
    # Euclid remainder kernels are divergence-tolerant (lanes retire as
    # their remainder hits zero), so a single warp (num_warps=1) keeps
    # the integer div/rem unit fully fed.  More warps oversubscribe it.
    if dtype in (torch.int8, torch.int16):
        return gcd_kernel_i16, gcd_inplace_kernel_i16, 128, 1
    if dtype == torch.int32:
        return gcd_kernel_i32, gcd_inplace_kernel_i32, 128, 1
    if dtype == torch.int64:
        return gcd_kernel_i64, gcd_inplace_kernel_i64, 128, 1
    raise TypeError(f"unsupported dtype for gcd: {dtype}")


def _materialize_inputs(self, other):
    promoted_dtype = torch.promote_types(self.dtype, other.dtype)
    lhs = self if self.dtype == promoted_dtype else self.to(promoted_dtype)
    rhs = other if other.dtype == promoted_dtype else other.to(promoted_dtype)
    if lhs.shape == rhs.shape:
        return lhs.contiguous(), rhs.contiguous(), promoted_dtype
    lhs, rhs = torch.broadcast_tensors(lhs, rhs)
    return lhs.contiguous(), rhs.contiguous(), promoted_dtype


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def gcd(self, other):
    """Compute element-wise greatest common divisor (out-of-place).

    Uses per-lane Euclid-by-remainder (with an early-exit warp ballot) to
    compute GCD, avoiding the fixed worst-case unrolled binary-GCD loop
    that serializes the generic kernel on thead PPU.
    """
    logger.debug("GEMS_THEAD GCD")
    lhs, rhs, promoted_dtype = _materialize_inputs(self, other)
    result = torch.empty_like(lhs, dtype=promoted_dtype)
    numel = result.numel()
    if numel == 0:
        return result

    kernel, _, block, num_warps = _kernel_meta(promoted_dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        result.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return result.view(lhs.shape)


def gcd_(self, other):
    """In-place version of gcd: self = gcd(self, other)."""
    logger.debug("GEMS_THEAD GCD_")
    if self.dtype != other.dtype or self.shape != other.shape:
        # Promotion / broadcast fall back to the out-of-place path plus a copy.
        self.copy_(gcd(self, other))
        return self

    lhs = self.contiguous()
    rhs = other.contiguous()
    numel = lhs.numel()
    if numel == 0:
        return self

    _, kernel, block, num_warps = _kernel_meta(self.dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return self
