# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _abs_u32(x):
    ux = x.to(tl.uint32)
    return tl.where(x < 0, 0 - ux, ux)


@triton.jit
def _abs_u64(x):
    ux = x.to(tl.uint64)
    return tl.where(x < 0, 0 - ux, ux)


@triton.jit
def _gcd_ballot_u32(ax, ay):
    # Per-lane Euclid by remainder with an early-exit program-wide ballot:
    # lanes that have converged skip the div/rem, and the loop stops as soon
    # as every lane in the program is done. On thead PPU the ballot (tl.sum
    # over the predicate) is far cheaper than the fixed worst-case unrolled
    # binary-GCD loop the generic kernel serializes through, because random
    # full-range inputs only need ~35 remainder steps on average.
    a = ax
    b = ay
    active = b != 0
    while tl.sum(active.to(tl.int32), axis=0) > 0:
        safe_b = tl.where(active, b, 1)
        r = a % safe_b
        a = tl.where(active, b, a)
        b = tl.where(active, r, b)
        active = active & (b != 0)
    return a


@triton.jit
def _lcm_epilogue_i32(ax, ay, g):
    # Reproduce torch's exact overflow semantics for int32: the exact product
    # |x| / g * |y| is computed in uint64 (it can reach ~2^62), wrapped mod
    # 2^32, and the wrapped 32-bit value is then taken in absolute value
    # (two's-complement negate), matching torch's CPU/CUDA native kernels.
    g64 = g.to(tl.uint64)
    g_safe = tl.where(g64 == 0, 1, g64)
    prod = (ax.to(tl.uint64) // g_safe) * ay.to(tl.uint64)
    w = (prod % 4294967296).to(tl.uint32)
    res = tl.where(w.to(tl.int32) < 0, 0 - w, w)
    return tl.where(g64 == 0, 0, res)


@triton.jit
def _lcm_while_i32(x, y):
    ax = _abs_u32(x)
    ay = _abs_u32(y)
    g = _gcd_ballot_u32(ax, ay)
    return _lcm_epilogue_i32(ax, ay, g)


@triton.jit
def _lcm_while_i64(x, y):
    # uint64 all the way: the product wraps mod 2^64 exactly like the exact
    # result truncated to the storage dtype, and the wrapped value is taken
    # in absolute value to match torch's native semantics.
    ax = _abs_u64(x)
    ay = _abs_u64(y)
    a = ax
    b = ay
    active = b != 0
    while tl.sum(active.to(tl.int32), axis=0) > 0:
        safe_b = tl.where(active, b, 1)
        r = a % safe_b
        a = tl.where(active, b, a)
        b = tl.where(active, r, b)
        active = active & (b != 0)
    g = a
    g_safe = tl.where(g == 0, 1, g)
    w = (ax // g_safe) * ay
    res = tl.where(w.to(tl.int64) < 0, 0 - w, w)
    return tl.where(g == 0, 0, res)


@triton.jit
def lcm_kernel_i32(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _lcm_while_i32(x, y)
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_kernel_i16(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    # int8/int16 path: torch promotes the computation to a wider signed type
    # and narrows the wrapped result WITHOUT the final abs() (narrowing after
    # the 32-bit abs is identical to plain truncation). So: Euclid in uint32,
    # product in uint64, truncate mod 2^bits.
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0).to(tl.int32)
    y = tl.load(y_ptr + offsets, mask=mask, other=0).to(tl.int32)
    ax = _abs_u32(x)
    ay = _abs_u32(y)
    g = _gcd_ballot_u32(ax, ay)
    g64 = g.to(tl.uint64)
    g_safe = tl.where(g64 == 0, 1, g64)
    prod = (ax.to(tl.uint64) // g_safe) * ay.to(tl.uint64)
    res = tl.where(g64 == 0, 0, prod.to(tl.uint32))
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_kernel_i64(x_ptr, y_ptr, out_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _lcm_while_i64(x, y)
    tl.store(out_ptr + offsets, res.to(out_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_inplace_kernel_i32(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    # In-place variant: read x once, write the result back over it. Saves the
    # separate output allocation plus the extra read/write of the generic
    # lcm + copy_ staging.
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _lcm_while_i32(x, y)
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_inplace_kernel_i16(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0).to(tl.int32)
    y = tl.load(y_ptr + offsets, mask=mask, other=0).to(tl.int32)
    ax = _abs_u32(x)
    ay = _abs_u32(y)
    g = _gcd_ballot_u32(ax, ay)
    g64 = g.to(tl.uint64)
    g_safe = tl.where(g64 == 0, 1, g64)
    prod = (ax.to(tl.uint64) // g_safe) * ay.to(tl.uint64)
    res = tl.where(g64 == 0, 0, prod.to(tl.uint32))
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


@triton.jit
def lcm_inplace_kernel_i64(x_ptr, y_ptr, n_elements, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0)
    y = tl.load(y_ptr + offsets, mask=mask, other=0)
    res = _lcm_while_i64(x, y)
    tl.store(x_ptr + offsets, res.to(x_ptr.type.element_ty), mask=mask)


def _kernel_meta(dtype):
    # The early-exit ballot (tl.sum over the active predicate) is cheaper the
    # fewer lanes a program has to scan per iteration, so tiny blocks with a
    # single warp win on thead PPU: BLOCK=32/nw=1 measured fastest for both
    # the int32 and the int16/int8 paths on full-range random inputs.
    if dtype in (torch.int8, torch.int16):
        return lcm_kernel_i16, lcm_inplace_kernel_i16, 32, 1
    if dtype == torch.int32:
        return lcm_kernel_i32, lcm_inplace_kernel_i32, 32, 1
    if dtype == torch.int64:
        return lcm_kernel_i64, lcm_inplace_kernel_i64, 32, 1
    raise TypeError(f"unsupported dtype for lcm: {dtype}")


def _materialize_inputs(self, other):
    promoted_dtype = torch.promote_types(self.dtype, other.dtype)
    lhs = self if self.dtype == promoted_dtype else self.to(promoted_dtype)
    rhs = other if other.dtype == promoted_dtype else other.to(promoted_dtype)
    # Fast path for the common case where the operands already share a shape
    # (including empty tensors): no broadcast is needed, so return them directly.
    # This avoids the GEMS ``broadcast_tensors`` op, whose ``expand`` step
    # rejects size-0 dimensions.
    if lhs.shape == rhs.shape:
        return lhs.contiguous(), rhs.contiguous(), promoted_dtype
    lhs, rhs = torch.broadcast_tensors(lhs, rhs)
    return lhs.contiguous(), rhs.contiguous(), promoted_dtype


def lcm(self, other):
    """Compute element-wise least common multiple.

    Uses per-lane Euclid (remainder loop with an early-exit ballot) to derive
    lcm(a, b) = |a| / gcd(a, b) * |b|, avoiding the fixed worst-case unrolled
    binary-GCD loop that serializes the generic kernel on thead PPU. The
    product is formed in uint64 and the wrapped result taken in absolute
    value (int32/int64) or plainly truncated (int8/int16), reproducing
    torch's native overflow semantics on full-range inputs.
    """
    logger.debug("GEMS_THEAD LCM")
    lhs, rhs, promoted_dtype = _materialize_inputs(self, other)
    result = torch.empty_like(lhs, dtype=promoted_dtype)
    numel = result.numel()
    if numel == 0:
        return result

    kernel, _, block, num_warps = _kernel_meta(promoted_dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        result.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return result.view(lhs.shape)


def lcm_(self, other):
    """In-place version of lcm."""
    logger.debug("GEMS_THEAD LCM_")
    if self.dtype != other.dtype or self.shape != other.shape:
        # Promotion / broadcast fall back to the out-of-place path plus a copy.
        self.copy_(lcm(self, other))
        return self

    lhs = self.contiguous()
    rhs = other.contiguous()
    numel = lhs.numel()
    if numel == 0:
        return self

    _, kernel, block, num_warps = _kernel_meta(self.dtype)
    grid = (triton.cdiv(numel, block),)
    kernel[grid](
        lhs.reshape(-1),
        rhs.reshape(-1),
        numel,
        BLOCK=block,
        num_warps=num_warps,
    )
    return self
