# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils.triton_lang_extension import program_id

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def cholesky_vec_kernel(
    A,
    L,
    N: tl.constexpr,
    stride_a,
    stride_l,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    """Left-looking column Cholesky of one (N x N) matrix.

    One program handles a whole matrix: for each column ``j`` it computes the
    full lower-triangular column at once, vectorizing the ``k``-summation over
    the already-computed columns with a blocked reduction instead of the
    scalar element-by-element loop used by the generic layer. The column-wide
    load/store and reduction parallelize across the matrix rows, which is what
    makes a single program competitive on the PPU for small/medium ``N``.
    """
    pid = program_id(0)
    base_a = A + pid * stride_a
    base_l = L + pid * stride_l
    rows = tl.arange(0, BLOCK_N).to(tl.int64)
    row_mask = rows < N
    cols_k = tl.arange(0, BLOCK_K).to(tl.int64)
    for j in range(N):
        # Load column j of A (all rows).
        a_col = tl.load(base_a + rows * N + j, mask=row_mask, other=0.0)
        acc = a_col
        # Subtract sum_{k<j} L[i, k] * L[j, k]  (matrix-vector over k-blocks).
        for k0 in range(0, j, BLOCK_K):
            k = k0 + cols_k
            kmask = k < j
            lcol = tl.load(
                base_l + rows[:, None] * N + k[None, :],
                mask=row_mask[:, None] & kmask[None, :],
                other=0.0,
            )
            lrow = tl.load(base_l + j * N + k, mask=kmask, other=0.0)
            acc = acc - tl.sum(lcol * lrow[None, :], axis=1)
        # diag = acc[j]; L[j, j] = sqrt(diag); L[i, j] = acc[i] / diag for i > j.
        diag = tl.sum(tl.where(rows == j, acc, 0.0))
        piv = tl.sqrt(tl.maximum(diag, 1.0e-20))
        lcol_out = tl.where(rows >= j, acc / piv, 0.0)
        lcol_out = tl.where(rows == j, piv, lcol_out)
        tl.store(base_l + rows * N + j, lcol_out, mask=row_mask)
        # Column j+1 reads back column j just stored, so the store must be
        # globally visible before the next iteration's load; without the barrier
        # the load can observe uninitialized ``L`` (``torch.empty_like``) memory.
        tl.debug_barrier()


def _vec_cholesky(A2d, n):
    """Run the vectorized single-kernel Cholesky on a (batch, n, n) tensor."""
    b = A2d.shape[0]
    L = torch.empty_like(A2d)
    block_n = triton.next_power_of_2(n)
    # BLOCK_K=16 balances reduction width against register pressure on the PPU.
    cholesky_vec_kernel[(b,)](
        A2d,
        L,
        n,
        A2d.stride(0),
        L.stride(0),
        block_n,
        16,
        num_warps=4,
    )
    return L


def _delegate_cholesky(A, upper):
    """Fall back to the vendor-native cuSOLVER potrf via ``cholesky_ex``.

    The generic layer's scalar element-by-element Cholesky kernel cannot compete
    with cuSOLVER's blocked potrf on the PPU for large matrices (it was ~140x
    slower at [256, 256]). ``torch.linalg.cholesky_ex`` dispatches to the native
    cuSOLVER-backed ``aten.linalg_cholesky_ex`` kernel, which is *not* overridden
    by FlagGems (only ``aten.linalg_cholesky`` is), so this does not recurse.
    """
    L, _info = torch.linalg.cholesky_ex(A, upper=upper, check_errors=False)
    return L


def linalg_cholesky(A, upper=False):
    logger.debug("GEMS_THEAD LINALG_CHOLESKY")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), "linalg_cholesky only supports float32 and float64"

    if A.numel() == 0:
        return A

    shape = A.shape
    if len(shape) < 2:
        raise ValueError("A must be at least 2D")

    n = shape[-1]
    m = shape[-2]
    if m != n:
        raise ValueError("A must be a square matrix")

    # Strategy: the PPU's scalar element-by-element path (generic layer) is
    # uncompetitive for every shape, so neither extreme wins everywhere.
    #  * Small/medium N: a single vectorized kernel is much faster than a
    #    cuSOLVER launch because it amortizes the launch overhead and keeps the
    #    whole matrix in one program's registers/SMEM (up to ~5-16x on tiny N).
    #  * Large N: cuSOLVER's blocked potrf is faster, so delegate to it.
    # The cut-off is per dtype: fp64 doubles the register footprint, so the
    # vectorized kernel stops winning earlier than for fp32.
    if A.dtype == torch.float32:
        use_vec = n <= 32
    else:
        use_vec = n <= 16

    if not use_vec:
        return _delegate_cholesky(A, upper)

    # The kernel reads the whole matrix row-major, so it needs a contiguous 3D
    # view (batch, n, n). ``reshape`` is a free view when A is already
    # contiguous; we only materialize a copy in the rare non-contiguous case.
    A_view = A.reshape(-1, n, n)
    if not A_view.is_contiguous():
        A_view = A_view.contiguous()

    L2d = _vec_cholesky(A_view, n)
    L = L2d.reshape(shape)
    # The kernel writes a strict lower triangle (zeros above the diagonal), so no
    # separate tril pass is needed — adding one would just launch an extra
    # elementwise kernel and regress the small-shape case that this path exists
    # to optimize.

    if upper:
        L = L.transpose(-2, -1).conj()
    return L
