# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging

import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)
UNROLL = 4

# log2(e), ln(2) and 2*pi as constexpr globals so they fold into kernel
# constants rather than being treated as runtime values.
LOG2E = tl.constexpr(1.4426950408889634)
LN2 = tl.constexpr(0.6931471805599453)
TWO_PI = tl.constexpr(6.283185307179586)


@triton.jit
def fast_sin_cos(x):
    # High-precision minimax sin/cos on [-pi, pi] (~1.5e-9 max error).
    # Cheaper than the libdevice sin/cos pair on this hardware, which matters
    # for the bandwidth-bound huge-shape case where compute is the bottleneck.
    x = x - TWO_PI * tl.floor(x / TWO_PI + 0.5)
    x2 = x * x

    # SIN: 7th-order minimax  x * P(x^2)
    s_c0 = 0.99999999999999999999
    s_c1 = -0.16666666666666666654
    s_c2 = 0.00833333333333332876
    s_c3 = -0.00019841269841269616
    s_c4 = 2.755731922398589e-6
    s_c5 = -2.505210838544172e-8
    sin_x = x * (
        s_c0 + x2 * (s_c1 + x2 * (s_c2 + x2 * (s_c3 + x2 * (s_c4 + x2 * s_c5))))
    )

    # COS: 6th-order minimax  Q(x^2)
    c_c0 = 1.0
    c_c1 = -0.49999999999999999983
    c_c2 = 0.04166666666666666636
    c_c3 = -0.00138888888888888742
    c_c4 = 2.4801587301587299e-5
    c_c5 = -2.755731922398581e-7
    cos_x = c_c0 + x2 * (c_c1 + x2 * (c_c2 + x2 * (c_c3 + x2 * (c_c4 + x2 * c_c5))))

    return sin_x, cos_x


def log_normal_heur_block(args):
    """Select block size for log-normal generation on PPU.

    Smaller blocks keep enough programs in flight for tiny shapes; the heaviest
    shapes are memory-bandwidth-bound and prefer BLOCK=1024 to amortize launch
    overhead.
    """
    N = args["N"]
    if N <= 4096:
        return 128
    elif N <= 1048576:
        return 256
    else:
        return 1024


def log_normal_heur_num_warps(args):
    # num_warps=4 wins across the board on this hardware: more warps
    # oversubscribe the SFU/transcendental unit used by exp2/log2/sin/cos.
    N = args["N"]
    if N <= 4096:
        return 2
    else:
        return 4


@triton.heuristics(
    {
        "BLOCK": log_normal_heur_block,
        "num_warps": log_normal_heur_num_warps,
    }
)
@triton.jit(do_not_specialize=["philox_seed", "philox_offset"])
def log_normal_kernel(
    out_ptr,
    N,
    mean,
    std,
    philox_seed,
    philox_offset,
    BLOCK: tl.constexpr,
):
    # Fused single-kernel log-normal sampler:
    #   Philox RNG -> uniform float -> Box-Muller normal -> exp(n*std + mean)
    #
    # The generic implementation writes the normal samples to a temporary fp32
    # buffer and runs a second elementwise kernel to apply exp() into the output
    # tensor. Fusing Philox + Box-Muller + exp into one kernel removes the
    # temporary buffer allocation and the second launch, which is the main win on
    # huge shapes and matches the generic impl on mid shapes.
    #
    # exp/log are expressed via exp2/log2 with pre-multiplied constants
    # (std*LOG2E, mean*LOG2E, -2*ln2) and a fused-multiply-add so the affine
    # transform folds into a single fma; this is measurably faster than the
    # natural-base tl.exp/tl.log path on this hardware.
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)
    c0 = (philox_offset & 0xFFFFFFFF).to(tl.uint32)
    c1 = ((philox_offset >> 32) & 0xFFFFFFFF).to(tl.uint32)
    i4 = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    c0 += i4
    _O = c0 * 0
    r0, r1, r2, r3 = tl.philox(philox_seed, c0, c1, _O, _O)
    r0 = uint_to_uniform_float(r0)
    r1 = uint_to_uniform_float(r1)
    r2 = uint_to_uniform_float(r2)
    r3 = uint_to_uniform_float(r3)

    # Box-Muller:  r = sqrt(-2 ln u),  n = r * cos/sin(2 pi u2)
    # log2(u) * ln2 == log(u),  keeping everything in fp32.
    u1 = tl.maximum(1.0e-7, r0)
    th = TWO_PI * r1
    r = tl.sqrt(-2.0 * tl.math.log2(u1) * LN2)
    s, c = fast_sin_cos(th)
    n0 = r * c
    n1 = r * s

    u2 = tl.maximum(1.0e-7, r2)
    th2 = TWO_PI * r3
    r2v = tl.sqrt(-2.0 * tl.math.log2(u2) * LN2)
    s2, c2 = fast_sin_cos(th2)
    n2 = r2v * c2
    n3 = r2v * s2

    # log-normal = exp(n*std + mean) = exp2(n*std*LOG2E + mean*LOG2E)
    sl = std * LOG2E
    ml = mean * LOG2E
    y0 = tl.math.exp2(tl.fma(n0, sl, ml))
    y1 = tl.math.exp2(tl.fma(n1, sl, ml))
    y2 = tl.math.exp2(tl.fma(n2, sl, ml))
    y3 = tl.math.exp2(tl.fma(n3, sl, ml))

    off_0 = tl.program_id(0) * BLOCK * 4 + tl.arange(0, BLOCK)
    off_1 = off_0 + BLOCK
    off_2 = off_1 + BLOCK
    off_3 = off_2 + BLOCK

    tl.store(out_ptr + off_0, y0, mask=off_0 < N)
    tl.store(out_ptr + off_1, y1, mask=off_1 < N)
    tl.store(out_ptr + off_2, y2, mask=off_2 < N)
    tl.store(out_ptr + off_3, y3, mask=off_3 < N)


def log_normal_(self, mean=1.0, std=2.0, *, generator=None):
    logger.debug("GEMS_THEAD LOG_NORMAL_")
    shape = self.shape
    device = self.device

    N = volume(shape)
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK"] * UNROLL),)

    increment = triton.cdiv(N, UNROLL)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )
    with torch_device_fn.device(device):
        log_normal_kernel[grid_fn](self, N, mean, std, philox_seed, philox_offset)
    return self
