# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Below this output size (in elements) the launch-overhead saving from fusing
# the zero-fill and the scatter into a single kernel outweighs the per-element
# cost of the fused kernel's div/mod + broadcast compare. Above it the output
# buffer write becomes memory-bandwidth bound: a pure memset (which the generic
# layer's ``torch.zeros_like`` already runs at memcpy bandwidth) plus a tiny
# scatter is optimal, and the fused kernel's extra compute only contends with
# the store path and regresses. Measured crossover on thead PPU sits just above
# 1M elements (1024x1024 fused wins, 10000x256 fused loses), so small/medium
# shapes use the fused kernel and large shapes fall back to the memset + scatter
# path (matching the generic layer's latency).
_FUSED_THRESHOLD = 1 << 20  # 1,048,576 elements


@libentry()
@triton.jit(do_not_specialize=["ignore_index"])
def nll_loss_backward_fused_kernel(
    out_grad_ptr,
    tgt_ptr,
    wgt_ptr,
    inp_grad_ptr,
    ignore_index,
    total_weight,
    N,
    C,
    reduction: tl.constexpr = 1,
    HAS_WEIGHT: tl.constexpr = False,
    BLOCK: tl.constexpr = 1024,
):
    # Single-pass fill+scatter over the full (N, C) grad buffer. Each program
    # owns a flat BLOCK-element tile of the output; for every element it writes
    # the gradient when the element's column equals its row's target, and zero
    # otherwise. This fuses the generic layer's separate full-tensor memset
    # (torch.zeros_like, the dominant cost on small/medium tensors because it
    # is a whole extra kernel launch) with the scatter, removing one launch.
    pid = tl.program_id(0)
    idx = pid * BLOCK + tl.arange(0, BLOCK)
    n_total = N * C
    mask = idx < n_total

    # Decompose the flat offset into (row, col). C is a specialized (non
    # do_not_specialize) arg, so Triton compiles div/mod by a constant and
    # lowers them to multiply-shift.
    row = idx // C
    col = idx % C

    tgt = tl.load(tgt_ptr + row, mask=mask, other=ignore_index)
    valid = (tgt != ignore_index) & mask

    if HAS_WEIGHT:
        w = tl.load(wgt_ptr + tgt, mask=valid, other=0).to(tl.float32)
    else:
        w = valid.to(tl.float32)

    if reduction == 0:
        out_grad = tl.load(out_grad_ptr + row, mask=mask, other=0).to(tl.float32)
    else:
        out_grad = tl.load(out_grad_ptr).to(tl.float32)
    if reduction == 1:
        total_w = tl.load(total_weight).to(tl.float32)
    else:
        total_w = 1.0

    grad_val = tl.where(valid, -out_grad * w / total_w, 0.0)

    # The target column of each row receives the gradient; every other column
    # is zeroed. For ignored rows tgt == ignore_index (typically -100), so
    # ``col == tgt`` is never true and the whole row is zeroed as required.
    out = tl.where((col == tgt) & mask, grad_val, 0.0)
    tl.store(inp_grad_ptr + idx, out, mask=mask)


@libentry()
@triton.jit(do_not_specialize=["ignore_index"])
def nll_loss_backward_scatter_kernel(
    out_grad_ptr,
    tgt_ptr,
    wgt_ptr,
    inp_grad_ptr,
    ignore_index,
    total_weight,
    N,
    C,
    reduction: tl.constexpr = 1,
    HAS_WEIGHT: tl.constexpr = False,
    BLOCK_N: tl.constexpr = 1024,
):
    # Scatter-only: writes just the one target position per row. The output
    # buffer is assumed pre-zeroed (by the caller's memset), so non-target
    # elements are left at zero. Used on large tensors where the memset is the
    # memory-bandwidth floor and a separate memset + this scatter matches the
    # generic layer's latency without the fused kernel's per-element overhead.
    pid_n = tl.program_id(0)
    offsets_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    mask_n = offsets_n < N

    tgt = tl.load(tgt_ptr + offsets_n, mask=mask_n, other=ignore_index)
    valid = (tgt != ignore_index) & mask_n

    if HAS_WEIGHT:
        wgt_tgt = tl.load(wgt_ptr + tgt, mask=valid, other=0).to(tl.float32)
    else:
        wgt_tgt = valid.to(tl.float32)

    if reduction == 0:
        out_grad = tl.load(out_grad_ptr + offsets_n, mask=mask_n, other=0).to(
            tl.float32
        )
    else:
        out_grad = tl.load(out_grad_ptr).to(tl.float32)
    if reduction == 1:
        total_w = tl.load(total_weight).to(tl.float32)
    else:
        total_w = 1.0

    inp_grad = tl.where(valid, -out_grad * wgt_tgt / total_w, 0.0)
    inp_grad_ptrs = inp_grad_ptr + offsets_n * C + tgt
    tl.store(inp_grad_ptrs, inp_grad, mask=mask_n)


def nll_loss_backward(
    grad_output,
    self,
    target,
    weight=None,
    reduction=1,
    ignore_index=-100,
    total_weight=None,
):
    logger.debug("GEMS_THEAD NLL_LOSS_BACKWARD")
    # nll_loss_backward is only validated for float dtypes on thead; reject
    # integer/other dtypes explicitly (Rule 31: unsupported dtype → assert).
    assert (
        self.dtype.is_floating_point
    ), f"nll_loss_backward only supports floating-point dtypes on thead, got {self.dtype}"
    N = 1 if self.ndim == 1 else self.shape[0]
    C = self.shape[-1]

    grad_output = grad_output.contiguous()
    target = target.contiguous()
    weight = None if weight is None else weight.contiguous()

    has_weight = weight is not None
    n_total = N * C

    if n_total <= _FUSED_THRESHOLD:
        # Small/medium: fuse the zero-fill and the scatter into one kernel.
        # Allocate UNINITIALIZED (torch.empty_like); the fused kernel memsets
        # the buffer to zero and scatter-writes the target positions in one
        # pass, removing the generic layer's separate torch.zeros_like launch.
        grad_input = torch.empty_like(self).contiguous()
        # BLOCK=512: tuned for thead PPU scatter-write workload — balances
        # parallelism (grid = ceil(n_total/512)) against per-block register
        # pressure for the fused memset+scatter loop.
        BLOCK = 512
        grid = (triton.cdiv(n_total, BLOCK),)
        with torch_device_fn.device(self.device):
            nll_loss_backward_fused_kernel[grid](
                grad_output,
                target,
                weight,
                grad_input,
                ignore_index,
                total_weight,
                N,
                C,
                reduction,
                HAS_WEIGHT=has_weight,
                BLOCK=BLOCK,
            )
    else:
        # Large: the output write is bandwidth-bound. A pure memset
        # (torch.zeros_like, already at memcpy bandwidth) plus this tiny
        # scatter is optimal and matches the generic layer; the fused kernel's
        # per-element compute would only contend with the store path here.
        grad_input = torch.zeros_like(self).contiguous()
        BLOCK_N = 128
        grid = (triton.cdiv(N, BLOCK_N),)
        with torch_device_fn.device(self.device):
            nll_loss_backward_scatter_kernel[grid](
                grad_output,
                target,
                weight,
                grad_input,
                ignore_index,
                total_weight,
                N,
                C,
                reduction,
                HAS_WEIGHT=has_weight,
                BLOCK_N=BLOCK_N,
            )

    return grad_input
