# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def reflection_pad3d_backward_kernel(
    grad_ptr,
    out_ptr,
    N,
    C,
    D_in,
    H_in,
    W_in,
    D_out,
    H_out,
    W_out,
    pad_d0,
    pad_h0,
    pad_w0,
    stride_grad_n,
    stride_grad_c,
    stride_grad_d,
    stride_grad_h,
    stride_grad_w,
    stride_out_n,
    stride_out_c,
    stride_out_d,
    stride_out_h,
    stride_out_w,
    BLOCK_DHW: tl.constexpr,
):
    pid_bc = tl.program_id(1)
    pid_dhw = tl.program_id(0)

    pid_n = pid_bc % N
    pid_c = pid_bc // N

    # Output (grad_output) position this program tile covers.
    dhw_start = pid_dhw * BLOCK_DHW
    dhw_offs = dhw_start + tl.arange(0, BLOCK_DHW)
    mask = dhw_offs < D_out * H_out * W_out

    d_out = dhw_offs // (H_out * W_out)
    h_out = (dhw_offs // W_out) % H_out
    w_out = dhw_offs % W_out

    # Reflect the output index back into the input index range. The reflection
    # has period 2*(dim-1); the kernel is only launched when padding > 0, which
    # (given pad < dim) guarantees dim >= 2, so the period is always >= 2.
    Dm1 = D_in - 1
    D_period = 2 * Dm1 if Dm1 > 0 else 1
    x_d = d_out - pad_d0
    m_d = tl.abs(x_d) % D_period
    d_idx = tl.where(m_d < D_in, m_d, D_period - m_d)

    Hm1 = H_in - 1
    H_period = 2 * Hm1 if Hm1 > 0 else 1
    x_h = h_out - pad_h0
    m_h = tl.abs(x_h) % H_period
    h_idx = tl.where(m_h < H_in, m_h, H_period - m_h)

    Wm1 = W_in - 1
    W_period = 2 * Wm1 if Wm1 > 0 else 1
    x_w = w_out - pad_w0
    m_w = tl.abs(x_w) % W_period
    w_idx = tl.where(m_w < W_in, m_w, W_period - m_w)

    grad_offs = (
        pid_n * stride_grad_n
        + pid_c * stride_grad_c
        + d_out * stride_grad_d
        + h_out * stride_grad_h
        + w_out * stride_grad_w
    )
    grad_val = tl.load(grad_ptr + grad_offs, mask=mask, other=0.0)

    out_offs = (
        pid_n * stride_out_n
        + pid_c * stride_out_c
        + d_idx * stride_out_d
        + h_idx * stride_out_h
        + w_idx * stride_out_w
    )

    # Scatter-add the upstream gradient into grad_input. Unlike the generic
    # layer, we accumulate directly in grad_input's own dtype instead of routing
    # through a float32 staging buffer + trailing cast: this hardware supports
    # low-precision atomic_add (see adaptive_max_pool3d_backward), so the staging
    # buffer and cast kernel — which dominate bf16/fp16 latency — are dropped.
    # The mask skips out-of-range tail threads, avoiding their wasted atomics.
    tl.atomic_add(out_ptr + out_offs, grad_val, mask=mask)


def reflection_pad3d_backward(grad_output, self, padding):
    """Compute gradient of reflection_pad3d forward pass.

    Args:
        grad_output: Gradient of the loss with respect to the output of reflection_pad3d.
                    Shape: (N, C, D + pad_d0 + pad_d1, H + pad_h0 + pad_h1, W + pad_w0 + pad_w1)
        self: Original input tensor before padding. Shape: (N, C, D, H, W)
        padding: Tuple of 6 ints (pad_d0, pad_d1, pad_h0, pad_h1, pad_w0, pad_w1)

    Returns:
        Gradient with respect to self. Shape: (N, C, D, H, W)
    """
    logger.debug("GEMS_THEAD REFLECTION_PAD3D_BACKWARD")

    if isinstance(padding, int):
        pad_d0 = pad_d1 = pad_h0 = pad_h1 = pad_w0 = pad_w1 = padding
    else:
        pad_d0, pad_d1, pad_h0, pad_h1, pad_w0, pad_w1 = padding

    if self.dim() != 5:
        raise ValueError("input must be a 5D tensor")

    N, C, D_in, H_in, W_in = self.shape
    D_out, H_out, W_out = (
        D_in + pad_d0 + pad_d1,
        H_in + pad_h0 + pad_h1,
        W_in + pad_w0 + pad_w1,
    )

    expected_grad_shape = (N, C, D_out, H_out, W_out)
    if tuple(grad_output.shape) != expected_grad_shape:
        raise ValueError(
            f"grad_output has shape {tuple(grad_output.shape)}, expected {expected_grad_shape}"
        )

    if (
        pad_d0 == 0
        and pad_d1 == 0
        and pad_h0 == 0
        and pad_h1 == 0
        and pad_w0 == 0
        and pad_w1 == 0
    ):
        return grad_output.clone()

    grad_output = grad_output.contiguous()

    # Accumulate directly in the input dtype — no float32 staging buffer and no
    # trailing dtype cast (see kernel comment). Multiple output positions can
    # reflect onto the same input position, so atomic_add is still required.
    out = torch.zeros_like(self)

    BLOCK_DHW = 256
    grid = (
        triton.cdiv(D_out * H_out * W_out, BLOCK_DHW),
        N * C,
    )

    reflection_pad3d_backward_kernel[grid](
        grad_output,
        out,
        N,
        C,
        D_in,
        H_in,
        W_in,
        D_out,
        H_out,
        W_out,
        pad_d0,
        pad_h0,
        pad_w0,
        *grad_output.stride(),
        *out.stride(),
        BLOCK_DHW=BLOCK_DHW,
    )

    return out
