# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


@libentry()
@triton.jit(do_not_specialize=["p", "maxnorm"])
def renorm_kernel(
    X,
    Y,
    M,
    N,
    stride_m,
    p,
    maxnorm,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Fused single-pass Lp renormalization, strided column-tile.

    Operates directly on a 2-D view of the tensor whose reduction axis is the
    last (contiguous, stride-1) axis: each program owns ``BLOCK_N`` sub-tensors
    (one per column) and reduces the ``M`` rows of each column in one tile.

    This fuses the norm computation and the scale-apply into a single launch
    (the generic layer uses two kernels and a redundant full-tensor pass) and,
    crucially, avoids the permute + contiguous copy the generic path performs
    to fold the reduction dim to the front: reading the strided columns directly
    removes one full-tensor read+write. fp32 accumulation for fp16/bf16 matches
    PyTorch's per-slice norm precision.

    ``X`` and ``Y`` may alias (in-place ``renorm_``): the norm is fully
    accumulated before any store, so the second (store) pass reading ``X`` again
    sees the original values.
    """
    pid_n = tl.program_id(0)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_m = tl.arange(0, BLOCK_M)
    mask_n = offs_n < N
    mask_m = offs_m < M
    mask = mask_m[:, None] & mask_n[None, :]

    # fp32 accumulation for fp16/bf16 to match PyTorch's per-slice norm precision.
    if tl.constexpr(X.dtype.element_ty == tl.float16) or tl.constexpr(
        X.dtype.element_ty == tl.bfloat16
    ):
        cdtype = tl.float32
    else:
        cdtype = X.dtype.element_ty

    # Load the whole M-row column tile at once (M fits in BLOCK_M), accumulate
    # the per-column Lp-norm. The reduction axis is fully covered in one load,
    # so no inner loop is needed and correctness is independent of BLOCK_M.
    x = tl.load(
        X + offs_m[:, None] * stride_m + offs_n[None, :],
        mask=mask,
        other=0.0,
    ).to(cdtype)
    if p == 2.0:
        acc = tl.sum(x * x, axis=0)
        norm = tl_extra_shim.sqrt(acc)
    else:
        acc = tl.sum(tl_extra_shim.pow(tl.abs(x), p), axis=0)
        norm = tl_extra_shim.pow(acc, 1.0 / p)

    # scale = maxnorm / norm when norm > maxnorm, else 1.0 (no change).
    scale = tl.where(norm > maxnorm, maxnorm / norm, 1.0)

    y = x * scale[None, :]
    tl.store(
        Y + offs_m[:, None] * stride_m + offs_n[None, :],
        y.to(Y.dtype.element_ty),
        mask=mask,
    )


def _heuristics(M, N):
    """Pick the (BLOCK_M, BLOCK_N, num_warps) tile for thead PPU.

    ``BLOCK_M`` covers the full reduction length when it fits (single-tile
    load, no inner loop), capped at 1024 to bound register pressure. ``BLOCK_N``
    packs several sub-tensors (columns) per program so the fixed launch cost is
    amortized over more elements; it shrinks for large ``BLOCK_M`` to keep the
    BLOCK_M*BLOCK_N register tile bounded. ``num_warps`` follows the tile size.
    """
    BLOCK_M = min(triton.next_power_of_2(M), 1024)
    if BLOCK_M >= 1024:
        BLOCK_N = 2
        num_warps = 4
    elif BLOCK_M >= 256:
        BLOCK_N = min(triton.next_power_of_2(N), 8)
        num_warps = 4
    elif BLOCK_M >= 64:
        BLOCK_N = min(triton.next_power_of_2(N), 16)
        num_warps = 4 if BLOCK_N <= 4 else 8
    else:
        BLOCK_N = min(triton.next_power_of_2(N), 32)
        num_warps = 8
    return BLOCK_M, BLOCK_N, num_warps


def _launch(x2d, y2d, M, N, stride_m, p, maxnorm):
    """Run the fused kernel on a 2-D view with the reduction axis last."""
    BLOCK_M, BLOCK_N, num_warps = _heuristics(M, N)
    grid = (triton.cdiv(N, BLOCK_N),)
    with torch_device_fn.device(x2d.device):
        renorm_kernel[grid](
            x2d,
            y2d,
            M,
            N,
            stride_m,
            p,
            maxnorm,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            num_warps=num_warps,
        )


def _fold_dim_to_last(input, dim):
    """Reshape ``input`` so the reduction axis is the last (contiguous,
    stride-1) axis and everything else flattens to the leading axis, returning
    the 2-D view plus the inverse reshape.

    For a contiguous tensor the reduction axis has stride 1 only when it is
    already the last axis; otherwise the elements of a sub-tensor are strided.
    To make the reduction axis stride-1 we permute it to the end and call
    ``.contiguous()`` (one copy) — the strided kernel then reads that contiguous
    buffer's last axis directly with no further permute/copy. The result is
    reshaped back to the original shape.
    """
    ndim = input.ndim
    perm = [i for i in range(ndim) if i != dim] + [dim]
    inv_perm = [0] * ndim
    for i, pi in enumerate(perm):
        inv_perm[pi] = i
    x_perm = input.permute(perm).contiguous()
    M = x_perm.numel() // x_perm.shape[-1]
    N = x_perm.shape[-1]
    # x_perm is (..., N) contiguous -> reshape to (M, N) is a view, N stride 1.
    x2d = x_perm.reshape(M, N)
    return x2d, x_perm, perm, inv_perm, M, N


def renorm(input, p, dim, maxnorm):
    logger.debug("GEMS_THEAD RENORM")
    if dim < 0:
        dim = input.ndim + dim

    x2d, x_perm, perm, inv_perm, M, N = _fold_dim_to_last(input, dim)
    out2d = torch.empty_like(x2d)
    _launch(x2d, out2d, M, N, x2d.stride(0), p, maxnorm)
    return out2d.reshape(x_perm.shape).permute(inv_perm)


def renorm_(input, p, dim, maxnorm):
    logger.debug("GEMS_THEAD RENORM_")
    if dim < 0:
        dim = input.ndim + dim

    x2d, x_perm, perm, inv_perm, M, N = _fold_dim_to_last(input, dim)
    # In-place on the contiguous permuted buffer, then copy back to the original
    # (possibly strided) tensor in its layout.
    _launch(x2d, x2d, M, N, x2d.stride(0), p, maxnorm)
    input.copy_(x2d.reshape(x_perm.shape).permute(inv_perm))
    return input
