# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _cheb_u_poly(xv, nv):
    """Evaluate U_nv(xv) for nv in [0, 5] with the explicit formulas.

    Identical numerics to the generic layer:
      U_0 = 1, U_1 = 2x, U_2 = 4x^2-1, U_3 = 8x^3-4x,
      U_4 = 16x^4-12x^2+1, U_5 = 32x^5-32x^3+6x
    """
    x2 = xv * xv
    x3 = x2 * xv
    x4 = x3 * xv
    x5 = x4 * xv
    u0 = tl.full(xv.shape, 1.0, tl.float32)
    u1 = 2.0 * xv
    u2 = 4.0 * x2 - 1.0
    u3 = 8.0 * x3 - 4.0 * xv
    u4 = 16.0 * x4 - 12.0 * x2 + 1.0
    u5 = 32.0 * x5 - 32.0 * x3 + 6.0 * xv
    return tl.where(
        nv == 0,
        u0,
        tl.where(
            nv == 1,
            u1,
            tl.where(nv == 2, u2, tl.where(nv == 3, u3, tl.where(nv == 4, u4, u5))),
        ),
    )


@triton.jit
def _cheb_u_flat_kernel(x_ptr, out_ptr, n_scalar, N, BLOCK: tl.constexpr):
    # Uniform-order kernel: n is a scalar argument, no n tensor load at all.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    xv = tl.load(x_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    r = _cheb_u_poly(xv, n_scalar)
    tl.store(out_ptr + offs, r.to(out_ptr.dtype.element_ty), mask=mask)


@triton.jit
def _cheb_u_flat_tensor_n_kernel(x_ptr, n_ptr, out_ptr, N, BLOCK: tl.constexpr):
    # Per-element order kernel: both operands are contiguous flat tensors.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < N
    xv = tl.load(x_ptr + offs, mask=mask, other=0.0).to(tl.float32)
    nv = tl.load(n_ptr + offs, mask=mask, other=0).to(tl.int32)
    r = _cheb_u_poly(xv, nv)
    tl.store(out_ptr + offs, r.to(out_ptr.dtype.element_ty), mask=mask)


def _pick_block(N):
    # Latency-floor heuristic measured on PPU: a raw kernel launch is ~12 us
    # flat, so small shapes are pure launch overhead regardless of BLOCK;
    # large shapes are bandwidth-bound and prefer BLOCK=1024.
    if N <= 256:
        return 256
    if N <= 1024:
        return 512
    return 1024


def special_chebyshev_polynomial_u(x, n):
    """Compute the Chebyshev polynomial of the second kind U_n(x).

    thead specialization: the generic layer routes through
    ``pointwise_dynamic`` whose Python codegen/reshape/broadcast scaffolding
    costs ~100 us per call on PPU — 10-16x the ~12 us flat latency of a raw
    Triton launch and slower than torch's eager fallback on every shape.
    This implementation keeps the identical polynomial numerics but drives a
    plain flattened kernel directly, collapsing the wrapper overhead to one
    ``torch.empty`` + one kernel launch.

    Two kernels cover the two call shapes: a scalar-order kernel that takes
    ``n`` as a uniform argument (the common/benchmark path), and a
    tensor-order kernel for per-element orders. The PPU Triton toolchain
    miscompiles loads from zero-stride (expanded) tensors, so the scalar
    path deliberately avoids the ``n.expand(x.shape)`` broadcast load the
    generic layer uses; a tensor ``n`` is materialized contiguous instead.
    """
    logger.debug("GEMS_THEAD SPECIAL_CHEBYSHEV_POLYNOMIAL_U")
    assert x.dtype == torch.float32, f"unsupported dtype {x.dtype}"

    n_scalar = None
    if isinstance(n, torch.Tensor):
        if n.numel() == 1:
            # 0-dim / single-element tensor folds into the uniform path.
            n_scalar = int(n.item())
            n_min = n_max = n_scalar
        else:
            # Run the range guard on a CPU copy to avoid dispatching back
            # into gems reduction kernels while use_gems() is active.
            n_ref = n.detach().to("cpu", dtype=torch.int32)
            n_min = int(n_ref.amin().item())
            n_max = int(n_ref.amax().item())
            n = n.to(device=x.device, dtype=torch.int32)
    else:
        n_min = n_max = n_scalar = int(n)

    # Guard: only n in [0, 5] is supported by the explicit polynomial
    # formulas (same contract as the generic layer).
    if n_max > 5 or n_min < 0:
        raise ValueError(
            f"Chebyshev polynomial order n must be in [0, 5], "
            f"got values in [{n_min}, {n_max}]"
        )

    out = torch.empty_like(x)
    N = x.numel()
    if N == 0:
        return out

    # Flatten x; reshape falls back to a copy only when a flat view is
    # impossible (non-contiguous input), which the kernel handles correctly.
    xf = x.reshape(-1)
    of = out.reshape(-1)
    BLOCK = _pick_block(N)
    grid = (triton.cdiv(N, BLOCK),)

    with torch_device_fn.device(x.device):
        if n_scalar is not None:
            _cheb_u_flat_kernel[grid](xf, of, n_scalar, N, BLOCK=BLOCK)
        else:
            # Broadcast n to x's shape and materialize it contiguous: a
            # zero-stride view would miscompile on this toolchain.
            nf = (
                n.expand(x.shape)
                .reshape(-1)
                .contiguous()
                .to(device=x.device, dtype=torch.int32)
            )
            _cheb_u_flat_tensor_n_kernel[grid](xf, nf, of, N, BLOCK=BLOCK)
    return out
