# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Upper rank supported by the general (multi-index) kernel. Tiled tensor shapes
# in practice never exceed 5 dimensions, and a constexpr rank keeps the index
# decomposition branch-free per specialization.
_MAX_RANK = 6


@libentry()
@triton.jit
def _tile_repeat_axis0_kernel(
    in_ptr,
    out_ptr,
    n,
    K: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """Fast path: repeat *only* along the outermost (axis-0) dimension.

    For a contiguous input the output satisfies ``out_flat[idx] = in_flat[idx % n]``,
    so each input element is read exactly once and written ``K`` times. This
    halves the read traffic of a memcpy-style ``cat`` (which reads the input
    ``K`` times), which is the dominant win on the bandwidth-bound huge shapes.
    """
    pid = tl.program_id(0)
    offs = (pid * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = offs < n
    v = tl.load(in_ptr + offs, mask=mask)
    for k in tl.static_range(K):
        tl.store(out_ptr + k * n + offs, v, mask=mask)


@libentry()
@triton.jit
def _tile_general_kernel(
    in_ptr,
    out_ptr,
    s0,
    s1,
    s2,
    s3,
    s4,
    s5,
    d0,
    d1,
    d2,
    d3,
    d4,
    d5,
    os0,
    os1,
    os2,
    os3,
    os4,
    os5,
    out_numel,
    rank: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """General path: arbitrary repetition pattern / non-contiguous input.

    Decomposes each flat output index into its row-major multi-index (using the
    contiguous output strides), takes it modulo the (padded) input shape per axis,
    and gathers from the (possibly strided) input. Correct for every ``tile``
    shape; used as the fallback when the axis-0 fast path does not apply.
    """
    pid = tl.program_id(0)
    offs = (pid * BLOCK + tl.arange(0, BLOCK)).to(tl.int64)
    mask = offs < out_numel
    idx = offs

    o0 = idx // os0 if rank > 1 else idx
    if rank > 1:
        rem = idx % os0
        o1 = rem // os1 if rank > 2 else rem
    else:
        o1 = 0
        rem = 0
    if rank > 2:
        rem = rem % os1
        o2 = rem // os2 if rank > 3 else rem
    else:
        o2 = 0
    if rank > 3:
        rem = rem % os2
        o3 = rem // os3 if rank > 4 else rem
    else:
        o3 = 0
    if rank > 4:
        rem = rem % os3
        o4 = rem
    else:
        o4 = 0

    in_off = (
        (o0 % d0) * s0
        + (o1 % d1) * s1
        + (o2 % d2) * s2
        + (o3 % d3) * s3
        + (o4 % d4) * s4
    )
    v = tl.load(in_ptr + in_off, mask=mask)
    tl.store(out_ptr + offs, v, mask=mask)


def _align_ranks(x, dims):
    """Pad ``dims``/``x.shape`` with leading 1s so they share a common rank.

    Mirrors the rank alignment the generic layer performs before constructing the
    output shape, so the specialization preserves tile semantics exactly.
    """
    d = list(dims)
    sh = list(x.shape)
    r = max(len(sh), len(d))
    if len(d) < r:
        d = [1] * (r - len(d)) + d
    if len(sh) < r:
        sh = [1] * (r - len(sh)) + sh
        x = x.reshape(sh)
    return x, d, sh, r


def _is_axis0_single_repeat(d, r):
    """True when only the outermost dim is repeated (``d[0] >= 1`` and ``d[1:]`` all 1)."""
    if d[0] < 1:
        return False
    return all(d[i] == 1 for i in range(1, r))


def _launch_axis0(x, k, out_shape):
    n = x.numel()
    out = torch.empty(out_shape, device=x.device, dtype=x.dtype)
    # num_warps=4 is optimal across small/mid/huge shapes on this hardware;
    # BLOCK scales with the task count so tiny tensors still get one program
    # while huge tensors amortize launch overhead with large tiles.
    block = min(16384, max(1024, triton.next_power_of_2(n)))
    grid = (max(1, triton.cdiv(n, block)),)
    with torch_device_fn.device(x.device.index):
        _tile_repeat_axis0_kernel[grid](x, out, n, k, BLOCK=block, num_warps=4)
    return out


def _launch_general(x, d, sh, r, out_shape):
    out = torch.empty(out_shape, device=x.device, dtype=x.dtype)
    out_numel = 1
    for s in out_shape:
        out_numel *= s
    # Pad strides / shapes / output strides to _MAX_RANK so a single specialized
    # kernel signature covers every rank (unused slots are never read because
    # ``rank`` is a constexpr guard).
    in_strides = [int(st) for st in x.stride()]
    in_strides += [0] * (_MAX_RANK - len(in_strides))
    in_shapes = list(sh) + [1] * (_MAX_RANK - len(sh))
    out_strides = [0] * _MAX_RANK
    acc = 1
    for i in range(r - 1, -1, -1):
        out_strides[i] = acc
        acc *= out_shape[i]
    block = min(4096, max(512, triton.next_power_of_2(out_numel)))
    grid = (max(1, triton.cdiv(out_numel, block)),)
    with torch_device_fn.device(x.device.index):
        _tile_general_kernel[grid](
            x,
            out,
            in_strides[0],
            in_strides[1],
            in_strides[2],
            in_strides[3],
            in_strides[4],
            in_strides[5],
            in_shapes[0],
            in_shapes[1],
            in_shapes[2],
            in_shapes[3],
            in_shapes[4],
            in_shapes[5],
            out_strides[0],
            out_strides[1],
            out_strides[2],
            out_strides[3],
            out_strides[4],
            out_strides[5],
            out_numel,
            rank=r,
            BLOCK=block,
            num_warps=4,
        )
    return out


def tile(inp: torch.Tensor, dims) -> torch.Tensor:
    """Construct a tensor by repeating ``inp`` along each dimension per ``dims``.

    Specialized for the T-Head PPU:
      * An empty-result fast path avoids any kernel launch when any repeat is 0.
      * The common "repeat only the outermost axis on a contiguous tensor" case
        (every shape in the core benchmark) takes a single-read / K-write kernel
        that halves the read traffic of a memcpy-based repeat.
      * All other cases (multi-axis repeats, non-contiguous inputs) fall back to
        a general multi-index gather kernel that is correct for any rank.
    """
    logger.debug("GEMS_THEAD TILE")

    x, d, sh, r = _align_ranks(inp, dims)
    out_shape = [sh[i] * d[i] for i in range(r)]

    # Empty result: no data to copy, skip the kernel launch entirely.
    if any(s == 0 for s in out_shape):
        return torch.empty(out_shape, device=x.device, dtype=x.dtype)

    # Fast path: repeat only axis-0 on a contiguous tensor -> out_flat = in_flat
    # cyclically, so each input element is read once and written K times.
    if (
        r <= _MAX_RANK
        and d[0] >= 1
        and d[0] <= 8  # constexpr K: bound recompilation for huge repeat factors
        and _is_axis0_single_repeat(d, r)
        and x.is_contiguous()
    ):
        return _launch_axis0(x, d[0], out_shape)

    # General fallback: per-axis modulo gather, handles arbitrary rank/dims and
    # non-contiguous (strided) inputs.
    if r <= _MAX_RANK:
        return _launch_general(x, d, sh, r, out_shape)

    # Ranks beyond _MAX_RANK are not expected on thead. Reject explicitly rather
    # than recursing via torch.tile (which would dispatch back into this thead
    # specialization and loop infinitely). The general kernel is padded to
    # _MAX_RANK=6, which covers all realistic tile use cases.
    assert (
        r <= _MAX_RANK
    ), f"thead tile only supports output rank <= {_MAX_RANK}, got {r}"
