# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import torch
import triton
import triton.language as tl


@triton.jit
def _lstm_cell_bwd_kernel(
    grad_hy_ptr,
    grad_cy_ptr,
    cx_ptr,
    cy_ptr,
    ws_ptr,
    grad_gates_ptr,
    grad_cx_ptr,
    bias_accum_ptr,
    H,
    HAS_BIAS: tl.constexpr,
    BLOCK_H: tl.constexpr,
):
    row = tl.program_id(0)
    off = tl.arange(0, BLOCK_H)
    m = off < H
    row_off = row * H
    ws_base = ws_ptr + row * (4 * H)

    # workspace holds the four gate ACTIVATIONS (i, f, g, o) per row
    i = tl.load(ws_base + off, mask=m, other=0.0).to(tl.float32)
    f = tl.load(ws_base + H + off, mask=m, other=0.0).to(tl.float32)
    g = tl.load(ws_base + 2 * H + off, mask=m, other=0.0).to(tl.float32)
    o = tl.load(ws_base + 3 * H + off, mask=m, other=0.0).to(tl.float32)
    cx_v = tl.load(cx_ptr + row_off + off, mask=m, other=0.0).to(tl.float32)
    cy_v = tl.load(cy_ptr + row_off + off, mask=m, other=0.0).to(tl.float32)
    ghy = tl.load(grad_hy_ptr + row_off + off, mask=m, other=0.0).to(tl.float32)
    gcy = tl.load(grad_cy_ptr + row_off + off, mask=m, other=0.0).to(tl.float32)

    tc = tl.extra.libdevice.tanh(cy_v)
    gct = gcy + ghy * o * (1.0 - tc * tc)
    grad_cx_v = gct * f
    gi = gct * g * i * (1.0 - i)
    gf = gct * cx_v * f * (1.0 - f)
    gg = gct * i * (1.0 - g * g)
    go = ghy * tc * o * (1.0 - o)

    goff = row * (4 * H)
    tl.store(grad_gates_ptr + goff + off, gi, mask=m)
    tl.store(grad_gates_ptr + goff + H + off, gf, mask=m)
    tl.store(grad_gates_ptr + goff + 2 * H + off, gg, mask=m)
    tl.store(grad_gates_ptr + goff + 3 * H + off, go, mask=m)
    tl.store(grad_cx_ptr + row_off + off, grad_cx_v, mask=m)

    if HAS_BIAS:
        tl.atomic_add(bias_accum_ptr + off, gi, mask=m)
        tl.atomic_add(bias_accum_ptr + H + off, gf, mask=m)
        tl.atomic_add(bias_accum_ptr + 2 * H + off, gg, mask=m)
        tl.atomic_add(bias_accum_ptr + 3 * H + off, go, mask=m)


@triton.jit
def _cast_kernel(src_ptr, dst_ptr, N, BLOCK: tl.constexpr):
    off = tl.arange(0, BLOCK)
    m = off < N
    v = tl.load(src_ptr + off, mask=m, other=0.0)
    tl.store(dst_ptr + off, v.to(dst_ptr.dtype.element_ty), mask=m)


def run(grad_hy, grad_cy, cx, cy, workspace, has_bias):
    B, H = cx.shape
    H4 = 4 * H
    dtype = cx.dtype
    device = cx.device

    grad_gates = torch.empty_like(workspace)
    grad_cx = torch.empty_like(cx)

    block_h = triton.next_power_of_2(H)
    nw = max(1, block_h // 64)

    if has_bias:
        if dtype == torch.float32:
            bias_accum = torch.zeros(H4, dtype=dtype, device=device)
            grad_biases = bias_accum
        else:
            bias_accum = torch.zeros(H4, dtype=torch.float32, device=device)
            grad_biases = torch.empty(H4, dtype=dtype, device=device)
        _lstm_cell_bwd_kernel[(B,)](
            grad_hy,
            grad_cy,
            cx,
            cy,
            workspace,
            grad_gates,
            grad_cx,
            bias_accum,
            H,
            HAS_BIAS=True,
            BLOCK_H=block_h,
            num_warps=nw,
        )
        if dtype != torch.float32:
            _cast_kernel[(1,)](
                bias_accum,
                grad_biases,
                H4,
                BLOCK=triton.next_power_of_2(H4),
                num_warps=1,
            )
    else:
        grad_biases = None
        _lstm_cell_bwd_kernel[(B,)](
            grad_hy,
            grad_cy,
            cx,
            cy,
            workspace,
            grad_gates,
            grad_cx,
            grad_gates,
            H,
            HAS_BIAS=False,
            BLOCK_H=block_h,
            num_warps=nw,
        )

    return grad_gates, grad_cx, grad_biases
