# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("adaptive_max_pool3d_backward"),
    key=["out_h", "out_w", "n_elements"],
    reset_to_zero=["grad_input_ptr"],
)
@triton.jit
def adaptive_max_pool3d_backward_metax_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    in_n,
    in_c,
    in_d,
    in_h,
    in_w,
    out_d,
    out_h,
    out_w,
    n_elements: tl.constexpr,
    USE_ATOMIC: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Backward kernel for adaptive max pool 3d on Metax GPUs.

    Supports two modes via USE_ATOMIC:
      - USE_ATOMIC=False: direct store when spatial dims are evenly
        divisible. Each output position maps to one unique input position.
      - USE_ATOMIC=True: atomic add for the general case.
    """
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    out_per_nc = out_d * out_h * out_w

    nc_out = offsets // out_per_nc
    remainder = offsets % out_per_nc
    d_out = remainder // (out_h * out_w)
    remainder2 = remainder % (out_h * out_w)
    h_out = remainder2 // out_w
    w_out = remainder2 % out_w

    n_idx = nc_out // in_c
    c_idx = nc_out % in_c

    out_offset = (
        n_idx * in_c * out_per_nc
        + c_idx * out_per_nc
        + d_out * out_h * out_w
        + h_out * out_w
        + w_out
    )

    idx = tl.load(indices_ptr + out_offset, mask=mask, other=0)

    spatial_size = in_h * in_w
    d_in = idx // spatial_size
    remainder_idx = idx % spatial_size
    h_in = remainder_idx // in_w
    w_in = remainder_idx % in_w

    grad_val = tl.load(grad_output_ptr + out_offset, mask=mask, other=0.0)

    in_offset = (
        n_idx * in_c * in_d * in_h * in_w
        + c_idx * in_d * in_h * in_w
        + d_in * in_h * in_w
        + h_in * in_w
        + w_in
    )

    if USE_ATOMIC:
        tl.atomic_add(grad_input_ptr + in_offset, grad_val, mask=mask)
    else:
        tl.store(grad_input_ptr + in_offset, grad_val, mask=mask)


def adaptive_max_pool3d_backward(
    grad_output: torch.Tensor,
    self: torch.Tensor,
    indices: torch.Tensor,
):
    """Backward pass for adaptive_max_pool3d, optimized for Metax GPUs.

    When input spatial dimensions are evenly divisible by the output
    spatial dimensions, each output element maps to a unique input
    position and the kernel uses a fast tl.store path instead of
    tl.atomic_add, avoiding the serialization overhead.
    """
    logger.debug("GEMS_METAX ADAPTIVE_MAX_POOL3D_BACKWARD")

    in_n, in_c, in_d, in_h, in_w = self.shape
    out_d, out_h, out_w = (
        grad_output.shape[2],
        grad_output.shape[3],
        grad_output.shape[4],
    )

    evenly_divisible = in_d % out_d == 0 and in_h % out_h == 0 and in_w % out_w == 0

    if evenly_divisible:
        USE_ATOMIC = False
        grad_input = torch.zeros_like(self)
    else:
        USE_ATOMIC = True
        grad_input = torch.zeros_like(self, dtype=torch.float32)

    if grad_input.numel() == 0:
        return grad_input.to(grad_output.dtype)

    n_elements = in_n * in_c * out_d * out_h * out_w

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)

    adaptive_max_pool3d_backward_metax_kernel[grid](
        grad_output,
        indices,
        grad_input,
        in_n,
        in_c,
        in_d,
        in_h,
        in_w,
        out_d,
        out_h,
        out_w,
        n_elements,
        USE_ATOMIC=USE_ATOMIC,
    )

    return grad_input.to(grad_output.dtype)
