# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("lgamma"),
    key=["n_elements"],
)
@triton.jit
def lgamma_kernel(
    in_ptr,
    out_ptr,
    n_elements: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Metax-optimized 1D kernel for lgamma.

    Replaces the @pointwise_dynamic code-generated kernel with a
    hand-tuned contiguous 1D kernel.
    """
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(in_ptr + offsets, mask=mask, other=0.0)
    result = tl_extra_shim.lgamma(x.to(tl.float32))
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def lgamma(A):
    """Compute the natural logarithm of the absolute value of Gamma(x).

    Optimized for Metax GPUs with a hand-crafted 1D contiguous Triton
    kernel that avoids the runtime code-generation overhead of
    @pointwise_dynamic.
    """
    logger.debug("GEMS_METAX LGAMMA")
    orig_shape = A.shape
    A = A.contiguous().flatten()
    out = torch.empty_like(A)
    n_elements = A.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    lgamma_kernel[grid](A, out, n_elements)
    return out.reshape(orig_shape)


def lgamma_(A):
    """In-place version of lgamma, optimized for Metax GPUs."""
    logger.debug("GEMS_METAX LGAMMA_")
    orig_shape = A.shape
    A = A.contiguous().flatten()
    n_elements = A.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    lgamma_kernel[grid](A, A, n_elements)
    return A.reshape(orig_shape)
