# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""Metax-specific inplace wrapper for lt_ and lt_scalar_ with fused kernels
that avoid uitofp i1->bf16 by using tl.where to produce 1.0/0.0 float
values."""

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def lt_func(x, y):
    """Fused less-than that avoids uitofp i1->bf16.

    Uses tl.where to produce 1.0/0.0 float values directly from the boolean
    comparison result, so no uitofp is ever generated.  The final truncf
    (f32->output_dtype) happens in the generated store code and is supported
    on all backends.
    """
    cmp = x.to(tl.float32) < y
    return tl.where(cmp, 1.0, 0.0)


def lt_(A, B):
    logger.debug("GEMS_METAX LT_")
    if A.device != B.device:
        B = B.to(A.device)
    lt_func(A, B, out0=A)
    return A


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def lt_func_scalar(x, y):
    """Fused less-than for scalar that avoids uitofp i1->bf16.

    Uses tl.where to produce 1.0/0.0 float values directly from the boolean
    comparison result, so no uitofp is ever generated.
    """
    cmp = x.to(tl.float32) < y
    return tl.where(cmp, 1.0, 0.0)


def lt_scalar_(A, B):
    logger.debug("GEMS_METAX LT_SCALAR_")
    lt_func_scalar(A, B, out0=A)
    return A
