# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton

from flag_gems.runtime import torch_device_fn
from flag_gems.utils.shape_utils import volume

from .ones import ones_kernel

logger = logging.getLogger(__name__)


def new_ones(self, size, *, dtype=None, layout=None, device=None, pin_memory=None):
    """Returns a tensor filled with ones, with the same dtype/device as self.

    Muxi-optimized: uses the locally-tuned ones_kernel with block-size
    heuristics instead of the generic fixed-BLOCK_SIZE=1024 kernel.
    """
    logger.debug("GEMS_METAX NEW_ONES")
    if device is None:
        device = self.device
    if dtype is None:
        dtype = self.dtype

    out = torch.empty(size, device=device, dtype=dtype)
    N = volume(size)
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(device):
        ones_kernel[grid_fn](out, N)
    return out
