# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def repeat_dim0_2x_kernel(
    inp_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Block-copy kernel for repeat along dim 0 by factor 2.

    Loads a block from input and writes it to two locations in the output:
    out[0:N] and out[N:2N].  Uses persistent loop for good SM occupancy.
    """
    pid = ext.program_id(0)
    num_pids = ext.num_programs(0)
    offsets = tl.arange(0, BLOCK_SIZE)

    num_blocks = tl.cdiv(n_elements, BLOCK_SIZE)
    for block_id in tl.range(pid, num_blocks, num_pids):
        off = block_id * BLOCK_SIZE + offsets
        mask = off < n_elements

        val = tl.load(inp_ptr + off, mask=mask)

        tl.store(out_ptr + off, val, mask=mask)
        tl.store(out_ptr + n_elements + off, val, mask=mask)


@libentry()
@triton.jit(do_not_specialize=["n_elements"])
def repeat_dim0_3x_kernel(
    inp_ptr,
    out_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Block-copy kernel for repeat along dim 0 by factor 3."""
    pid = ext.program_id(0)
    num_pids = ext.num_programs(0)
    offsets = tl.arange(0, BLOCK_SIZE)

    num_blocks = tl.cdiv(n_elements, BLOCK_SIZE)
    for block_id in tl.range(pid, num_blocks, num_pids):
        off = block_id * BLOCK_SIZE + offsets
        mask = off < n_elements

        val = tl.load(inp_ptr + off, mask=mask)

        tl.store(out_ptr + off, val, mask=mask)
        tl.store(out_ptr + n_elements + off, val, mask=mask)
        tl.store(out_ptr + 2 * n_elements + off, val, mask=mask)


def repeat(inp, sizes):
    """Metax-optimized repeat.

    Fast path: when only dim 0 is repeated by factor 2 or 3 with all
    other dims = 1, uses a block-copy kernel that loads each input block
    once and writes it to 2 or 3 staggered output offsets.  Complex
    repeat patterns fall back to the generic code-generated kernel.
    """
    from flag_gems.ops.repeat import _repeat_func

    logger.debug("GEMS_METAX REPEAT")

    inp_ndim = inp.ndim
    sizes_rank = len(sizes)

    # Fast path: sizes == [k, 1, 1, ...] where k in (2, 3) and len(sizes) == inp.ndim.
    # This means only dim 0 is repeated (no prepended dimensions).
    is_dim0_only_2d_plus = (
        sizes_rank == inp_ndim
        and sizes_rank >= 1
        and sizes[0] in (2, 3)
        and all(s == 1 for s in sizes[1:])
    )
    # Also handle 1D: sizes = [k] where k in (2, 3)
    is_1d_simple = inp_ndim == 1 and sizes_rank == 1 and sizes[0] in (2, 3)

    if is_dim0_only_2d_plus or is_1d_simple:
        repeat0 = sizes[0]
        inp = inp.contiguous()

        out_shape = list(inp.shape)
        out_shape[0] *= repeat0

        out = torch.empty(out_shape, dtype=inp.dtype, device=inp.device)

        # Flatten for contiguous block-copy
        inp_flat = inp.reshape(-1)
        out_flat = out.reshape(-1)
        n = inp_flat.numel()

        BLOCK_SIZE = 4096
        grid = (triton.cdiv(n, BLOCK_SIZE),)
        kernel = repeat_dim0_2x_kernel if repeat0 == 2 else repeat_dim0_3x_kernel

        with torch_device_fn.device(inp.device):
            kernel[grid](
                inp_flat,
                out_flat,
                n,
                BLOCK_SIZE=BLOCK_SIZE,
                num_warps=8,
            )
        return out

    # Fall back to generic implementation
    return _repeat_func(inp, sizes)
