# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""MetaX backend override for zero/zero_/zero_out.

The common implementation uses BLOCK_SIZE=1024, generating ~1M thread
blocks for large tensors (1B elements). This causes excessive grid
launch overhead on MetaX hardware.

This override uses a persistent kernel pattern: a small fixed number
of thread blocks (256), each processing multiple chunks via a strided
loop with BLOCK_SIZE=16384. This reduces grid dispatch overhead while
maintaining full memory bandwidth utilization.
"""

import logging

import torch
import triton
import triton.language as tl

import flag_gems
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# Persistent kernel parameters tuned for MetaX GPU.
# 256 blocks with 16384 elements each covers most tensor sizes
# with minimal grid dispatch overhead.
_NUM_PROGRAMS = 256
_BLOCK_SIZE = 16384


@libentry()
@triton.jit
def zero_persistent_kernel(
    out_ptr,
    n_elements,
    NUM_PROGRAMS: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Persistent zero-fill kernel.

    Each program processes multiple chunks in a strided loop,
    reducing total grid size from O(n/BLOCK) to NUM_PROGRAMS.
    """
    pid = tl.program_id(axis=0)
    step = NUM_PROGRAMS * BLOCK_SIZE
    block_start = pid * BLOCK_SIZE

    for offset in range(block_start, n_elements, step):
        offsets = offset + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        tl.store(out_ptr + offsets, 0.0, mask=mask)


def _launch_zero(tensor: torch.Tensor) -> torch.Tensor:
    """Launch persistent zero kernel on the given tensor."""
    n_elements = tensor.numel()
    if n_elements == 0:
        return tensor

    num_programs = min(_NUM_PROGRAMS, triton.cdiv(n_elements, _BLOCK_SIZE))

    with torch_device_fn.device(tensor.device):
        zero_persistent_kernel[(num_programs,)](
            tensor,
            n_elements,
            NUM_PROGRAMS=num_programs,
            BLOCK_SIZE=_BLOCK_SIZE,
            num_warps=4,
        )
    return tensor


def zero_(x: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS_METAX ZERO_")
    assert x.is_contiguous(), "Tensor must be contiguous"
    return _launch_zero(x)


def zero(*args, **kwargs):
    logger.debug("GEMS_METAX ZERO")
    target = None
    if len(args) >= 1 and isinstance(args[0], torch.Tensor):
        target = args[0]
    elif "self" in kwargs:
        target = kwargs["self"]
    elif "input" in kwargs:
        target = kwargs["input"]
    elif "out" in kwargs:
        target = kwargs["out"]
    else:
        raise ValueError(
            "zero expects a Tensor as the first argument "
            "or in kwargs as 'self', 'input', or 'out'"
        )
    if target.device.type != flag_gems.device:
        raise ValueError(f"Tensor must be on {flag_gems.device} device")
    assert target.is_contiguous(), "Tensor must be contiguous"
    return _launch_zero(target)


def zero_out(*args, **kwargs):
    logger.debug("GEMS_METAX ZERO_OUT")
    out = None
    if "out" in kwargs and isinstance(kwargs["out"], torch.Tensor):
        out = kwargs["out"]
    elif len(args) >= 1 and isinstance(args[0], torch.Tensor):
        out = args[0]
    else:
        raise ValueError(
            "zero_out expects an output Tensor as the first "
            "positional argument or 'out' kwarg"
        )
    if out.device.type != flag_gems.device:
        raise ValueError(f"Tensor must be on {flag_gems.device} device")
    assert out.is_contiguous(), "Tensor must be contiguous"
    return _launch_zero(out)
