# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


def _extract_qparams(scale, zero_point, quant_min, quant_max):
    # scale and zero_point are single-element tensors. Extract scalar values
    # following the native aten implementation:
    #   scale_val = scale[0].item<float>()
    #   zero_point_val = clamp(nearbyint(zero_point[0]), quant_min, quant_max)
    scale_val = scale.view(-1)[0].float().item()
    # std::nearbyint uses round-half-to-even; Python's round matches it.
    zp_fp = round(float(zero_point.view(-1)[0]))
    zero_point_val = int(min(max(zp_fp, quant_min), quant_max))
    return scale_val, zero_point_val


@pointwise_dynamic(
    is_tensor=[True, False, False, False, False], promotion_methods=[(0, "DEFAULT")]
)
@triton.jit
def _fake_quantize_learnable_per_tensor_affine_kernel(
    x, scale, zero_point, quant_min, quant_max
):
    x = x.to(tl.float32)
    inv_scale = 1.0 / scale
    qval = tl_extra_shim.nearbyint(x * inv_scale).to(tl.int32) + zero_point.to(tl.int32)
    qval = tl.minimum(quant_max.to(tl.int32), tl.maximum(quant_min.to(tl.int32), qval))
    return (qval.to(tl.float32) - zero_point.to(tl.float32)) * scale


def _fake_quantize_learnable_per_tensor_affine(
    self, scale, zero_point, quant_min, quant_max, grad_factor=1.0
):
    logger.debug("GEMS FAKE_QUANTIZE_LEARNABLE_PER_TENSOR_AFFINE")
    scale_val, zero_point_val = _extract_qparams(
        scale, zero_point, quant_min, quant_max
    )
    return _fake_quantize_learnable_per_tensor_affine_kernel(
        self,
        scale_val,
        zero_point_val,
        quant_min,
        quant_max,
    )
