# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
import triton.language.extra.libdevice as libdevice

logger = logging.getLogger(__name__)


_SCALAR_TYPE_NAMES = {
    torch.float16: "Half",
    torch.bfloat16: "BFloat16",
    torch.float64: "Double",
}


@triton.jit
def _init_minmax(cmin_ptr, cmax_ptr, C, BLOCK: tl.constexpr):
    off = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    m = off < C
    tl.store(cmin_ptr + off, tl.full((BLOCK,), float("inf"), tl.float32), mask=m)
    tl.store(cmax_ptr + off, tl.full((BLOCK,), float("-inf"), tl.float32), mask=m)


@triton.jit
def _reduce_minmax(x_ptr, cmin_ptr, cmax_ptr, R, BLOCK: tl.constexpr):
    # grid = (ceil(R / BLOCK), C); each program reduces a chunk of channel c's
    # row. The row-chunk count can reach 2**20+ for large tensors, so it must be
    # grid dim 0 (limit 2**31-1); channels go on dim 1 (limit 65535).
    j = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    c = tl.program_id(1)
    m = j < R
    x = tl.load(x_ptr + c * R + j, mask=m, other=0.0).to(tl.float32)
    xmin = tl.where(m, x, float("inf"))
    xmax = tl.where(m, x, float("-inf"))
    lmin = tl.min(xmin, axis=0)
    lmax = tl.max(xmax, axis=0)
    tl.atomic_min(cmin_ptr + c, lmin)
    tl.atomic_max(cmax_ptr + c, lmax)


@triton.jit
def _qparams(
    cmin_ptr,
    cmax_ptr,
    rmin_ptr,
    rmax_ptr,
    scale_ptr,
    zp_ptr,
    C,
    avg_const,
    qmin,
    qmax,
    OBS: tl.constexpr,
    FQ: tl.constexpr,
    SYM: tl.constexpr,
    BLOCK: tl.constexpr,
):
    off = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    m = off < C
    rmin = tl.load(rmin_ptr + off, mask=m, other=0.0).to(tl.float32)
    rmax = tl.load(rmax_ptr + off, mask=m, other=0.0).to(tl.float32)

    if OBS:
        cmin = tl.load(cmin_ptr + off, mask=m, other=0.0).to(tl.float32)
        cmax = tl.load(cmax_ptr + off, mask=m, other=0.0).to(tl.float32)
        rmin = rmin + avg_const * (cmin - rmin)
        rmax = rmax + avg_const * (cmax - rmax)
        tl.store(rmin_ptr + off, rmin, mask=m)
        tl.store(rmax_ptr + off, rmax, mask=m)

    if FQ:
        qmnf = qmin.to(tl.float32)
        qmxf = qmax.to(tl.float32)
        mn = tl.minimum(rmin, 0.0)
        mx = tl.maximum(rmax, 0.0)
        # asymmetric / default branch
        sc = libdevice.div_rn(mx - mn, qmxf - qmnf)
        sc = tl.where(sc == 0.0, 0.1, sc)
        z = libdevice.rint(qmnf - libdevice.div_rn(mn, sc))
        z = tl.minimum(tl.maximum(z, qmnf), qmxf)

        both = (mn < 0.0) & (mx > 0.0)
        if SYM:
            sc_sym = tl.maximum(
                libdevice.div_rn(-mn, -qmnf), libdevice.div_rn(mx, qmxf)
            )
            sc_sym = tl.where(sc_sym == 0.0, 0.1, sc_sym)
            z_sym = libdevice.rint((qmnf + qmxf) / 2.0)
            sc = tl.where(both, sc_sym, sc)
            z = tl.where(both, z_sym, z)

        tl.store(scale_ptr + off, sc, mask=m)
        tl.store(zp_ptr + off, z.to(tl.int32), mask=m)


@triton.jit
def _fake_quant(
    x_ptr,
    out_ptr,
    mask_ptr,
    scale_ptr,
    zp_ptr,
    N,
    R,
    qmin,
    qmax,
    PER_CHANNEL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    off = tl.program_id(0) * BLOCK + tl.arange(0, BLOCK)
    m = off < N
    x = tl.load(x_ptr + off, mask=m, other=0.0).to(tl.float32)
    if PER_CHANNEL:
        c = off // R
    else:
        c = tl.zeros((BLOCK,), tl.int32)
    s = tl.load(scale_ptr + c, mask=m, other=1.0).to(tl.float32)
    z = tl.load(zp_ptr + c, mask=m, other=0).to(tl.float32)

    qmnf = qmin.to(tl.float32)
    qmxf = qmax.to(tl.float32)
    q = libdevice.rint(libdevice.div_rn(x, s)) + z
    valid = (q >= qmnf) & (q <= qmxf)
    qc = tl.minimum(tl.maximum(q, qmnf), qmxf)
    out = (qc - z) * s
    tl.store(out_ptr + off, out, mask=m)
    tl.store(mask_ptr + off, valid.to(tl.int8), mask=m)


@triton.jit
def _pt_qparam_fq(
    x_ptr,
    out_ptr,
    mask_ptr,
    cmin_ptr,
    cmax_ptr,
    rmin_in_ptr,
    rmax_in_ptr,
    rmin_out_ptr,
    rmax_out_ptr,
    scale_out_ptr,
    zp_out_ptr,
    N,
    avg_const,
    qmin,
    qmax,
    OBS: tl.constexpr,
    SYM: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Per-tensor (C == 1) fused qparam + fake-quant with SCALAR qparam compute.
    # Leaner than the generalized _fused_fq for the per-tensor case: every block
    # computes the same scalar scale/zp from read-only inputs (no vector loads,
    # no modulo scatter); block 0 persists the scalar qparam/running outputs.
    pid = tl.program_id(0)

    rmin = tl.load(rmin_in_ptr).to(tl.float32)
    rmax = tl.load(rmax_in_ptr).to(tl.float32)
    if OBS:
        cmin = tl.load(cmin_ptr).to(tl.float32)
        cmax = tl.load(cmax_ptr).to(tl.float32)
        rmin = rmin + avg_const * (cmin - rmin)
        rmax = rmax + avg_const * (cmax - rmax)

    qmnf = qmin.to(tl.float32)
    qmxf = qmax.to(tl.float32)
    mn = tl.minimum(rmin, 0.0)
    mx = tl.maximum(rmax, 0.0)
    sc = libdevice.div_rn(mx - mn, qmxf - qmnf)
    sc = tl.where(sc == 0.0, 0.1, sc)
    z = libdevice.rint(qmnf - libdevice.div_rn(mn, sc))
    z = tl.minimum(tl.maximum(z, qmnf), qmxf)
    if SYM:
        both = (mn < 0.0) & (mx > 0.0)
        sc_sym = tl.maximum(libdevice.div_rn(-mn, -qmnf), libdevice.div_rn(mx, qmxf))
        sc_sym = tl.where(sc_sym == 0.0, 0.1, sc_sym)
        z_sym = libdevice.rint((qmnf + qmxf) / 2.0)
        sc = tl.where(both, sc_sym, sc)
        z = tl.where(both, z_sym, z)

    if pid == 0:
        if OBS:
            tl.store(rmin_out_ptr, rmin)
            tl.store(rmax_out_ptr, rmax)
        tl.store(scale_out_ptr, sc)
        tl.store(zp_out_ptr, z.to(tl.int32))

    off = pid * BLOCK + tl.arange(0, BLOCK)
    m = off < N
    x = tl.load(x_ptr + off, mask=m, other=0.0).to(tl.float32)
    q = libdevice.rint(libdevice.div_rn(x, sc)) + z
    valid = (q >= qmnf) & (q <= qmxf)
    qc = tl.minimum(tl.maximum(q, qmnf), qmxf)
    out = (qc - z) * sc
    tl.store(out_ptr + off, out, mask=m)
    tl.store(mask_ptr + off, valid.to(tl.int8), mask=m)


@triton.jit
def _fused_fq(
    x_ptr,
    out_ptr,
    mask_ptr,
    cmin_ptr,
    cmax_ptr,
    rmin_in_ptr,
    rmax_in_ptr,
    rmin_out_ptr,
    rmax_out_ptr,
    scale_out_ptr,
    zp_out_ptr,
    N,
    R,
    avg_const,
    qmin,
    qmax,
    OBS: tl.constexpr,
    SYM: tl.constexpr,
    PER_CHANNEL: tl.constexpr,
    BLOCK: tl.constexpr,
):
    # Fused qparam + fake-quant. Every lane recomputes scale/zp for its channel
    # from READ-ONLY inputs (rmin_in/rmax_in + cmin/cmax), so there is no
    # cross-block RAW hazard. Each channel's qparam / running-stat output is
    # written exactly once, by the lane holding that channel's first element
    # (off % R == 0). This removes the separate _qparams launch.
    pid = tl.program_id(0)
    off = pid * BLOCK + tl.arange(0, BLOCK)
    m = off < N
    if PER_CHANNEL:
        c = off // R
    else:
        c = tl.zeros((BLOCK,), tl.int32)

    rmin = tl.load(rmin_in_ptr + c, mask=m, other=0.0).to(tl.float32)
    rmax = tl.load(rmax_in_ptr + c, mask=m, other=0.0).to(tl.float32)
    if OBS:
        cmin = tl.load(cmin_ptr + c, mask=m, other=0.0).to(tl.float32)
        cmax = tl.load(cmax_ptr + c, mask=m, other=0.0).to(tl.float32)
        rmin = rmin + avg_const * (cmin - rmin)
        rmax = rmax + avg_const * (cmax - rmax)

    qmnf = qmin.to(tl.float32)
    qmxf = qmax.to(tl.float32)
    mn = tl.minimum(rmin, 0.0)
    mx = tl.maximum(rmax, 0.0)
    sc = libdevice.div_rn(mx - mn, qmxf - qmnf)
    sc = tl.where(sc == 0.0, 0.1, sc)
    z = libdevice.rint(qmnf - libdevice.div_rn(mn, sc))
    z = tl.minimum(tl.maximum(z, qmnf), qmxf)
    if SYM:
        both = (mn < 0.0) & (mx > 0.0)
        sc_sym = tl.maximum(libdevice.div_rn(-mn, -qmnf), libdevice.div_rn(mx, qmxf))
        sc_sym = tl.where(sc_sym == 0.0, 0.1, sc_sym)
        z_sym = libdevice.rint((qmnf + qmxf) / 2.0)
        sc = tl.where(both, sc_sym, sc)
        z = tl.where(both, z_sym, z)

    # Persist qparam / running per channel exactly once (first element of chan).
    gate = m & ((off % R) == 0)
    if OBS:
        tl.store(rmin_out_ptr + c, rmin, mask=gate)
        tl.store(rmax_out_ptr + c, rmax, mask=gate)
    tl.store(scale_out_ptr + c, sc, mask=gate)
    tl.store(zp_out_ptr + c, z.to(tl.int32), mask=gate)

    x = tl.load(x_ptr + off, mask=m, other=0.0).to(tl.float32)
    q = libdevice.rint(libdevice.div_rn(x, sc)) + z
    valid = (q >= qmnf) & (q <= qmxf)
    qc = tl.minimum(tl.maximum(q, qmnf), qmxf)
    out = (qc - z) * sc
    tl.store(out_ptr + off, out, mask=m)
    tl.store(mask_ptr + off, valid.to(tl.int8), mask=m)


def _fused_moving_avg_obs_fq_helper(
    self,
    observer_on,
    fake_quant_on,
    running_min,
    running_max,
    scale,
    zero_point,
    averaging_const,
    quant_min,
    quant_max,
    ch_axis,
    per_row_fake_quant=False,
    symmetric_quant=False,
):
    """Fused moving-average observer + fake-quantize helper (QAT).

    Matches aten._fused_moving_avg_obs_fq_helper: updates running_min/max in
    place by moving average, recomputes scale/zero_point, and fake-quantizes
    the input. Supports per-tensor and per-channel (per_row_fake_quant) modes.
    Returns (output, mask); running_min/max/scale/zero_point are updated in
    place to match the native op's mutating contract.
    """
    logger.debug("GEMS _FUSED_MOVING_AVG_OBS_FQ_HELPER")
    # The native ATen operator is intentionally restricted to float32 input.
    # Keep this check at the dispatch boundary instead of silently converting
    # unsupported inputs, which would make FlagGems diverge from ATen.
    if self.dtype is not torch.float32:
        scalar_type = _SCALAR_TYPE_NAMES.get(self.dtype, str(self.dtype))
        raise RuntimeError(f"expected scalar type Float but found {scalar_type}")

    x = self
    dev = x.device
    obs = int(observer_on)
    fq = int(fake_quant_on)
    sym = bool(symmetric_quant)
    pc = bool(per_row_fake_quant)
    qmin = int(quant_min)
    qmax = int(quant_max)
    ac = float(averaging_const)

    N = x.numel()
    xf = x.contiguous().view(-1)

    if pc:
        C = x.shape[int(ch_axis)]
        R = N // C
    else:
        C = 1
        R = N

    out = torch.empty_like(xf, dtype=torch.float32)
    mask_b = torch.empty(N, dtype=torch.bool, device=dev)

    # Fused fake-quant-on path: single launch for qparam + fake-quant (removes
    # the separate _qparams launch) for BOTH per-tensor and per-channel. Each
    # lane recomputes its channel's scale/zp from read-only inputs; the lane at
    # each channel's first element persists that channel's qparam/running stats.
    if fq:
        rmin_in = running_min.to(torch.float32)
        rmax_in = running_max.to(torch.float32)
        # Separate output buffers so cross-block reads of rmin_in/rmax_in never
        # race with the running-stat writes.
        rmin_out = torch.empty(C, dtype=torch.float32, device=dev)
        rmax_out = torch.empty(C, dtype=torch.float32, device=dev)
        if obs:
            # Allocate cmin/cmax pre-filled with +/-inf (tensor creation, not a
            # kernel launch), then reduce; removes the _init_minmax launch.
            cmin = torch.full((C,), float("inf"), dtype=torch.float32, device=dev)
            cmax = torch.full((C,), float("-inf"), dtype=torch.float32, device=dev)
            BLK_R = 1024
            _reduce_minmax[(triton.cdiv(R, BLK_R), C)](xf, cmin, cmax, R, BLOCK=BLK_R)
        else:
            cmin = rmin_in
            cmax = rmax_in
        BLK = 1024
        if pc:
            _fused_fq[(triton.cdiv(N, BLK),)](
                xf,
                out,
                mask_b,
                cmin,
                cmax,
                rmin_in,
                rmax_in,
                rmin_out,
                rmax_out,
                scale,
                zero_point,
                N,
                R,
                ac,
                qmin,
                qmax,
                OBS=obs,
                SYM=sym,
                PER_CHANNEL=True,
                BLOCK=BLK,
            )
        else:
            _pt_qparam_fq[(triton.cdiv(N, BLK),)](
                xf,
                out,
                mask_b,
                cmin,
                cmax,
                rmin_in,
                rmax_in,
                rmin_out,
                rmax_out,
                scale,
                zero_point,
                N,
                ac,
                qmin,
                qmax,
                OBS=obs,
                SYM=sym,
                BLOCK=BLK,
            )
        if obs:
            running_min.copy_(rmin_out)
            running_max.copy_(rmax_out)
        out_t = out.view(x.shape)
        mask_t = mask_b.view(x.shape)
        return (out_t, mask_t)

    # fake-quant-off path: still update running stats via the qparam kernel.
    # Phase 1: per-channel min/max reduction (only needed if observer on)
    if obs:
        cmin = torch.empty(C, dtype=torch.float32, device=dev)
        cmax = torch.empty(C, dtype=torch.float32, device=dev)
        BLK_C = 128
        _init_minmax[(triton.cdiv(C, BLK_C),)](cmin, cmax, C, BLOCK=BLK_C)
        BLK_R = 1024
        grid_r = (triton.cdiv(R, BLK_R), C)
        _reduce_minmax[grid_r](xf, cmin, cmax, R, BLOCK=BLK_R)
    else:
        cmin = running_min
        cmax = running_max

    # Phase 2: qparam update (mutates running_min/max in place)
    BLK_Q = 128
    _qparams[(triton.cdiv(C, BLK_Q),)](
        cmin,
        cmax,
        running_min,
        running_max,
        scale,
        zero_point,
        C,
        ac,
        qmin,
        qmax,
        OBS=obs,
        FQ=fq,
        SYM=sym,
        BLOCK=BLK_Q,
    )

    # fake-quant off: output is identity, mask is all-true.
    out_t = xf.to(torch.float32).view(x.shape)
    mask_t = torch.ones(x.shape, dtype=torch.bool, device=dev)
    return (out_t, mask_t)
