# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _sdpa_math_kernel(
    Q,
    K,
    V,
    ATTN_MASK,
    Out,
    Weights,
    sm_scale,
    stride_qz,
    stride_qm,
    stride_qk,
    stride_kz,
    stride_kn,
    stride_kk,
    stride_vz,
    stride_vn,
    stride_vk,
    stride_mz,
    stride_mm,
    stride_mn,
    stride_oz,
    stride_om,
    stride_ok,
    stride_wz,
    stride_wm,
    stride_wn,
    Q_CTX,
    KV_CTX,
    HEAD_DIM: tl.constexpr,
    BLOCK_D: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    IS_CAUSAL: tl.constexpr,
    HAS_ATTN_MASK: tl.constexpr,
):
    start_m = tl.program_id(0)
    off_z = tl.program_id(1)

    q_base = Q + off_z * stride_qz
    k_base = K + off_z * stride_kz
    v_base = V + off_z * stride_vz
    o_base = Out + off_z * stride_oz
    w_base = Weights + off_z * stride_wz

    offs_m = start_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_d = tl.arange(0, BLOCK_D)
    d_mask = offs_d < HEAD_DIM

    q_mask = offs_m < Q_CTX
    q_ptrs = q_base + offs_m[:, None] * stride_qm + offs_d[None, :] * stride_qk
    # Keep Q/K/V in their native dtype so tl.dot uses tensor cores; only the
    # softmax statistics and accumulators run in fp32.
    query = tl.load(q_ptrs, mask=q_mask[:, None] & d_mask[None, :], other=0.0)

    LOG2E: tl.constexpr = 1.4426950408889634

    m_i = tl.full([BLOCK_M], -float("inf"), dtype=tl.float32)
    l_i = tl.zeros([BLOCK_M], dtype=tl.float32)
    acc = tl.zeros([BLOCK_M, BLOCK_D], dtype=tl.float32)

    if IS_CAUSAL:
        # Top-left causal masking: query row i attends to key j when j <= i,
        # matching torch's tril(diagonal=0) in the math reference.
        hi = tl.minimum((start_m + 1) * BLOCK_M, KV_CTX)
    else:
        hi = KV_CTX

    # Pass 1: online softmax to compute row max (m_i), row sum (l_i) and the
    # unnormalized output accumulator in a single streaming loop.
    for start_n in range(0, hi, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        kv_mask = offs_n < KV_CTX

        k_ptrs = k_base + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kk
        key = tl.load(k_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)

        qk = tl.dot(query, tl.trans(key)).to(tl.float32) * sm_scale

        if HAS_ATTN_MASK:
            m_ptrs = (
                ATTN_MASK
                + off_z * stride_mz
                + offs_m[:, None] * stride_mm
                + offs_n[None, :] * stride_mn
            )
            load_mask = q_mask[:, None] & kv_mask[None, :]
            add_mask = tl.load(m_ptrs, mask=load_mask, other=0.0).to(tl.float32)
            qk += add_mask

        qk = tl.where(kv_mask[None, :], qk, -float("inf"))

        if IS_CAUSAL:
            causal = offs_m[:, None] >= offs_n[None, :]
            qk = tl.where(causal, qk, -float("inf"))

        m_ij = tl.maximum(m_i, tl.max(qk, 1))
        m_ij_safe = tl.where(m_ij == -float("inf"), 0.0, m_ij)
        p = tl.exp2((qk - m_ij_safe[:, None]) * LOG2E)
        alpha = tl.exp2((m_i - m_ij_safe) * LOG2E)
        l_i = l_i * alpha + tl.sum(p, 1)

        v_ptrs = v_base + offs_n[:, None] * stride_vn + offs_d[None, :] * stride_vk
        value = tl.load(v_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)

        acc = acc * alpha[:, None]
        acc += tl.dot(p.to(value.dtype), value).to(tl.float32)
        m_i = m_ij_safe

    l_safe = tl.where(l_i == 0.0, 1.0, l_i)
    acc = acc / l_safe[:, None]

    o_ptrs = o_base + offs_m[:, None] * stride_om + offs_d[None, :] * stride_ok
    tl.store(
        o_ptrs, acc.to(Out.dtype.element_ty), mask=q_mask[:, None] & d_mask[None, :]
    )

    # Pass 2: recompute normalized probabilities with the finalized m_i / l_i
    # and materialize the full (Q_CTX, KV_CTX) attention weight matrix.
    for start_n in range(0, KV_CTX, BLOCK_N):
        offs_n = start_n + tl.arange(0, BLOCK_N)
        kv_mask = offs_n < KV_CTX

        k_ptrs = k_base + offs_n[:, None] * stride_kn + offs_d[None, :] * stride_kk
        key = tl.load(k_ptrs, mask=kv_mask[:, None] & d_mask[None, :], other=0.0)
        qk = tl.dot(query, tl.trans(key)).to(tl.float32) * sm_scale

        if HAS_ATTN_MASK:
            m_ptrs = (
                ATTN_MASK
                + off_z * stride_mz
                + offs_m[:, None] * stride_mm
                + offs_n[None, :] * stride_mn
            )
            load_mask = q_mask[:, None] & kv_mask[None, :]
            add_mask = tl.load(m_ptrs, mask=load_mask, other=0.0).to(tl.float32)
            qk += add_mask

        keep = kv_mask[None, :]
        if IS_CAUSAL:
            causal = offs_m[:, None] >= offs_n[None, :]
            keep = keep & causal

        p = tl.exp2((qk - m_i[:, None]) * LOG2E)
        p = tl.where(keep, p, 0.0) / l_safe[:, None]

        w_ptrs = w_base + offs_m[:, None] * stride_wm + offs_n[None, :] * stride_wn
        store_mask = q_mask[:, None] & kv_mask[None, :]
        tl.store(w_ptrs, p.to(Weights.dtype.element_ty), mask=store_mask)


def _scaled_dot_product_attention_math(
    query,
    key,
    value,
    attn_mask=None,
    dropout_p=0.0,
    is_causal=False,
    scale=None,
):
    """Computes scaled dot-product attention with an explicit softmax and
    returns both the attention output and the full attention weight matrix."""
    logger.debug("GEMS _SCALED_DOT_PRODUCT_ATTENTION_MATH")

    assert dropout_p == 0.0, "dropout_p != 0.0 is not supported"
    assert query.dim() == 4, "expected 4D (batch, heads, seq_len, head_dim) tensors"

    batch, heads, q_seq_len, head_dim = query.shape
    kv_seq_len = key.shape[2]

    if scale is None:
        scale = 1.0 / math.sqrt(head_dim)

    query = query.contiguous()
    key = key.contiguous()
    value = value.contiguous()

    out = torch.empty_like(query)
    weights = torch.empty(
        (batch, heads, q_seq_len, kv_seq_len),
        dtype=query.dtype,
        device=query.device,
    )

    # Fold (batch, heads) into one grid axis; contiguous reshape gives a clean
    # per-(b, h) leading stride for pointer arithmetic in the kernel.
    q2 = query.reshape(batch * heads, q_seq_len, head_dim)
    k2 = key.reshape(batch * heads, kv_seq_len, head_dim)
    v2 = value.reshape(batch * heads, kv_seq_len, head_dim)
    o2 = out.reshape(batch * heads, q_seq_len, head_dim)
    w2 = weights.reshape(batch * heads, q_seq_len, kv_seq_len)

    has_attn_mask = attn_mask is not None
    if has_attn_mask:
        assert attn_mask.dtype != torch.bool, "boolean attn_mask is not supported"
        # Broadcast the mask to (batch, heads, q, kv) then fold like the rest.
        attn_mask = attn_mask.expand(batch, heads, q_seq_len, kv_seq_len).contiguous()
        am2 = attn_mask.reshape(batch * heads, q_seq_len, kv_seq_len)
        m_strides = (am2.stride(0), am2.stride(1), am2.stride(2))
    else:
        am2 = query  # unused placeholder; HAS_ATTN_MASK guards all accesses
        m_strides = (0, 0, 0)

    # BLOCK_M/BLOCK_N = 32 to stay within shared memory limits (166KB on T4/A10).
    # The two-pass algorithm (forward + materialize weights) requires ~2x memory
    # vs. a single-pass kernel, so smaller blocks are necessary.
    BLOCK_M = 32
    BLOCK_N = 32
    # tl.arange over the head dim requires a power-of-2 span; pad and mask.
    BLOCK_D = triton.next_power_of_2(head_dim)

    grid = (triton.cdiv(q_seq_len, BLOCK_M), batch * heads)

    with torch_device_fn.device(query.device):
        _sdpa_math_kernel[grid](
            q2,
            k2,
            v2,
            am2,
            o2,
            w2,
            scale,
            q2.stride(0),
            q2.stride(1),
            q2.stride(2),
            k2.stride(0),
            k2.stride(1),
            k2.stride(2),
            v2.stride(0),
            v2.stride(1),
            v2.stride(2),
            m_strides[0],
            m_strides[1],
            m_strides[2],
            o2.stride(0),
            o2.stride(1),
            o2.stride(2),
            w2.stride(0),
            w2.stride(1),
            w2.stride(2),
            q_seq_len,
            kv_seq_len,
            HEAD_DIM=head_dim,
            BLOCK_D=BLOCK_D,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
            IS_CAUSAL=is_causal,
            HAS_ATTN_MASK=has_attn_mask,
        )

    return out, weights
