# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch

from flag_gems.ops.attention import scaled_dot_product_attention_forward

logger = logging.getLogger(__name__)


def cudnn_attention_forward(
    query,
    key,
    value,
    attn_bias,
    cum_seq_q,
    cum_seq_k,
    max_q,
    max_k,
    compute_log_sumexp,
    dropout_p=0.0,
    is_causal=False,
    return_debug_mask=False,
    *,
    scale=None,
):
    """Forward kernel for cuDNN attention -- BHSD-native path.

    Computes the cuDNN-style scaled dot-product attention forward pass.
    Inputs and outputs are in BHSD (batch, heads, seq, dim) layout.

    The attention output and log-sum-exp are computed via
    ``scaled_dot_product_attention_forward`` (Triton FlashAttention-2).
    The kernel tracks online-softmax state in log2 scale (``M * log(2)``
    recovers the natural-log LSE), so the O(N^2) post-processing matmul
    used in earlier versions is eliminated.
    """
    logger.debug("GEMS CUDNN_ATTENTION_FORWARD")

    if dropout_p > 0.0:
        raise NotImplementedError(
            "cudnn_attention_forward: dropout > 0 is not yet supported"
        )

    if cum_seq_q is not None or cum_seq_k is not None:
        raise NotImplementedError(
            "cudnn_attention_forward: varlen is not yet supported"
        )

    out, m_log2 = scaled_dot_product_attention_forward(
        query,
        key,
        value,
        attn_mask=attn_bias,
        dropout_p=dropout_p,
        is_causal=is_causal,
        scale=scale,
    )

    # M is the online-softmax accumulator in log2 scale
    # (the kernel uses exp2 / LOG2E internally).
    # Convert to natural-log LSE:  LSE_nat = M * ln(2).
    if compute_log_sumexp:
        lse = m_log2.float() * math.log(2)  # [B, H, S_q]
    else:
        lse = torch.zeros(
            query.shape[0],
            query.shape[1],
            query.shape[2],
            device=query.device,
            dtype=torch.float32,
        )

    # cuDNN convention: logsumexp shape is [B, H, S_q, 1]
    lse = lse.unsqueeze(-1)

    # Philox seed / offset: the Triton kernel does not produce these
    # (dropout is not supported), so return scalar zero tensors.
    zero_seed = torch.zeros([], device=query.device, dtype=torch.int64)
    zero_offset = torch.zeros([], device=query.device, dtype=torch.int64)

    # debug_attn_mask is not computed; return an empty tensor.
    debug_mask = torch.zeros([0], device=query.device, dtype=query.dtype)

    return (
        out,
        lse,
        cum_seq_q,
        cum_seq_k,
        max_q,
        max_k,
        zero_seed,
        zero_offset,
        debug_mask,
    )
