# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.cumsum import cumsum_wrapper

logger = logging.getLogger(__name__)


def cumsum_(inp, dim, *, dtype=None):
    logger.debug("GEMS CUMSUM_")
    if dtype is not None and dtype != inp.dtype:
        raise RuntimeError(
            "Bad in-place call: input tensor dtype and output tensor dtype should match"
        )
    assert inp.dtype in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.int16,
        torch.int32,
    ), f"cumsum_ only supports float/int dtypes, got {inp.dtype}"
    result = cumsum_wrapper(inp, dim, dtype)
    inp.copy_(result)
    return inp
