# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as tle
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)


@triton.jit
def empty_permuted_kernel(
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Touches the freshly allocated storage.

    `empty_permuted` returns uninitialized memory, so no meaningful value has to
    be produced. The permuted layout is non-overlapping and dense, therefore the
    storage can be walked linearly.
    """
    pid = tle.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    tl.store(output_ptr + offsets, 0.0, mask=mask)


def _strides_from_physical_layout(size, physical_layout):
    """Derives strides from a physical layout.

    `physical_layout` lists the logical dimensions ordered from the outermost to
    the innermost physical dimension, so walking it backwards and accumulating
    the sizes yields the stride of each logical dimension.
    """
    strides = [0] * len(size)
    accumulated = 1
    for dim in reversed(physical_layout):
        strides[dim] = accumulated
        accumulated *= size[dim]
    return strides


def empty_permuted(
    size,
    physical_layout,
    *,
    dtype=None,
    layout=None,
    device=None,
    pin_memory=None,
):
    """Returns an uninitialized tensor whose memory follows `physical_layout`."""
    logger.debug("GEMS EMPTY_PERMUTED")
    shape = tuple(size)
    physical_layout = list(physical_layout)
    if len(physical_layout) != len(shape):
        raise RuntimeError(
            f"empty_permuted: physical_layout must have the same length as size, "
            f"but got {len(physical_layout)} and {len(shape)}"
        )
    if sorted(physical_layout) != list(range(len(shape))):
        raise RuntimeError(
            f"empty_permuted: physical_layout must be a permutation of "
            f"[0, {len(shape)}), but got {physical_layout}"
        )

    if dtype is None:
        dtype = torch.get_default_dtype()
    if device is None:
        import flag_gems.runtime as _rt

        device = torch.device(_rt.device.name)
    if layout is None:
        layout = torch.strided
    if pin_memory is None:
        pin_memory = False

    # Allocate via empty_strided instead of torch.empty to avoid self-recursion
    # through aten::empty.memory_format, which flag_gems also overrides.
    out = torch.empty_strided(
        shape,
        _strides_from_physical_layout(shape, physical_layout),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )
    N = volume(shape)
    if N == 0:
        return out
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(device):
        empty_permuted_kernel[grid_fn](out, N, BLOCK_SIZE=1024)
    return out
