# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from flag_gems.ops.copy import copy_

logger = logging.getLogger(__name__)


def expand_copy(x: torch.Tensor, size) -> torch.Tensor:
    """
    Wrapper for aten::expand_copy
    Creates and returns a copy of x with the given size, broadcasting as needed.
    """
    logger.debug("GEMS EXPAND_COPY")

    # Convert size to tuple and handle -1 (meaning keep original size)
    size_tuple = tuple(-1 if s is None else s for s in size)

    # Ensure input is on the correct device
    device = x.device

    # Create output tensor with target shape on the same device
    out = torch.empty(size_tuple, dtype=x.dtype, device=device)

    # Handle empty tensors
    if out.numel() == 0:
        return out

    # Use torch.expand to get a broadcasted view with correct strides
    expanded_src = x.expand(size_tuple)

    # Ensure expanded_src is on the right device (expand preserves device)
    if expanded_src.device != device:
        expanded_src = expanded_src.to(device)

    # Use FlagGems copy_ which properly handles broadcasting
    return copy_(out, expanded_src)
