# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _fix_inplace_kernel(x_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)

    # Upcast to fp32 for stable math, then cast back to input dtype.
    # Truncation toward zero: floor for x >= 0, ceil for x < 0.
    x_fp32 = x.to(tl.float32)
    res_pos = tl.floor(x_fp32)
    res_neg = tl.ceil(x_fp32)
    res_fp32 = tl.where(x_fp32 >= 0, res_pos, res_neg)
    res = res_fp32.to(x.dtype)

    tl.store(x_ptr + offsets, res, mask=mask)


def fix_(self: torch.Tensor):
    """
    Wrapper for ATen operator: ('fix_', <Autograd.disable: False>)
    In-place truncation toward zero for floating tensors.
    Integer tensors are left unchanged (no-op).
    """
    logger.debug("GEMS FIX_")

    if self.is_complex():
        # Fallback for complex dtypes not supported by Triton.
        self.copy_(torch.trunc(self))
        return self

    # Integer tensors: truncation is a no-op.
    if not self.is_floating_point():
        return self

    n_elements = self.numel()
    if n_elements == 0:
        return self

    x_contig = self.contiguous()

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(self.device):
        _fix_inplace_kernel[grid](x_contig, n_elements, BLOCK_SIZE=1024)

    # If the input was non-contiguous, write results back into it.
    if x_contig is not self:
        self.copy_(x_contig)

    return self
