# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@triton.jit
def compute_source_index(
    coord, size, padding_mode: tl.constexpr, align_corners: tl.constexpr
):
    """Map normalized coordinate [-1, 1] to source index."""
    if align_corners:
        idx = (coord + 1.0) * 0.5 * (size - 1)
    else:
        idx = ((coord + 1.0) * size - 1.0) * 0.5
    return idx


@triton.jit
def compute_source_index_grad(size, align_corners: tl.constexpr):
    """Gradient of the coordinate mapping (d(idx)/d(coord))."""
    if align_corners:
        return 0.5 * (size - 1)
    else:
        return 0.5 * size


@triton.jit
def clip_coord(coord, size):
    """Clip coordinate to [0, size - 1]."""
    return tl.minimum(tl.maximum(coord, 0.0), size - 1.0)


@triton.jit
def clip_coord_grad(coord, size):
    """Gradient multiplier for clipping."""
    return tl.where((coord >= 0.0) & (coord <= size - 1.0), 1.0, 0.0)


@triton.jit
def reflect_coord(coord, size, align_corners: tl.constexpr):
    """Reflect coordinate using PyTorch's formula.

    For align_corners=True: reflects in [0, size-1]
    For align_corners=False: reflects in [-0.5, size-0.5]
    """
    if align_corners:
        # min=0, span=size-1
        # result = span - |fabs(coord) - span|
        span = size - 1.0
        coord = tl.abs(coord)
        coord = coord - span
        coord = span - tl.abs(coord)
    else:
        # min=-0.5, span=size
        # result = span - |fabs(coord + 0.5) - span| - 0.5
        span = size * 1.0
        coord = tl.abs(coord + 0.5)
        coord = coord - span
        coord = span - tl.abs(coord)
        coord = coord - 0.5
    return coord


@triton.jit
def apply_padding(coord, size, padding_mode: tl.constexpr, align_corners: tl.constexpr):
    """Apply padding mode to coordinate and return (clamped_coord, in_bounds_mask)."""
    if padding_mode == 0:  # zeros
        in_bounds = (coord >= 0.0) & (coord < size)
        return coord, in_bounds
    elif padding_mode == 1:  # border
        coord = clip_coord(coord, size)
        return coord, tl.full(coord.shape, 1, dtype=tl.int1)
    else:  # reflection
        coord = reflect_coord(coord, size, align_corners)
        return coord, tl.full(coord.shape, 1, dtype=tl.int1)


@triton.jit
def get_padding_grad_mult(
    coord_raw, size, padding_mode: tl.constexpr, align_corners: tl.constexpr
):
    """Get gradient multiplier for padding mode.

    For reflection, this is the product of:
    1. reflect gradient: -sign(v) * sign(u)
    2. clip gradient: 1 if reflected value in [0, size-1], else 0
    """
    if padding_mode == 0:  # zeros
        return tl.where((coord_raw >= -0.5) & (coord_raw < size - 0.5), 1.0, 0.0)
    elif padding_mode == 1:  # border
        return clip_coord_grad(coord_raw, size)
    else:  # reflection
        # Step 1: gradient of reflection
        if align_corners:
            u = coord_raw
            abs_u = tl.abs(u)
            v = abs_u - (size - 1.0)
        else:
            u = coord_raw + 0.5
            abs_u = tl.abs(u)
            v = abs_u - size * 1.0
        sign_u = tl.where(u >= 0.0, 1.0, -1.0)
        sign_v = tl.where(v >= 0.0, 1.0, -1.0)
        reflect_grad = -sign_v * sign_u

        # Step 2: compute reflected coordinate for clip gradient
        reflected = reflect_coord(coord_raw, size, align_corners)
        clip_grad = clip_coord_grad(reflected, size)

        return reflect_grad * clip_grad


@libentry()
@triton.jit
def grid_sampler_3d_backward_kernel(
    # Pointers
    grad_output_ptr,
    input_ptr,
    grid_ptr,
    grad_input_ptr,
    grad_grid_ptr,
    # Shapes
    N,
    C,
    iD,
    iH,
    iW,
    oD,
    oH,
    oW,
    # Strides for grad_output (N, C, oD, oH, oW)
    go_sN,
    go_sC,
    go_sD,
    go_sH,
    go_sW,
    # Strides for input (N, C, iD, iH, iW)
    inp_sN,
    inp_sC,
    inp_sD,
    inp_sH,
    inp_sW,
    # Strides for grid (N, oD, oH, oW, 3)
    grid_sN,
    grid_sD,
    grid_sH,
    grid_sW,
    # Strides for grad_input (N, C, iD, iH, iW)
    gi_sN,
    gi_sC,
    gi_sD,
    gi_sH,
    gi_sW,
    # Strides for grad_grid (N, oD, oH, oW, 3)
    gg_sN,
    gg_sD,
    gg_sH,
    gg_sW,
    # Parameters
    num_elements,
    interpolation_mode: tl.constexpr,
    padding_mode: tl.constexpr,
    align_corners: tl.constexpr,
    need_grad_input: tl.constexpr,
    need_grad_grid: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < num_elements

    # Decompose linear index into (n, od, oh, ow)
    ow = offsets % oW
    tmp = offsets // oW
    oh = tmp % oH
    tmp2 = tmp // oH
    od = tmp2 % oD
    n = tmp2 // oD

    # Load grid coordinates (x, y, z)
    grid_base = n * grid_sN + od * grid_sD + oh * grid_sH + ow * grid_sW
    gx = tl.load(grid_ptr + grid_base, mask=mask, other=0.0)
    gy = tl.load(grid_ptr + grid_base + 1, mask=mask, other=0.0)
    gz = tl.load(grid_ptr + grid_base + 2, mask=mask, other=0.0)

    # Compute source indices
    ix = compute_source_index(gx, iW, padding_mode, align_corners)
    iy = compute_source_index(gy, iH, padding_mode, align_corners)
    iz = compute_source_index(gz, iD, padding_mode, align_corners)

    # Gradient multiplier for coordinate mapping
    if need_grad_grid:
        gx_mult = compute_source_index_grad(iW, align_corners).to(tl.float32)
        gy_mult = compute_source_index_grad(iH, align_corners).to(tl.float32)
        gz_mult = compute_source_index_grad(iD, align_corners).to(tl.float32)

        # Padding gradient multiplier
        if padding_mode == 1:  # border
            px_mult = clip_coord_grad(ix, iW)
            py_mult = clip_coord_grad(iy, iH)
            pz_mult = clip_coord_grad(iz, iD)
        elif padding_mode == 2:  # reflection
            px_mult = get_padding_grad_mult(ix, iW, padding_mode, align_corners)
            py_mult = get_padding_grad_mult(iy, iH, padding_mode, align_corners)
            pz_mult = get_padding_grad_mult(iz, iD, padding_mode, align_corners)
        else:
            px_mult = tl.full([BLOCK_SIZE], 1.0, dtype=tl.float32)
            py_mult = tl.full([BLOCK_SIZE], 1.0, dtype=tl.float32)
            pz_mult = tl.full([BLOCK_SIZE], 1.0, dtype=tl.float32)

    # Apply padding to get safe indices
    if padding_mode == 1:  # border
        ix = clip_coord(ix, iW)
        iy = clip_coord(iy, iH)
        iz = clip_coord(iz, iD)
    elif padding_mode == 2:  # reflection
        ix = reflect_coord(ix, iW, align_corners)
        iy = reflect_coord(iy, iH, align_corners)
        iz = reflect_coord(iz, iD, align_corners)
        # PyTorch clips after reflection to ensure [0, size-1]
        ix = clip_coord(ix, iW)
        iy = clip_coord(iy, iH)
        iz = clip_coord(iz, iD)

    if interpolation_mode == 0:  # bilinear
        # Floor and ceil indices
        ix0 = tl.floor(ix).to(tl.int32)
        iy0 = tl.floor(iy).to(tl.int32)
        iz0 = tl.floor(iz).to(tl.int32)
        ix1 = ix0 + 1
        iy1 = iy0 + 1
        iz1 = iz0 + 1

        # Fractional parts (trilinear weights)
        tx = ix - ix0.to(tl.float32)
        ty = iy - iy0.to(tl.float32)
        tz = iz - iz0.to(tl.float32)

        # 8 trilinear weights
        w000 = (1.0 - tx) * (1.0 - ty) * (1.0 - tz)
        w001 = (1.0 - tx) * (1.0 - ty) * tz
        w010 = (1.0 - tx) * ty * (1.0 - tz)
        w011 = (1.0 - tx) * ty * tz
        w100 = tx * (1.0 - ty) * (1.0 - tz)
        w101 = tx * (1.0 - ty) * tz
        w110 = tx * ty * (1.0 - tz)
        w111 = tx * ty * tz

        # Bounds check for zeros padding (inline since Triton JIT doesn't support nested def)
        v000 = (
            (ix0 >= 0)
            & (ix0 < iW)
            & (iy0 >= 0)
            & (iy0 < iH)
            & (iz0 >= 0)
            & (iz0 < iD)
            & mask
        )
        v001 = (
            (ix0 >= 0)
            & (ix0 < iW)
            & (iy0 >= 0)
            & (iy0 < iH)
            & (iz1 >= 0)
            & (iz1 < iD)
            & mask
        )
        v010 = (
            (ix0 >= 0)
            & (ix0 < iW)
            & (iy1 >= 0)
            & (iy1 < iH)
            & (iz0 >= 0)
            & (iz0 < iD)
            & mask
        )
        v011 = (
            (ix0 >= 0)
            & (ix0 < iW)
            & (iy1 >= 0)
            & (iy1 < iH)
            & (iz1 >= 0)
            & (iz1 < iD)
            & mask
        )
        v100 = (
            (ix1 >= 0)
            & (ix1 < iW)
            & (iy0 >= 0)
            & (iy0 < iH)
            & (iz0 >= 0)
            & (iz0 < iD)
            & mask
        )
        v101 = (
            (ix1 >= 0)
            & (ix1 < iW)
            & (iy0 >= 0)
            & (iy0 < iH)
            & (iz1 >= 0)
            & (iz1 < iD)
            & mask
        )
        v110 = (
            (ix1 >= 0)
            & (ix1 < iW)
            & (iy1 >= 0)
            & (iy1 < iH)
            & (iz0 >= 0)
            & (iz0 < iD)
            & mask
        )
        v111 = (
            (ix1 >= 0)
            & (ix1 < iW)
            & (iy1 >= 0)
            & (iy1 < iH)
            & (iz1 >= 0)
            & (iz1 < iD)
            & mask
        )

        # Clamp indices to valid range for safe address computation
        # (mask will prevent actual read/write for out-of-bounds points)
        ix0_safe = tl.maximum(tl.minimum(ix0, iW - 1), 0)
        ix1_safe = tl.maximum(tl.minimum(ix1, iW - 1), 0)
        iy0_safe = tl.maximum(tl.minimum(iy0, iH - 1), 0)
        iy1_safe = tl.maximum(tl.minimum(iy1, iH - 1), 0)
        iz0_safe = tl.maximum(tl.minimum(iz0, iD - 1), 0)
        iz1_safe = tl.maximum(tl.minimum(iz1, iD - 1), 0)

        # Initialize grad_grid accumulators
        if need_grad_grid:
            grad_gx_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            grad_gy_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            grad_gz_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

        # Base offset for input/grad_input
        inp_base = n * inp_sN
        gi_base = n * gi_sN

        # Loop over channels for grad_input scatter
        if need_grad_input:
            for c in range(C):
                go_off = n * go_sN + c * go_sC + od * go_sD + oh * go_sH + ow * go_sW
                g_out = tl.load(grad_output_ptr + go_off, mask=mask, other=0.0).to(
                    tl.float32
                )
                gc_off = c * gi_sC

                # Compute offsets using safe (clamped) indices
                off_000 = (
                    gi_base
                    + gc_off
                    + iz0_safe * gi_sD
                    + iy0_safe * gi_sH
                    + ix0_safe * gi_sW
                )
                off_001 = (
                    gi_base
                    + gc_off
                    + iz1_safe * gi_sD
                    + iy0_safe * gi_sH
                    + ix0_safe * gi_sW
                )
                off_010 = (
                    gi_base
                    + gc_off
                    + iz0_safe * gi_sD
                    + iy1_safe * gi_sH
                    + ix0_safe * gi_sW
                )
                off_011 = (
                    gi_base
                    + gc_off
                    + iz1_safe * gi_sD
                    + iy1_safe * gi_sH
                    + ix0_safe * gi_sW
                )
                off_100 = (
                    gi_base
                    + gc_off
                    + iz0_safe * gi_sD
                    + iy0_safe * gi_sH
                    + ix1_safe * gi_sW
                )
                off_101 = (
                    gi_base
                    + gc_off
                    + iz1_safe * gi_sD
                    + iy0_safe * gi_sH
                    + ix1_safe * gi_sW
                )
                off_110 = (
                    gi_base
                    + gc_off
                    + iz0_safe * gi_sD
                    + iy1_safe * gi_sH
                    + ix1_safe * gi_sW
                )
                off_111 = (
                    gi_base
                    + gc_off
                    + iz1_safe * gi_sD
                    + iy1_safe * gi_sH
                    + ix1_safe * gi_sW
                )

                tl.atomic_add(grad_input_ptr + off_000, g_out * w000, mask=v000)
                tl.atomic_add(grad_input_ptr + off_001, g_out * w001, mask=v001)
                tl.atomic_add(grad_input_ptr + off_010, g_out * w010, mask=v010)
                tl.atomic_add(grad_input_ptr + off_011, g_out * w011, mask=v011)
                tl.atomic_add(grad_input_ptr + off_100, g_out * w100, mask=v100)
                tl.atomic_add(grad_input_ptr + off_101, g_out * w101, mask=v101)
                tl.atomic_add(grad_input_ptr + off_110, g_out * w110, mask=v110)
                tl.atomic_add(grad_input_ptr + off_111, g_out * w111, mask=v111)

        # Separate loop for grad_grid accumulation
        if need_grad_grid:
            for c in range(C):
                go_off = n * go_sN + c * go_sC + od * go_sD + oh * go_sH + ow * go_sW
                g_out = tl.load(grad_output_ptr + go_off, mask=mask, other=0.0).to(
                    tl.float32
                )
                c_off = c * inp_sC

                # Load input values using safe (clamped) indices
                inp_off_000 = (
                    inp_base
                    + c_off
                    + iz0_safe * inp_sD
                    + iy0_safe * inp_sH
                    + ix0_safe * inp_sW
                )
                inp_off_001 = (
                    inp_base
                    + c_off
                    + iz1_safe * inp_sD
                    + iy0_safe * inp_sH
                    + ix0_safe * inp_sW
                )
                inp_off_010 = (
                    inp_base
                    + c_off
                    + iz0_safe * inp_sD
                    + iy1_safe * inp_sH
                    + ix0_safe * inp_sW
                )
                inp_off_011 = (
                    inp_base
                    + c_off
                    + iz1_safe * inp_sD
                    + iy1_safe * inp_sH
                    + ix0_safe * inp_sW
                )
                inp_off_100 = (
                    inp_base
                    + c_off
                    + iz0_safe * inp_sD
                    + iy0_safe * inp_sH
                    + ix1_safe * inp_sW
                )
                inp_off_101 = (
                    inp_base
                    + c_off
                    + iz1_safe * inp_sD
                    + iy0_safe * inp_sH
                    + ix1_safe * inp_sW
                )
                inp_off_110 = (
                    inp_base
                    + c_off
                    + iz0_safe * inp_sD
                    + iy1_safe * inp_sH
                    + ix1_safe * inp_sW
                )
                inp_off_111 = (
                    inp_base
                    + c_off
                    + iz1_safe * inp_sD
                    + iy1_safe * inp_sH
                    + ix1_safe * inp_sW
                )

                i000 = tl.load(input_ptr + inp_off_000, mask=v000, other=0.0).to(
                    tl.float32
                )
                i001 = tl.load(input_ptr + inp_off_001, mask=v001, other=0.0).to(
                    tl.float32
                )
                i010 = tl.load(input_ptr + inp_off_010, mask=v010, other=0.0).to(
                    tl.float32
                )
                i011 = tl.load(input_ptr + inp_off_011, mask=v011, other=0.0).to(
                    tl.float32
                )
                i100 = tl.load(input_ptr + inp_off_100, mask=v100, other=0.0).to(
                    tl.float32
                )
                i101 = tl.load(input_ptr + inp_off_101, mask=v101, other=0.0).to(
                    tl.float32
                )
                i110 = tl.load(input_ptr + inp_off_110, mask=v110, other=0.0).to(
                    tl.float32
                )
                i111 = tl.load(input_ptr + inp_off_111, mask=v111, other=0.0).to(
                    tl.float32
                )

                # d(output)/dx = sum over z,y of weight_yz * (inp[1,y,z] - inp[0,y,z])
                grad_gx_acc += g_out * (
                    (1.0 - ty) * (1.0 - tz) * (i100 - i000)
                    + (1.0 - ty) * tz * (i101 - i001)
                    + ty * (1.0 - tz) * (i110 - i010)
                    + ty * tz * (i111 - i011)
                )
                # d(output)/dy
                grad_gy_acc += g_out * (
                    (1.0 - tx) * (1.0 - tz) * (i010 - i000)
                    + (1.0 - tx) * tz * (i011 - i001)
                    + tx * (1.0 - tz) * (i110 - i100)
                    + tx * tz * (i111 - i101)
                )
                # d(output)/dz
                grad_gz_acc += g_out * (
                    (1.0 - tx) * (1.0 - ty) * (i001 - i000)
                    + (1.0 - tx) * ty * (i011 - i010)
                    + tx * (1.0 - ty) * (i101 - i100)
                    + tx * ty * (i111 - i110)
                )

        # Write grad_grid
        if need_grad_grid:
            gg_base = n * gg_sN + od * gg_sD + oh * gg_sH + ow * gg_sW
            final_gx = grad_gx_acc * gx_mult * px_mult
            final_gy = grad_gy_acc * gy_mult * py_mult
            final_gz = grad_gz_acc * gz_mult * pz_mult
            tl.store(grad_grid_ptr + gg_base, final_gx, mask=mask)
            tl.store(grad_grid_ptr + gg_base + 1, final_gy, mask=mask)
            tl.store(grad_grid_ptr + gg_base + 2, final_gz, mask=mask)

    elif interpolation_mode == 1:  # nearest
        # Nearest neighbor: round to nearest index
        ix_nearest = tl.floor(ix + 0.5).to(tl.int32)
        iy_nearest = tl.floor(iy + 0.5).to(tl.int32)
        iz_nearest = tl.floor(iz + 0.5).to(tl.int32)

        valid = (
            (ix_nearest >= 0)
            & (ix_nearest < iW)
            & (iy_nearest >= 0)
            & (iy_nearest < iH)
            & (iz_nearest >= 0)
            & (iz_nearest < iD)
            & mask
        )

        if need_grad_input:
            inp_base = n * inp_sN
            gi_base = n * gi_sN
            # Clamp for safe address computation
            ix_safe = tl.maximum(tl.minimum(ix_nearest, iW - 1), 0)
            iy_safe = tl.maximum(tl.minimum(iy_nearest, iH - 1), 0)
            iz_safe = tl.maximum(tl.minimum(iz_nearest, iD - 1), 0)
            for c in range(C):
                go_off = n * go_sN + c * go_sC + od * go_sD + oh * go_sH + ow * go_sW
                g_out = tl.load(grad_output_ptr + go_off, mask=mask, other=0.0).to(
                    tl.float32
                )
                gi_off = (
                    gi_base
                    + c * gi_sC
                    + iz_safe * gi_sD
                    + iy_safe * gi_sH
                    + ix_safe * gi_sW
                )
                tl.atomic_add(grad_input_ptr + gi_off, g_out, mask=valid)

        # Nearest mode has zero gradient w.r.t. grid coordinates
        if need_grad_grid:
            gg_base = n * gg_sN + od * gg_sD + oh * gg_sH + ow * gg_sW
            zeros = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            tl.store(grad_grid_ptr + gg_base, zeros, mask=mask)
            tl.store(grad_grid_ptr + gg_base + 1, zeros, mask=mask)
            tl.store(grad_grid_ptr + gg_base + 2, zeros, mask=mask)


def grid_sampler_3d_backward(
    grad_output: torch.Tensor,
    input: torch.Tensor,
    grid: torch.Tensor,
    interpolation_mode: int,
    padding_mode: int,
    align_corners: bool,
    output_mask: list,
) -> tuple:
    """Backward pass for grid_sampler_3d.

    Args:
        grad_output: (N, C, oD, oH, oW)
        input: (N, C, iD, iH, iW)
        grid: (N, oD, oH, oW, 3)
        interpolation_mode: 0=bilinear, 1=nearest
        padding_mode: 0=zeros, 1=border, 2=reflection
        align_corners: whether to align corners
        output_mask: [need_grad_input, need_grad_grid]

    Returns:
        (grad_input, grad_grid)
    """
    logger.debug(
        "grid_sampler_3d_backward: mode=%d pad=%d align=%s",
        interpolation_mode,
        padding_mode,
        align_corners,
    )

    # PyTorch grid_sampler_3d_backward only supports float32/float64 on CUDA
    assert grad_output.dtype in (
        torch.float32,
        torch.float64,
    ), f"grid_sampler_3d_backward only supports float32/float64, got {grad_output.dtype}"
    assert (
        input.dtype == grad_output.dtype
    ), "input and grad_output must have same dtype"
    assert grid.dtype == grad_output.dtype, "grid and grad_output must have same dtype"

    N, C, iD, iH, iW = input.shape
    _, oD, oH, oW, _ = grid.shape

    need_grad_input = output_mask[0]
    need_grad_grid = output_mask[1]

    # Ensure contiguous tensors for consistent strides
    grad_output = grad_output.contiguous()
    input = input.contiguous()
    grid = grid.contiguous()

    # Allocate output tensors
    if need_grad_input:
        grad_input = torch.zeros_like(input, dtype=torch.float32)
    else:
        grad_input = torch.zeros(
            (N, C, iD, iH, iW), dtype=torch.float32, device=input.device
        )

    if need_grad_grid:
        grad_grid = torch.empty(
            (N, oD, oH, oW, 3), dtype=torch.float32, device=grid.device
        )
    else:
        grad_grid = torch.zeros(
            (N, oD, oH, oW, 3), dtype=torch.float32, device=grid.device
        )

    num_elements = N * oD * oH * oW

    if num_elements == 0:
        return grad_input.to(input.dtype), grad_grid.to(grid.dtype)

    # Cast input tensors to float32 for computation
    grad_output_f32 = grad_output.float()
    input_f32 = input.float()
    grid_f32 = grid.float()

    # Use fixed BLOCK_SIZE to avoid autotune pollution of output buffers
    BLOCK_SIZE = 256
    grid_launch = (triton.cdiv(num_elements, BLOCK_SIZE),)

    grid_sampler_3d_backward_kernel[grid_launch](
        grad_output_f32,
        input_f32,
        grid_f32,
        grad_input,
        grad_grid,
        N,
        C,
        iD,
        iH,
        iW,
        oD,
        oH,
        oW,
        # grad_output strides
        grad_output_f32.stride(0),
        grad_output_f32.stride(1),
        grad_output_f32.stride(2),
        grad_output_f32.stride(3),
        grad_output_f32.stride(4),
        # input strides
        input_f32.stride(0),
        input_f32.stride(1),
        input_f32.stride(2),
        input_f32.stride(3),
        input_f32.stride(4),
        # grid strides
        grid_f32.stride(0),
        grid_f32.stride(1),
        grid_f32.stride(2),
        grid_f32.stride(3),
        # grad_input strides
        grad_input.stride(0),
        grad_input.stride(1),
        grad_input.stride(2),
        grad_input.stride(3),
        grad_input.stride(4),
        # grad_grid strides
        grad_grid.stride(0),
        grad_grid.stride(1),
        grad_grid.stride(2),
        grad_grid.stride(3),
        # Parameters
        num_elements,
        interpolation_mode=interpolation_mode,
        padding_mode=padding_mode,
        align_corners=align_corners,
        need_grad_input=need_grad_input,
        need_grad_grid=need_grad_grid,
        BLOCK_SIZE=BLOCK_SIZE,
    )

    return grad_input.to(input.dtype), grad_grid.to(grid.dtype)
