# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _huber_loss_element_kernel(
    x_ptr, y_ptr, out_ptr, n_elements, delta, BLOCK_SIZE: tl.constexpr
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)
    y = tl.load(y_ptr + offsets, mask=mask)
    diff = x - y
    absdiff = tl.abs(diff)

    # loss = 0.5 * diff^2                    if |diff| <= delta
    #        delta * (|diff| - 0.5 * delta)  otherwise
    loss_quad = 0.5 * diff * diff
    loss_linear = delta * (absdiff - 0.5 * delta)
    loss = tl.where(absdiff <= delta, loss_quad, loss_linear)

    tl.store(out_ptr + offsets, loss, mask=mask)


@libentry()
@triton.jit
def _huber_loss_reduce_kernel(
    x_ptr, y_ptr, mid_ptr, n_elements, delta, BLOCK_SIZE: tl.constexpr
):
    # Stage 1: compute the per-element huber loss and store one partial sum
    # per program into `mid`. No atomics -- avoids serialization.
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    y = tl.load(y_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    diff = x - y
    absdiff = tl.abs(diff)
    loss_quad = 0.5 * diff * diff
    loss_linear = delta * (absdiff - 0.5 * delta)
    loss = tl.where(absdiff <= delta, loss_quad, loss_linear)
    loss = tl.where(mask, loss, 0.0)

    tl.store(mid_ptr + pid, tl.sum(loss, axis=0))


@libentry()
@triton.jit
def _reduce_sum_kernel(mid_ptr, out_ptr, mid_size, divisor, BLOCK_MID: tl.constexpr):
    # Stage 2: reduce the `mid` partial sums to a single scalar, applying the
    # mean divisor (1.0 for sum) and casting to the output dtype in-kernel so
    # no extra host-side division/cast launches are needed.
    offsets = tl.arange(0, BLOCK_MID)
    mask = offsets < mid_size
    vals = tl.load(mid_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
    tl.store(out_ptr, tl.sum(vals, axis=0) / divisor)


@libentry()
@triton.jit
def _huber_loss_fused_kernel(
    x_ptr, y_ptr, out_ptr, n_elements, delta, divisor, BLOCK_SIZE: tl.constexpr
):
    # Single-launch fused reduction for small tensors: one program with a
    # grid-stride loop consumes the whole input, reduces to a scalar, applies
    # the mean/sum divisor, and casts to the output dtype in-kernel -- all in
    # ONE launch with NO intermediate `mid` allocation. This removes the second
    # kernel launch + mid-array allocation that dominated small-tensor latency
    # in the two-stage path.
    acc = tl.zeros((), dtype=tl.float32)
    for base in range(0, n_elements, BLOCK_SIZE):
        offsets = base + tl.arange(0, BLOCK_SIZE)
        mask = offsets < n_elements
        x = tl.load(x_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
        y = tl.load(y_ptr + offsets, mask=mask, other=0.0).to(tl.float32)
        diff = x - y
        absdiff = tl.abs(diff)
        loss_quad = 0.5 * diff * diff
        loss_linear = delta * (absdiff - 0.5 * delta)
        loss = tl.where(absdiff <= delta, loss_quad, loss_linear)
        loss = tl.where(mask, loss, 0.0)
        acc += tl.sum(loss, axis=0)

    tl.store(out_ptr, acc / divisor)


def _normalize_reduction(reduction):
    if isinstance(reduction, str):
        r = reduction.lower()
        mapping = {"none": 0, "mean": 1, "sum": 2}
        if r not in mapping:
            raise ValueError(f"Unsupported reduction: {reduction}")
        return mapping[r]
    if isinstance(reduction, int) and reduction in (0, 1, 2):
        return reduction
    raise ValueError(f"Unsupported reduction: {reduction}")


def _huber_loss_compute(input, target, reduction, delta, result_dtype):
    device = input.device
    x_b, y_b = torch.broadcast_tensors(input.to(result_dtype), target.to(result_dtype))
    x_b = x_b.contiguous()
    y_b = y_b.contiguous()
    numel = x_b.numel()

    with torch_device_fn.device(device):
        if reduction == 0:  # none
            out = torch.empty_like(x_b, dtype=result_dtype, device=device)
            grid = lambda meta: (triton.cdiv(numel, meta["BLOCK_SIZE"]),)
            _huber_loss_element_kernel[grid](
                x_b, y_b, out, numel, float(delta), BLOCK_SIZE=1024
            )
            return out

        divisor = float(numel) if reduction == 1 else 1.0  # mean vs sum
        out = torch.empty((), dtype=result_dtype, device=device)

        # Small tensors: the two-stage path is dominated by the fixed cost of a
        # second kernel launch + the `mid` allocation. A single fused kernel
        # (one launch, no `mid`) that grid-strides the whole input and writes
        # the scalar result directly in the output dtype is markedly faster.
        # The single-block grid-stride loop stays efficient until the input is
        # large enough that a parallel tree reduction wins -- past FUSED_LIMIT
        # we switch to the two-stage kernels.
        FUSED_LIMIT = 1 << 17  # 131,072 elements
        if numel <= FUSED_LIMIT:
            block_size = min(1024, triton.next_power_of_2(numel))
            _huber_loss_fused_kernel[(1, 1, 1)](
                x_b, y_b, out, numel, float(delta), divisor, BLOCK_SIZE=block_size
            )
            return out

        # Two-stage tree reduction (mirrors mse_loss): stage 1 fuses the huber
        # computation with a per-block partial sum into `mid`; stage 2 reduces
        # `mid` to a scalar. Avoids the atomic-add serialization bottleneck.
        block_size = triton.next_power_of_2(math.ceil(math.sqrt(numel)))
        mid_size = triton.cdiv(numel, block_size)
        block_mid = triton.next_power_of_2(mid_size)

        mid = torch.empty((mid_size,), dtype=torch.float32, device=device)

        _huber_loss_reduce_kernel[(mid_size, 1, 1)](
            x_b, y_b, mid, numel, float(delta), BLOCK_SIZE=block_size
        )
        _reduce_sum_kernel[(1, 1, 1)](mid, out, mid_size, divisor, BLOCK_MID=block_mid)
        return out


def huber_loss(self: torch.Tensor, target: torch.Tensor, reduction=1, delta=1.0):
    logger.debug("GEMS HUBER_LOSS")
    reduction = _normalize_reduction(reduction)
    result_dtype = torch.result_type(self, target)
    return _huber_loss_compute(self, target, reduction, delta, result_dtype)


def huber_loss_out(
    self: torch.Tensor,
    target: torch.Tensor,
    reduction=1,
    delta=1.0,
    *,
    out: torch.Tensor,
):
    logger.debug("GEMS HUBER_LOSS_OUT")
    reduction = _normalize_reduction(reduction)
    val = _huber_loss_compute(self, target, reduction, delta, out.dtype)
    if reduction == 0:
        if out.shape != val.shape:
            out.resize_(val.shape)
    out.copy_(val)
    return out
