# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def lu_unpack_p_kernel_small(
    pivots_ptr,
    p_ptr,
    m,
    k,
    pivots_stride_b,
    pivots_stride_k,
    p_stride_b,
    p_stride_m,
    p_stride_n,
    BLOCK_M: tl.constexpr,
):
    """
    Vectorized P kernel for small/medium matrices (m <= BLOCK_M).
    One program per batch element processes the entire permutation at once.
    Grid: (batch_size,)

    Strategy: maintain perm[0..m-1] as a vector, apply all k swaps vectorized,
    then scatter 1.0 to P[i, perm[i]] for each i.
    """
    batch_id = tl.program_id(0)

    pivots_base = batch_id * pivots_stride_b
    p_base = batch_id * p_stride_b

    # Initialize perm = [0, 1, 2, ..., m-1]
    row_ids = tl.arange(0, BLOCK_M)
    perm = row_ids  # perm[i] tracks where row i maps to
    mask = row_ids < m

    # Apply all pivot swaps vectorized
    for i in range(k):
        pivot_val = tl.load(pivots_ptr + pivots_base + i * pivots_stride_k)
        pivot_idx = pivot_val - 1  # 0-indexed

        # Vectorized swap: for all rows simultaneously
        # If perm[j] == i, set perm[j] = pivot_idx
        # If perm[j] == pivot_idx, set perm[j] = i
        perm = tl.where(
            perm == i,
            pivot_idx,
            tl.where(perm == pivot_idx, i, perm),
        )

    # Write P[i, perm[i]] = 1.0 for each row i
    # P is pre-zeroed, just scatter the 1s
    offsets = p_base + row_ids * p_stride_m + perm * p_stride_n
    tl.store(p_ptr + offsets, tl.full([BLOCK_M], 1.0, dtype=tl.float32), mask=mask)


@libentry()
@triton.jit
def lu_unpack_p_kernel_large(
    pivots_ptr,
    p_ptr,
    m,
    k,
    pivots_stride_b,
    pivots_stride_k,
    p_stride_b,
    p_stride_m,
    p_stride_n,
    BLOCK_SIZE: tl.constexpr,
):
    """
    P kernel for large matrices (m > 4096).
    Each program handles one row, computes its final permutation position,
    then writes a single 1.0 at P[row, final_pos].
    Grid: (batch_size * m,)
    """
    pid = tl.program_id(0)
    batch_id = pid // m
    row_id = pid % m

    pivots_base = batch_id * pivots_stride_b
    p_base = batch_id * p_stride_b

    # Track where this row ends up after applying all pivot swaps
    current_pos = row_id
    for i in range(k):
        pivot_val = tl.load(pivots_ptr + pivots_base + i * pivots_stride_k)
        pivot_idx = pivot_val - 1
        current_pos = tl.where(
            current_pos == i,
            pivot_idx,
            tl.where(current_pos == pivot_idx, i, current_pos),
        )

    # P is pre-zeroed; only write the single 1.0
    tl.store(
        p_ptr + p_base + row_id * p_stride_m + current_pos * p_stride_n,
        1.0,
    )


@libentry()
@triton.jit
def lu_unpack_l_kernel(
    lu_ptr,
    l_ptr,
    m,
    n,
    k,
    lu_stride_b,
    lu_stride_m,
    lu_stride_n,
    l_stride_b,
    l_stride_m,
    l_stride_n,
    BLOCK_K: tl.constexpr,
):
    """
    Kernel to extract L from packed LU data.
    Each program handles one row of L for one batch element.
    Grid: (batch_size * m,)
    L[row, col] = LU[row, col] if row > col, 1 if row == col, 0 otherwise
    """
    pid = tl.program_id(0)
    batch_id = pid // m
    row = pid % m

    lu_base = batch_id * lu_stride_b
    l_base = batch_id * l_stride_b

    col_offsets = tl.arange(0, BLOCK_K)
    num_blocks = (k + BLOCK_K - 1) // BLOCK_K
    for block_idx in range(num_blocks):
        cols = block_idx * BLOCK_K + col_offsets
        mask = cols < k

        lu_vals = tl.load(
            lu_ptr + lu_base + row * lu_stride_m + cols * lu_stride_n,
            mask=mask,
            other=0.0,
        )

        vals = tl.where(row > cols, lu_vals, tl.where(row == cols, 1.0, 0.0))

        tl.store(
            l_ptr + l_base + row * l_stride_m + cols * l_stride_n,
            vals,
            mask=mask,
        )


@libentry()
@triton.jit
def lu_unpack_u_kernel(
    lu_ptr,
    u_ptr,
    m,
    n,
    k,
    lu_stride_b,
    lu_stride_m,
    lu_stride_n,
    u_stride_b,
    u_stride_m,
    u_stride_n,
    BLOCK_N: tl.constexpr,
):
    """
    Kernel to extract U from packed LU data.
    Each program handles one row of U for one batch element.
    Grid: (batch_size * k,)
    U[row, col] = LU[row, col] if row <= col, 0 otherwise
    """
    pid = tl.program_id(0)
    batch_id = pid // k
    row = pid % k

    lu_base = batch_id * lu_stride_b
    u_base = batch_id * u_stride_b

    col_offsets = tl.arange(0, BLOCK_N)
    num_blocks = (n + BLOCK_N - 1) // BLOCK_N
    for block_idx in range(num_blocks):
        cols = block_idx * BLOCK_N + col_offsets
        mask = cols < n

        lu_vals = tl.load(
            lu_ptr + lu_base + row * lu_stride_m + cols * lu_stride_n,
            mask=mask,
            other=0.0,
        )

        vals = tl.where(row <= cols, lu_vals, 0.0)

        tl.store(
            u_ptr + u_base + row * u_stride_m + cols * u_stride_n,
            vals,
            mask=mask,
        )


def lu_unpack(LU_data, LU_pivots, unpack_data=True, unpack_pivots=True):
    """
    Unpacks the LU decomposition into P, L, U matrices.

    Args:
        LU_data: Tensor of shape (..., m, n) containing the packed LU factorization
        LU_pivots: Tensor of shape (..., min(m, n)) containing the pivots (1-indexed)
        unpack_data: If True, unpack L and U. If False, return empty tensors.
        unpack_pivots: If True, unpack P. If False, return empty tensor.

    Returns:
        Tuple of (P, L, U) where:
            P: (..., m, m) permutation matrix
            L: (..., m, min(m, n)) lower triangular with unit diagonal
            U: (..., min(m, n), n) upper triangular
    """
    # Get shapes
    lu_shape = LU_data.shape
    pivots_shape = LU_pivots.shape

    assert LU_data.dtype in (
        torch.float32,
        torch.float64,
    ), f"lu_unpack only supports float32/float64, got {LU_data.dtype}"

    # Handle batch dimensions
    batch_dims = lu_shape[:-2]
    m, n = lu_shape[-2], lu_shape[-1]
    k = min(m, n)  # min(m, n)

    logger.debug(
        "GEMS LU_UNPACK, shape: %s, m: %s, n: %s, k: %s",
        lu_shape,
        m,
        n,
        k,
    )

    # Prepare outputs
    device = LU_data.device
    dtype = LU_data.dtype

    # Handle batch size
    if len(batch_dims) > 0:
        batch_size = 1
        for dim in batch_dims:
            batch_size *= dim
    else:
        batch_size = 1

    if unpack_pivots:
        # P has shape (..., m, m), pre-initialized to zeros
        P = torch.zeros(*batch_dims, m, m, device=device, dtype=dtype)

        # Hybrid strategy based on matrix size:
        # - Small m (<=512): vectorized kernel processing entire perm in one program
        #   (reduces total pivot loop iterations from m*k to k with SIMD width m)
        # - Large m (>512): per-row kernel with single store (better parallelism)
        if m <= 512:
            # Vectorized kernel: one program per batch, processes all rows in parallel
            BLOCK_M = triton.next_power_of_2(m)
            grid = (batch_size,)
            lu_unpack_p_kernel_small[grid](
                LU_pivots,
                P,
                m,
                k,
                LU_pivots.stride(-2) if len(pivots_shape) > 1 else 0,
                LU_pivots.stride(-1) if len(pivots_shape) > 0 else 0,
                P.stride(-3) if len(batch_dims) > 0 else 0,
                P.stride(-2),
                P.stride(-1),
                BLOCK_M,
            )
        else:
            # Per-row kernel: each program tracks one row through pivots
            BLOCK_SIZE = 1  # Each program writes single element
            grid = (batch_size * m,)
            lu_unpack_p_kernel_large[grid](
                LU_pivots,
                P,
                m,
                k,
                LU_pivots.stride(-2) if len(pivots_shape) > 1 else 0,
                LU_pivots.stride(-1) if len(pivots_shape) > 0 else 0,
                P.stride(-3) if len(batch_dims) > 0 else 0,
                P.stride(-2),
                P.stride(-1),
                BLOCK_SIZE,
            )
    else:
        # Return empty tensor
        P = torch.empty(0, device=device, dtype=dtype)

    if unpack_data:
        # L has shape (..., m, k)
        L = torch.empty(*batch_dims, m, k, device=device, dtype=dtype)
        # U has shape (..., k, n)
        U = torch.empty(*batch_dims, k, n, device=device, dtype=dtype)

        # Compute block sizes as next power of 2, capped at 1024
        BLOCK_K = triton.next_power_of_2(k)
        if BLOCK_K > 1024:
            BLOCK_K = 1024
        BLOCK_N = triton.next_power_of_2(n)
        if BLOCK_N > 1024:
            BLOCK_N = 1024

        # Extract L: each program handles one row
        grid_l = (batch_size * m,)
        lu_unpack_l_kernel[grid_l](
            LU_data,
            L,
            m,
            n,
            k,
            LU_data.stride(-3) if len(lu_shape) > 2 else 0,
            LU_data.stride(-2),
            LU_data.stride(-1),
            L.stride(-3) if len(batch_dims) > 0 else 0,
            L.stride(-2),
            L.stride(-1),
            BLOCK_K,
        )

        # Extract U: each program handles one row
        grid_u = (batch_size * k,)
        lu_unpack_u_kernel[grid_u](
            LU_data,
            U,
            m,
            n,
            k,
            LU_data.stride(-3) if len(lu_shape) > 2 else 0,
            LU_data.stride(-2),
            LU_data.stride(-1),
            U.stride(-3) if len(batch_dims) > 0 else 0,
            U.stride(-2),
            U.stride(-1),
            BLOCK_N,
        )
    else:
        # Return empty tensors
        L = torch.empty(0, device=device, dtype=dtype)
        U = torch.empty(0, device=device, dtype=dtype)

    return (P, L, U)


def lu_unpack_out(
    LU_data, LU_pivots, unpack_data=True, unpack_pivots=True, *, P=None, L=None, U=None
):
    """
    Out-of-place variant of lu_unpack that writes results into pre-allocated tensors.

    Args:
        LU_data: Tensor of shape (..., m, n) containing the packed LU factorization
        LU_pivots: Tensor of shape (..., min(m, n)) containing the pivots (1-indexed)
        unpack_data: If True, unpack L and U. If False, return empty tensors.
        unpack_pivots: If True, unpack P. If False, return empty tensor.
        P: Optional pre-allocated output tensor for permutation matrix
        L: Optional pre-allocated output tensor for lower triangular matrix
        U: Optional pre-allocated output tensor for upper triangular matrix

    Returns:
        Tuple of (P, L, U)
    """
    P_result, L_result, U_result = lu_unpack(
        LU_data, LU_pivots, unpack_data, unpack_pivots
    )

    if P is not None and P_result.numel() > 0:
        P.copy_(P_result)
    else:
        P = P_result

    if L is not None and L_result.numel() > 0:
        L.copy_(L_result)
    else:
        L = L_result

    if U is not None and U_result.numel() > 0:
        U.copy_(U_result)
    else:
        U = U_result

    return (P, L, U)
