# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def _parse_pool3d_params(kernel_size, stride, padding, dilation):
    """Parse and validate 3-D pooling parameters.

    Each parameter can be an int (applied to all 3 spatial dims) or a
    3-element tuple/list (D, H, W).
    """

    def _parse_param(param, name, default=None):
        if param is None:
            return default
        if isinstance(param, int):
            return param, param, param
        if isinstance(param, (list, tuple)) and len(param) == 3:
            return tuple(param)
        raise ValueError(f"Invalid {name}: {param}")

    kd, kh, kw = _parse_param(kernel_size, "kernel_size")
    sd, sh, sw = _parse_param(stride, "stride", default=(kd, kh, kw))
    pd, ph, pw = _parse_param(padding, "padding", default=(0, 0, 0))
    dd, dh, dw = _parse_param(dilation, "dilation", default=(1, 1, 1))

    if sd <= 0 or sh <= 0 or sw <= 0:
        raise ValueError(f"stride must be positive, but got stride=({sd}, {sh}, {sw})")
    if pd < 0 or ph < 0 or pw < 0:
        raise ValueError(
            f"padding must be non-negative, but got padding=({pd}, {ph}, {pw})"
        )
    if dd <= 0 or dh <= 0 or dw <= 0:
        raise ValueError(
            f"dilation must be positive, but got dilation=({dd}, {dh}, {dw})"
        )

    return kd, kh, kw, sd, sh, sw, pd, ph, pw, dd, dh, dw


def pool3d_output_size(
    in_size: int,
    kernel_size: int,
    stride: int,
    padding: int,
    dilation: int,
    ceil_mode: bool = False,
) -> int:
    """Compute one spatial dimension of the 3-D max-pool output."""
    effective_kernel_size = (kernel_size - 1) * dilation + 1
    numerator = in_size + 2 * padding - effective_kernel_size
    if ceil_mode:
        output_size = (numerator + stride - 1) // stride + 1
        if (output_size - 1) * stride >= in_size + padding:
            output_size -= 1
    else:
        output_size = numerator // stride + 1
    return output_size


@libentry()
@triton.autotune(
    configs=[
        triton.Config({"BLOCK_SIZE": 256}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 512}, num_warps=4),
        triton.Config({"BLOCK_SIZE": 1024}, num_warps=8),
        triton.Config({"BLOCK_SIZE": 2048}, num_warps=8),
    ],
    key=["out_numel_per_nc"],
    reset_to_zero=["grad_input_ptr"],
)
@triton.jit
def max_pool3d_with_indices_backward_kernel(
    grad_output_ptr,
    indices_ptr,
    grad_input_ptr,
    # Shape info
    in_d,
    in_h,
    in_w,
    out_d,
    out_h,
    out_w,
    out_numel_per_nc,
    in_numel_per_nc,
    # Tiling parameters
    BLOCK_SIZE: tl.constexpr,
):
    """Backward kernel for 3-D max pooling (scatter-based).

    Grid: (N * C, cdiv(out_D * out_H * out_W, BLOCK_SIZE))
    For each output position, read the index and scatter grad to the
    corresponding input position using atomic_add.
    """
    nc_idx = tl.program_id(0)
    block_idx = tl.program_id(1)

    offsets = block_idx * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < out_numel_per_nc

    # Load grad_output and indices for this block of output positions
    base_out = nc_idx * out_numel_per_nc
    grad_vals = tl.load(grad_output_ptr + base_out + offsets, mask=mask, other=0.0)
    idx_vals = tl.load(indices_ptr + base_out + offsets, mask=mask, other=-1)

    # Scatter grad to input positions
    valid_mask = mask & (idx_vals >= 0)
    base_in = nc_idx * in_numel_per_nc
    tl.atomic_add(grad_input_ptr + base_in + idx_vals, grad_vals, mask=valid_mask)


def max_pool3d_with_indices_backward(
    grad_output: torch.Tensor,
    self: torch.Tensor,
    kernel_size,
    stride,
    padding,
    dilation,
    ceil_mode: bool,
    indices: torch.Tensor,
) -> torch.Tensor:
    """Backward pass for 3-D max pooling with indices.

    Matches the ATen signature:
        aten::max_pool3d_with_indices_backward(
            Tensor grad_output, Tensor self, int[3] kernel_size,
            int[3] stride, int[3] padding, int[3] dilation,
            bool ceil_mode, Tensor indices) -> Tensor
    """
    logger.debug("GEMS MAX_POOL3D_WITH_INDICES_BACKWARD")
    out_dtype = grad_output.dtype
    grad_output = grad_output.contiguous().to(torch.float32)
    indices = indices.contiguous()

    _parse_pool3d_params(kernel_size, stride, padding, dilation)

    in_n, in_c, in_d, in_h, in_w = self.shape
    out_d, out_h, out_w = (
        grad_output.shape[2],
        grad_output.shape[3],
        grad_output.shape[4],
    )

    grad_input = torch.zeros_like(self, dtype=torch.float32)

    if grad_input.numel() == 0:
        return grad_input.to(out_dtype)

    out_numel_per_nc = out_d * out_h * out_w
    in_numel_per_nc = in_d * in_h * in_w

    grid = lambda meta: (
        in_n * in_c,
        triton.cdiv(out_numel_per_nc, meta["BLOCK_SIZE"]),
    )

    max_pool3d_with_indices_backward_kernel[grid](
        grad_output,
        indices,
        grad_input,
        in_d,
        in_h,
        in_w,
        out_d,
        out_h,
        out_w,
        out_numel_per_nc,
        in_numel_per_nc,
    )

    return grad_input.to(out_dtype)
