# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


# =============================================================================
# Small-matrix fused kernels (for active_rows <= 128 and cols <= 128)
# Single block handles everything — no tiling needed.
# =============================================================================


@libentry()
@triton.jit
def _householder_left_fused_kernel(
    C_ptr,
    input_ptr,
    tau_ptr,
    M,
    N,
    i,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Fused kernel for left Householder on small matrices.
    Grid: (batch,). Each block handles one batch element fully.
    """
    bid = tl.program_id(0)
    row_offs = tl.arange(0, BLOCK_M)
    col_offs = tl.arange(0, BLOCK_N)
    active_rows = M - i
    row_mask = row_offs < active_rows
    col_mask = col_offs < N

    # Build v: v[0]=1, v[j]=input[i+j, i] for j>0
    v_vals = tl.load(
        input_ptr + bid * stride_ib + (i + row_offs) * stride_im + i * stride_ik,
        mask=(row_offs > 0) & row_mask,
        other=0.0,
    )
    v = tl.where(row_offs == 0, 1.0, v_vals)
    tau_val = tl.load(tau_ptr + bid * stride_tb + i)

    # Load C[i:, :]
    c_block = tl.load(
        C_ptr
        + bid * stride_cb
        + (i + row_offs[:, None]) * stride_cm
        + col_offs[None, :] * stride_cn,
        mask=row_mask[:, None] & col_mask[None, :],
        other=0.0,
    )

    # w = v^T @ C[i:, :], then C[i:, :] -= tau * v * w^T
    w = tl.sum(v[:, None] * c_block, axis=0)
    c_block = c_block - tau_val * v[:, None] * w[None, :]

    tl.store(
        C_ptr
        + bid * stride_cb
        + (i + row_offs[:, None]) * stride_cm
        + col_offs[None, :] * stride_cn,
        c_block,
        mask=row_mask[:, None] & col_mask[None, :],
    )


@libentry()
@triton.jit
def _householder_right_fused_kernel(
    C_ptr,
    input_ptr,
    tau_ptr,
    M,
    N,
    i,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Fused kernel for right Householder on small matrices.
    Grid: (batch,). Each block handles one batch element fully.
    """
    bid = tl.program_id(0)
    row_offs = tl.arange(0, BLOCK_M)
    col_offs = tl.arange(0, BLOCK_N)
    active_cols = N - i
    row_mask = row_offs < M
    col_mask = col_offs < active_cols

    v_vals = tl.load(
        input_ptr + bid * stride_ib + (i + col_offs) * stride_im + i * stride_ik,
        mask=(col_offs > 0) & col_mask,
        other=0.0,
    )
    v = tl.where(col_offs == 0, 1.0, v_vals)
    tau_val = tl.load(tau_ptr + bid * stride_tb + i)

    c_block = tl.load(
        C_ptr
        + bid * stride_cb
        + row_offs[:, None] * stride_cm
        + (i + col_offs[None, :]) * stride_cn,
        mask=row_mask[:, None] & col_mask[None, :],
        other=0.0,
    )

    w = tl.sum(c_block * v[None, :], axis=1)
    c_block = c_block - tau_val * w[:, None] * v[None, :]

    tl.store(
        C_ptr
        + bid * stride_cb
        + row_offs[:, None] * stride_cm
        + (i + col_offs[None, :]) * stride_cn,
        c_block,
        mask=row_mask[:, None] & col_mask[None, :],
    )


# =============================================================================
# Large-matrix tiled kernels: one kernel launch per reflector.
# Grid parallelizes over column tiles (left) or row tiles (right).
# Each block does a full reduction over the active rows/cols internally.
# =============================================================================


@libentry()
@triton.jit
def _householder_apply_left_kernel(
    C_ptr,
    input_ptr,
    tau_ptr,
    M,
    N,
    i,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
    BLOCK_N: tl.constexpr,
    BLOCK_M_INNER: tl.constexpr,
):
    """Apply single left Householder reflector i to C.
    Grid: (num_col_tiles, batch).
    Each block handles BLOCK_N columns, loops over rows internally.

    Computes: w = v^T @ C[i:, col_tile], then C[i:, col_tile] -= tau * v * w^T
    where v[0]=1, v[j]=input[i+j, i] for j>0.
    """
    col_tile_id = tl.program_id(0)
    bid = tl.program_id(1)

    col_offs = col_tile_id * BLOCK_N + tl.arange(0, BLOCK_N)
    col_mask = col_offs < N
    active_rows = M - i

    tau_val = tl.load(tau_ptr + bid * stride_tb + i)

    # Phase 1: Compute w = v^T @ C[i:, col_tile] by looping over row chunks
    # w has shape (BLOCK_N,) -- one dot product result per column
    w = tl.zeros([BLOCK_N], dtype=tl.float32)

    for m_start in range(0, active_rows, BLOCK_M_INNER):
        m_offs = m_start + tl.arange(0, BLOCK_M_INNER)
        m_mask = m_offs < active_rows

        # Load v chunk: v[0]=1, v[j]=input[i+j, i]
        v_vals = tl.load(
            input_ptr + bid * stride_ib + (i + m_offs) * stride_im + i * stride_ik,
            mask=(m_offs > 0) & m_mask,
            other=0.0,
        )
        v_chunk = tl.where(m_offs == 0, 1.0, v_vals)

        # Load C chunk: C[i+m_offs, col_offs]
        c_chunk = tl.load(
            C_ptr
            + bid * stride_cb
            + (i + m_offs[:, None]) * stride_cm
            + col_offs[None, :] * stride_cn,
            mask=m_mask[:, None] & col_mask[None, :],
            other=0.0,
        )

        # Accumulate w += v_chunk^T @ c_chunk (reduce over rows)
        w += tl.sum(v_chunk.to(tl.float32)[:, None] * c_chunk.to(tl.float32), axis=0)

    # Phase 2: Update C[i:, col_tile] -= tau * v * w^T
    for m_start in range(0, active_rows, BLOCK_M_INNER):
        m_offs = m_start + tl.arange(0, BLOCK_M_INNER)
        m_mask = m_offs < active_rows

        v_vals = tl.load(
            input_ptr + bid * stride_ib + (i + m_offs) * stride_im + i * stride_ik,
            mask=(m_offs > 0) & m_mask,
            other=0.0,
        )
        v_chunk = tl.where(m_offs == 0, 1.0, v_vals)

        c_chunk = tl.load(
            C_ptr
            + bid * stride_cb
            + (i + m_offs[:, None]) * stride_cm
            + col_offs[None, :] * stride_cn,
            mask=m_mask[:, None] & col_mask[None, :],
            other=0.0,
        )

        c_chunk = c_chunk - (
            tau_val * v_chunk[:, None] * w[None, :].to(v_chunk.dtype)
        ).to(c_chunk.dtype)

        tl.store(
            C_ptr
            + bid * stride_cb
            + (i + m_offs[:, None]) * stride_cm
            + col_offs[None, :] * stride_cn,
            c_chunk,
            mask=m_mask[:, None] & col_mask[None, :],
        )


@libentry()
@triton.jit
def _householder_apply_right_kernel(
    C_ptr,
    input_ptr,
    tau_ptr,
    M,
    N,
    i,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
    BLOCK_M: tl.constexpr,
    BLOCK_N_INNER: tl.constexpr,
):
    """Apply single right Householder reflector i to C.
    Grid: (num_row_tiles, batch).
    Each block handles BLOCK_M rows, loops over active columns internally.

    Computes: w = C[row_tile, i:] @ v, then C[row_tile, i:] -= tau * w * v^T
    where v[0]=1, v[j]=input[i+j, i] for j>0.
    """
    row_tile_id = tl.program_id(0)
    bid = tl.program_id(1)

    row_offs = row_tile_id * BLOCK_M + tl.arange(0, BLOCK_M)
    row_mask = row_offs < M
    active_cols = N - i

    tau_val = tl.load(tau_ptr + bid * stride_tb + i)

    # Phase 1: Compute w = C[row_tile, i:] @ v by looping over column chunks
    # w has shape (BLOCK_M,) -- one dot product result per row
    w = tl.zeros([BLOCK_M], dtype=tl.float32)

    for n_start in range(0, active_cols, BLOCK_N_INNER):
        n_offs = n_start + tl.arange(0, BLOCK_N_INNER)
        n_mask = n_offs < active_cols

        # Load v chunk
        v_vals = tl.load(
            input_ptr + bid * stride_ib + (i + n_offs) * stride_im + i * stride_ik,
            mask=(n_offs > 0) & n_mask,
            other=0.0,
        )
        v_chunk = tl.where(n_offs == 0, 1.0, v_vals)

        # Load C chunk: C[row_offs, i+n_offs]
        c_chunk = tl.load(
            C_ptr
            + bid * stride_cb
            + row_offs[:, None] * stride_cm
            + (i + n_offs[None, :]) * stride_cn,
            mask=row_mask[:, None] & n_mask[None, :],
            other=0.0,
        )

        # Accumulate w += c_chunk @ v_chunk (reduce over cols)
        w += tl.sum(c_chunk.to(tl.float32) * v_chunk.to(tl.float32)[None, :], axis=1)

    # Phase 2: Update C[row_tile, i:] -= tau * w * v^T
    for n_start in range(0, active_cols, BLOCK_N_INNER):
        n_offs = n_start + tl.arange(0, BLOCK_N_INNER)
        n_mask = n_offs < active_cols

        v_vals = tl.load(
            input_ptr + bid * stride_ib + (i + n_offs) * stride_im + i * stride_ik,
            mask=(n_offs > 0) & n_mask,
            other=0.0,
        )
        v_chunk = tl.where(n_offs == 0, 1.0, v_vals)

        c_chunk = tl.load(
            C_ptr
            + bid * stride_cb
            + row_offs[:, None] * stride_cm
            + (i + n_offs[None, :]) * stride_cn,
            mask=row_mask[:, None] & n_mask[None, :],
            other=0.0,
        )

        c_chunk = c_chunk - (
            tau_val * w.to(v_chunk.dtype)[:, None] * v_chunk[None, :]
        ).to(c_chunk.dtype)

        tl.store(
            C_ptr
            + bid * stride_cb
            + row_offs[:, None] * stride_cm
            + (i + n_offs[None, :]) * stride_cn,
            c_chunk,
            mask=row_mask[:, None] & n_mask[None, :],
        )


# =============================================================================
# Python wrapper — unified 2D/3D dispatch via stride
# =============================================================================


def ormqr(input, tau, other, left=True, transpose=False):
    """
    Computes the matrix-matrix multiplication of a product of Householder matrices
    with a general matrix using Triton kernels.

    Multiplies a m x n matrix C (given by other) with a matrix Q,
    where Q is represented using Householder reflectors (input, tau).

    If left is True then op(Q) @ C is computed, otherwise C @ op(Q).
    If transpose is True then op is the conjugate transpose, otherwise identity.

    Strategy:
    - Small matrices (<=128 in both dims of active region): fused single-block kernel
    - Large matrices: per-reflector tiled kernel with grid over col/row tiles

    All computation is in pure Triton kernels. No torch small ops on device data.
    CUDA-graph compatible.

    Args:
        input: tensor of shape (*, mn, k) containing Householder vectors.
        tau: tensor of shape (*, min(mn, k)) containing Householder scalars.
        other: tensor of shape (*, m, n) - the matrix to multiply.
        left: if True, compute op(Q) @ C; otherwise C @ op(Q).
        transpose: if True, op = transpose; otherwise op = identity.

    Returns:
        The result of the matrix multiplication.
    """
    logger.debug("GEMS ORMQR")
    assert input.dtype in (
        torch.float32,
        torch.float64,
    ), f"ormqr only supports float32 and float64, got {input.dtype}"

    # Make contiguous output copy
    C = other.clone().contiguous()
    input_c = input.contiguous()
    tau_c = tau.contiguous()

    # Unified 2D/3D handling via strides
    if C.dim() > 2:
        batch_shape = C.shape[:-2]
        M, N = C.shape[-2], C.shape[-1]
        k = tau_c.shape[-1]
        B = 1
        for s in batch_shape:
            B *= s
        C_flat = C.reshape(B, M, N)
        input_flat = input_c.reshape(B, *input_c.shape[-2:])
        tau_flat = tau_c.reshape(B, k)
        stride_cb = C_flat.stride(0)
        stride_cm = C_flat.stride(1)
        stride_cn = C_flat.stride(2)
        stride_ib = input_flat.stride(0)
        stride_im = input_flat.stride(1)
        stride_ik = input_flat.stride(2)
        stride_tb = tau_flat.stride(0)
    else:
        M, N = C.shape
        k = tau_c.shape[0]
        B = 1
        C_flat = C.unsqueeze(0)
        input_flat = input_c.unsqueeze(0)
        tau_flat = tau_c.unsqueeze(0)
        # batch_stride = 0 means all batch elements point to same data
        # but since B=1 it doesn't matter; use real strides
        stride_cb = 0
        stride_cm = C.stride(0)
        stride_cn = C.stride(1)
        stride_ib = 0
        stride_im = input_c.stride(0)
        stride_ik = input_c.stride(1)
        stride_tb = 0

    # Determine iteration order
    # Q = H_0 H_1 ... H_{k-1}, Q^T = H_{k-1} ... H_0
    # Left Q^T @ C (transpose=True): apply H_0..H_{k-1} forward
    # Left Q @ C (transpose=False): apply H_{k-1}..H_0 reverse
    # Right C @ Q (transpose=False): apply H_0..H_{k-1} forward
    # Right C @ Q^T (transpose=True): apply H_{k-1}..H_0 reverse
    if left:
        indices = range(k) if transpose else range(k - 1, -1, -1)
    else:
        indices = range(k - 1, -1, -1) if transpose else range(k)

    if left:
        _apply_left(
            C_flat,
            input_flat,
            tau_flat,
            M,
            N,
            k,
            B,
            indices,
            stride_cb,
            stride_cm,
            stride_cn,
            stride_ib,
            stride_im,
            stride_ik,
            stride_tb,
        )
    else:
        _apply_right(
            C_flat,
            input_flat,
            tau_flat,
            M,
            N,
            k,
            B,
            indices,
            stride_cb,
            stride_cm,
            stride_cn,
            stride_ib,
            stride_im,
            stride_ik,
            stride_tb,
        )

    return C


def _apply_left(
    C,
    input_t,
    tau_t,
    M,
    N,
    k,
    B,
    indices,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
):
    """Apply Householder reflectors from the left."""
    # Decide small vs large path based on max active region
    # For left: active_rows = M - i (max at i=0 is M), cols = N
    use_small = M <= 128 and N <= 128

    if use_small:
        BLOCK_M = triton.next_power_of_2(M)
        BLOCK_N = triton.next_power_of_2(N)
        for i in indices:
            _householder_left_fused_kernel[(B,)](
                C,
                input_t,
                tau_t,
                M,
                N,
                i,
                stride_cb,
                stride_cm,
                stride_cn,
                stride_ib,
                stride_im,
                stride_ik,
                stride_tb,
                BLOCK_M=BLOCK_M,
                BLOCK_N=BLOCK_N,
            )
    else:
        # Large matrix: tiled kernel, one launch per reflector
        BLOCK_N = 128
        BLOCK_M_INNER = 128
        for i in indices:
            num_col_tiles = triton.cdiv(N, BLOCK_N)
            grid = (num_col_tiles, B)
            _householder_apply_left_kernel[grid](
                C,
                input_t,
                tau_t,
                M,
                N,
                i,
                stride_cb,
                stride_cm,
                stride_cn,
                stride_ib,
                stride_im,
                stride_ik,
                stride_tb,
                BLOCK_N=BLOCK_N,
                BLOCK_M_INNER=BLOCK_M_INNER,
            )


def _apply_right(
    C,
    input_t,
    tau_t,
    M,
    N,
    k,
    B,
    indices,
    stride_cb,
    stride_cm,
    stride_cn,
    stride_ib,
    stride_im,
    stride_ik,
    stride_tb,
):
    """Apply Householder reflectors from the right."""
    use_small = M <= 128 and N <= 128

    if use_small:
        BLOCK_M = triton.next_power_of_2(M)
        BLOCK_N = triton.next_power_of_2(N)
        for i in indices:
            _householder_right_fused_kernel[(B,)](
                C,
                input_t,
                tau_t,
                M,
                N,
                i,
                stride_cb,
                stride_cm,
                stride_cn,
                stride_ib,
                stride_im,
                stride_ik,
                stride_tb,
                BLOCK_M=BLOCK_M,
                BLOCK_N=BLOCK_N,
            )
    else:
        # Large matrix: tiled kernel, one launch per reflector
        BLOCK_M = 128
        BLOCK_N_INNER = 128
        for i in indices:
            num_row_tiles = triton.cdiv(M, BLOCK_M)
            grid = (num_row_tiles, B)
            _householder_apply_right_kernel[grid](
                C,
                input_t,
                tau_t,
                M,
                N,
                i,
                stride_cb,
                stride_cm,
                stride_cn,
                stride_ib,
                stride_im,
                stride_ik,
                stride_tb,
                BLOCK_M=BLOCK_M,
                BLOCK_N_INNER=BLOCK_N_INNER,
            )
