# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import builtins
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def slice_kernel_contiguous(
    input_ptr,
    output_ptr,
    input_offset,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Fast path for contiguous slices with step=1."""
    pid = tl.program_id(0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    data = tl.load(input_ptr + input_offset + offsets, mask=mask)
    tl.store(output_ptr + offsets, data, mask=mask)


@triton.jit
def slice_kernel_1d(
    input_ptr,
    output_ptr,
    start,
    step,
    input_stride_0,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Strided 1D slice kernel (handles step != 1)."""
    pid = tl.program_id(0)
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    in_idx = start + offsets * step
    data = tl.load(input_ptr + in_idx * input_stride_0, mask=mask)
    tl.store(output_ptr + offsets, data, mask=mask)


@triton.jit
def slice_kernel_2d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    output_size_0,
    output_size_1,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 2D slice kernel."""
    pid_0 = tl.program_id(0)
    pid_1 = tl.program_id(1)

    out_idx_0 = pid_0
    out_idx_1_base = pid_1 * BLOCK_SIZE
    out_idx_1 = out_idx_1_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_1 < output_size_1

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)

    input_offset = in_idx_0 * input_stride_0 + in_idx_1 * input_stride_1
    output_offset = out_idx_0 * output_size_1 + out_idx_1

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


@triton.jit
def slice_kernel_3d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    input_stride_2,
    output_size_1,
    output_size_2,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 3D slice kernel."""
    pid_0 = tl.program_id(0)
    pid_1 = tl.program_id(1)
    pid_2_base = tl.program_id(2)

    out_idx_0 = pid_0
    out_idx_1 = pid_1
    out_idx_2_base = pid_2_base * BLOCK_SIZE
    out_idx_2 = out_idx_2_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_2 < output_size_2

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)
    in_idx_2 = tl.where(dim == 2, start + out_idx_2 * step, out_idx_2)

    input_offset = (
        in_idx_0 * input_stride_0
        + in_idx_1 * input_stride_1
        + in_idx_2 * input_stride_2
    )
    output_offset = (
        out_idx_0 * (output_size_1 * output_size_2)
        + out_idx_1 * output_size_2
        + out_idx_2
    )

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


@triton.jit
def slice_kernel_4d(
    input_ptr,
    output_ptr,
    dim,
    start,
    step,
    input_stride_0,
    input_stride_1,
    input_stride_2,
    input_stride_3,
    output_size_0,
    output_size_1,
    output_size_2,
    output_size_3,
    BLOCK_SIZE: tl.constexpr,
):
    """Optimized 4D slice kernel using 3D grid (flatten first two dims)."""
    pid_01 = tl.program_id(0)  # Combined dimension 0 and 1
    pid_2 = tl.program_id(1)
    pid_3_base = tl.program_id(2)

    # Decompose combined dimension
    out_idx_0 = pid_01 // output_size_1
    out_idx_1 = pid_01 % output_size_1
    out_idx_2 = pid_2
    out_idx_3_base = pid_3_base * BLOCK_SIZE
    out_idx_3 = out_idx_3_base + tl.arange(0, BLOCK_SIZE)
    mask = out_idx_3 < output_size_3

    # Map to input coordinates
    in_idx_0 = tl.where(dim == 0, start + out_idx_0 * step, out_idx_0)
    in_idx_1 = tl.where(dim == 1, start + out_idx_1 * step, out_idx_1)
    in_idx_2 = tl.where(dim == 2, start + out_idx_2 * step, out_idx_2)
    in_idx_3 = tl.where(dim == 3, start + out_idx_3 * step, out_idx_3)

    input_offset = (
        in_idx_0 * input_stride_0
        + in_idx_1 * input_stride_1
        + in_idx_2 * input_stride_2
        + in_idx_3 * input_stride_3
    )
    output_offset = (
        out_idx_0 * (output_size_1 * output_size_2 * output_size_3)
        + out_idx_1 * (output_size_2 * output_size_3)
        + out_idx_2 * output_size_3
        + out_idx_3
    )

    data = tl.load(input_ptr + input_offset, mask=mask, other=0.0)
    tl.store(output_ptr + output_offset, data, mask=mask)


def slice(input_tensor, dim, start, end, step):
    logger.debug("GEMS SLICE")
    # slice is a pure memory-movement op; reject only bool/complex which the
    # kernels' element-wise load/store path does not handle.
    assert input_tensor.dtype not in (
        torch.bool,
        torch.complex64,
        torch.complex128,
    ), f"slice: unsupported dtype {input_tensor.dtype}"
    # Normalize negative indices
    input_shape = list(input_tensor.shape)
    ndim = len(input_shape)

    if start is None:
        start = 0
    if end is None:
        end = input_shape[dim]
    if step is None:
        step = 1

    # Handle negative indices
    if start < 0:
        start = input_shape[dim] + start
    if end < 0:
        end = input_shape[dim] + end

    # Clamp to valid range
    start = max(0, min(start, input_shape[dim]))
    end = max(0, min(end, input_shape[dim]))

    # Compute output shape
    output_shape = input_shape.copy()
    slice_size = max(0, (end - start + step - 1) // step)
    output_shape[dim] = slice_size

    # Allocate output
    output = torch.empty(
        output_shape, dtype=input_tensor.dtype, device=input_tensor.device
    )

    n_elements = output.numel()
    if n_elements == 0:
        return output

    # For contiguous inputs, use a memcpy-style approach with view + contiguous
    # This leverages PyTorch's optimized memory copy primitives
    if input_tensor.is_contiguous() and step == 1:
        # Build slice tuple
        slices = [builtins.slice(None)] * ndim
        slices[dim] = builtins.slice(start, end, step)

        # Create view and copy to contiguous output
        view = input_tensor[tuple(slices)]
        output.copy_(view)
        return output

    # Fast path: contiguous slice with step=1 on innermost dimension
    if step == 1 and dim == ndim - 1:
        # 1024 balances occupancy and register pressure for coalesced memory access
        BLOCK_SIZE = 1024
        grid = (triton.cdiv(n_elements, BLOCK_SIZE),)

        # Compute the starting offset in the input tensor
        input_offset = start
        for i in range(ndim - 1):
            input_offset *= input_shape[i]

        slice_kernel_contiguous[grid](
            input_tensor,
            output,
            input_offset * input_tensor.stride(ndim - 1),
            n_elements,
            BLOCK_SIZE=BLOCK_SIZE,
        )
        return output

    # Multi-dimensional grid approach with larger block size
    BLOCK_SIZE = 1024
    input_strides = list(input_tensor.stride())

    if ndim == 2:
        grid = (output_shape[0], triton.cdiv(output_shape[1], BLOCK_SIZE))
        slice_kernel_2d[grid](
            input_tensor,
            output,
            dim,
            start,
            step,
            input_strides[0],
            input_strides[1],
            output_shape[0],
            output_shape[1],
            BLOCK_SIZE=BLOCK_SIZE,
        )
    elif ndim == 3:
        grid = (
            output_shape[0],
            output_shape[1],
            triton.cdiv(output_shape[2], BLOCK_SIZE),
        )
        slice_kernel_3d[grid](
            input_tensor,
            output,
            dim,
            start,
            step,
            input_strides[0],
            input_strides[1],
            input_strides[2],
            output_shape[1],
            output_shape[2],
            BLOCK_SIZE=BLOCK_SIZE,
        )
    elif ndim == 4:
        grid = (
            output_shape[0] * output_shape[1],
            output_shape[2],
            triton.cdiv(output_shape[3], BLOCK_SIZE),
        )
        slice_kernel_4d[grid](
            input_tensor,
            output,
            dim,
            start,
            step,
            input_strides[0],
            input_strides[1],
            input_strides[2],
            input_strides[3],
            output_shape[0],
            output_shape[1],
            output_shape[2],
            output_shape[3],
            BLOCK_SIZE=BLOCK_SIZE,
        )
    elif ndim == 1:
        # 1D strided slice (step may be != 1)
        grid = (triton.cdiv(n_elements, BLOCK_SIZE),)
        slice_kernel_1d[grid](
            input_tensor,
            output,
            start,
            step,
            input_strides[0],
            n_elements,
            BLOCK_SIZE=BLOCK_SIZE,
        )
    else:
        # Fallback for 5D+: flatten to a generic strided copy per output element
        # using PyTorch indexing (correctness first for rare high-rank cases).
        slices = [builtins.slice(None)] * ndim
        slices[dim] = builtins.slice(start, end, step)
        output.copy_(input_tensor[tuple(slices)])

    return output
