# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.mvlgamma_ import mvlgamma_

logger = logging.getLogger(__name__)


def special_multigammaln(self, p):
    """Computes the multivariate log-gamma function for each element of the input.

    `special_multigammaln` is the out-of-place counterpart of `mvlgamma_`, so the
    input is cloned before the existing in-place kernel is applied to the copy.

    The reused kernel unrolls the lgamma sum, which limits `p` to at most 12.
    """
    logger.debug("GEMS SPECIAL_MULTIGAMMALN")
    return mvlgamma_(self.clone(), p)
