# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_t_kernel(x, n):
    # Shifted Chebyshev polynomial of the first kind: T_n^*(x)
    # Formula: T_n^*(x) = T_n(2x-1)
    # Where T_n(y) = cos(n * arccos(y))
    # The shifted polynomial is defined on [0, 1]

    # Compute in the promoted input precision so float64 keeps full accuracy.
    # Shift from [0, 1] to [-1, 1]
    x_shifted = x * 2.0 - 1.0

    # Clamp to valid range for acos to avoid numerical issues
    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    # T_n(y) = cos(n * arccos(y))
    return tl_extra_shim.cos(n * tl_extra_shim.acos(x_shifted))


# Kernel for scalar n (n is not a tensor)
@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "INT_TO_FLOAT")])
@triton.jit
def shifted_chebyshev_polynomial_t_kernel_scalar_n(x, n):
    # Same as above but n is a scalar
    x_shifted = x * 2.0 - 1.0

    x_shifted = tl.where(x_shifted > 1.0, 1.0, x_shifted)
    x_shifted = tl.where(x_shifted < -1.0, -1.0, x_shifted)

    return tl_extra_shim.cos(n * tl_extra_shim.acos(x_shifted))


def special_shifted_chebyshev_polynomial_t(x, n):
    logger.debug("GEMS SPECIAL_SHIFTED_CHEBYSHEV_POLYNOMIAL_T")
    # Matches the eager CUDA kernel, which has no Half/BFloat16 implementation.
    if x.dtype in (torch.float16, torch.bfloat16):
        raise ValueError(
            f"Unsupported dtype {x.dtype}: "
            "shifted_chebyshev_polynomial_t has no Half/BFloat16 implementation"
        )
    # Handle scalar n
    if not isinstance(n, torch.Tensor):
        return shifted_chebyshev_polynomial_t_kernel_scalar_n(x, n)
    return shifted_chebyshev_polynomial_t_kernel(x, n)
