# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
from typing import List

import torch

logger = logging.getLogger(__name__)


def unflatten(A: torch.Tensor, dim: int, sizes: List[int]) -> torch.Tensor:
    r"""Expand a single dimension of a tensor into multiple dimensions.

    This is the inverse operation of :func:`torch.flatten`.

    Args:
        A (torch.Tensor): Input tensor.
        dim (int): Dimension to unflatten.
        sizes (List[int]): New shape of the unflattened dimension.

    Returns:
        torch.Tensor: A view of the input tensor with the specified
            dimension unflattened.
    """
    logger.debug("GEMS unflatten")

    # Handle negative dim
    if dim < 0:
        dim = dim + A.ndim

    # Validate that product of sizes matches the dimension size
    dim_size = A.size(dim)
    product = 1
    inferred_idx = -1
    for i, s in enumerate(sizes):
        if s == -1:
            if inferred_idx != -1:
                raise RuntimeError("only one dimension can be inferred")
            inferred_idx = i
        else:
            product *= s

    if inferred_idx != -1:
        if dim_size % product != 0:
            raise RuntimeError(
                f"inferred size {dim_size // product} is not a factor of "
                f"dimension size {dim_size}"
            )
        sizes = list(sizes)
        sizes[inferred_idx] = dim_size // product
    else:
        if product != dim_size:
            raise RuntimeError(
                f"unflatten: Provided sizes {sizes} don't multiply up to the "
                f"size of dim {dim} ({dim_size}) in the input tensor"
            )

    # Build new shape: shape[:dim] + sizes + shape[dim+1:]
    new_shape = list(A.shape[:dim]) + list(sizes) + list(A.shape[dim + 1 :])

    return A.view(new_shape)
